version: 2

updates:
  # This configuration will:
  # - Check for updates weekly on Monday at 12:00 UTC
  # - Create up to 5 pull requests at a time
  # - Ignore updates for the `@clerk/*` packages
  # - Commit changes with the prefix `chore(repo)` and include the scope
  # - Group updates into two categories:
  #   - `Dependency updates [Patch]` for patch updates
  #   - `Dependency updates [Minor]` for minor updates
  #   - Remaining Major updates won't be grouped
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@clerk/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(repo)"
      include: "scope"
    groups:
      "Dependency updates [Patch]":
        update-types:
          - "patch"
        patterns:
          - "*"
      "Dependency updates [Minor]":
        update-types:
          - "minor"
        patterns:
          - "*"

  # This configuration will:
  # - Check for updates weekly on Wednesday at 12:00 UTC
  # - Create one pull request at a time
  # - Commit changes with the prefix `chore(repo)` and include the scope
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(repo)"
      include: "scope"
