# See https://github.com/actions/labeler

backend:
  - packages/backend/**

chrome-extension:
  - packages/chrome-extension/**

clerk-js:
  - packages/clerk-js/**

elements:
  - packages/elements/**

express:
  - packages/express/**

expo:
  - packages/expo/**

fastify:
  - packages/fastify/**

localizations:
  - packages/localizations/**

nextjs:
  - packages/nextjs/**

react:
  - packages/react/**

remix:
  - packages/remix/**

sdk-node:
  - packages/sdk-node/**

themes:
  - packages/themes/**

types:
  - packages/types/**

testing:
  - packages/testing/**

playground:
  - playground/**

actions:
  - .github/workflows/**

integration:
  - integration/**

tanstack:
  - packages/tanstack-start/**
