# See https://github.com/actions/labeler

astro:
  - packages/astro/**

backend:
  - packages/backend/**

chrome-extension:
  - packages/chrome-extension/**

clerk-js:
  - packages/clerk-js/**

expo:
  - packages/expo/**

express:
  - packages/express/**

fastify:
  - packages/fastify/**

localizations:
  - packages/localizations/**

nextjs:
  - packages/nextjs/**

nuxt:
  - packages/nuxt/**

react:
  - packages/react/**

react-router:
  - packages/react-router/**

tanstack:
  - packages/tanstack-react-start/**

testing:
  - packages/testing/**

themes:
  - packages/themes/**

vue:
  - packages/vue/**

playground:
  - playground/**

actions:
  - .github/workflows/**

integration:
  - integration/**

agent-toolkit:
  - packages/agent-toolkit/**
