name: Checkout, setup node and dependencies
description: Checkout, setup node and dependencies
inputs:
  node-version:
    description: 'The node version to use'
    required: false
    default: '18'
  use-turbo-cache:
    description: 'Whether or not the turbo cache should be restored. Defaults to false.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        cache: "npm"
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: Install dependencies
      shell: bash
      run: npm ci
    - if: ${{ inputs.use-turbo-cache == 'true' }} 
      name: Download turbo cache
      uses: actions/download-artifact@v3
      with:
        name: package-artifacts
        path: ./node_modules/.cache/turbo
