export default [
  { label: '@clerk/nextjs', value: 'nextjs' },
  { label: '@clerk/redwood', value: 'redwood' },
  { label: '@clerk/react', value: 'react' },
  { label: '@clerk/expo', value: 'expo' },
  { label: '@clerk/fastify', value: 'fastify' },
  { label: '@clerk/express', value: 'express' },
  { label: '@clerk/clerk-js', value: 'js' },
  { label: '@clerk/clerk-sdk-node', value: 'node' },
  { label: '@clerk/backend', value: 'backend' },
  { label: '@clerk/localizations', value: 'localizations' },
  { label: '@clerk/shared', value: 'shared' },
  { label: '@clerk/shared/types', value: 'types' },
  { label: '@clerk/chrome-extension', value: 'chrome-extension' },
];
