packages:
  - 'packages/*'

catalog:
  typescript: 5.6.3

catalogs:
  # Can be referenced through "catalog:react"
  react:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.12
    '@types/react-dom': 18.3.1
