packages:
  - 'packages/*'

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@clerk/*'

catalogs:
  # Can be referenced through "catalog:react"
  react:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.26
    '@types/react-dom': 18.3.7

  # Can be referenced through "catalog:peer-react"
  peer-react:
    react: ^18.0.0 || ~19.0.3 || ~19.1.4 || ~19.2.3 || ~19.3.0-0
    react-dom: ^18.0.0 || ~19.0.3 || ~19.1.4 || ~19.2.3 || ~19.3.0-0

  # Can be referenced through "catalog:repo"
  repo:
    tslib: 2.8.1
    tsdown: 0.15.7
    tsup: 8.5.0
    typescript: 5.8.3
    zx: 8.8.5
    rolldown: 1.0.0-beta.43
