packages:
  - packages/*

catalogs:
  peer-react:
    react: ^18.0.0 || ^19.0.3 || ^19.1.4 || ^19.2.3 || ^19.3.0-0
    react-dom: ^18.0.0 || ^19.0.0 || ^19.0.0-0
  react:
    '@types/react': 18.3.26
    '@types/react-dom': 18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  repo:
    tslib: 2.8.1
    tsdown: 0.15.7
    tsup: 8.5.0
    typescript: 5.8.3
    zx: 8.8.5
    rolldown: 1.0.0-beta.47
    vue: 3.5.24
  module-manager:
    '@base-org/account': 2.0.1
    '@coinbase/wallet-sdk': 4.3.0
    '@zxcvbn-ts/core': 3.0.4
    '@zxcvbn-ts/language-common': 3.0.4

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@clerk/*'
