name: Run Verdaccio
description: Checkout, setup node and dependencies
inputs:
  auth-email:
    description: 'The email to use for auth'
    required: false
    default: 'test@test.com'
  auth-password:
    description: 'The pass to use for auth'
    required: false
    default: 'pass'
  auth-user:
    description: 'The user to use for auth'
    required: false
    default: 'user'
  publish-cmd:
    description: 'The command to use to publish'
    required: true
  registry:
    description: 'The registry to use'
    required: false
    default: 'http://localhost:4873'

runs:
  using: 'composite'
  steps:
    - name: Update NPM Registry to Verdaccio
      shell: bash
      run: pnpm set registry ${{ inputs.registry }}

    - name: Run Verdaccio (using publish config)
      shell: bash
      run: |
        nohup ./node_modules/.bin/verdaccio --config ./verdaccio.publish.yaml & echo "VERDACCIO_PID=$!" >> $GITHUB_ENV
        # Wait for Verdaccio to start and verify it's responding
        for i in {1..10}; do
          if curl -f ${{ inputs.registry }}/ > /dev/null 2>&1; then
            echo "Verdaccio is up and running"
            break
          fi
          echo "Waiting for Verdaccio to start (attempt $i)..."
          sleep 2
        done
        pnpm config set $(echo ${{ inputs.registry }} | sed -E 's/https?://')/:_authToken secretToken

    - name: Publish to Verdaccio
      shell: bash
      run: ${{ inputs.publish-cmd }}

    - name: Stop Verdaccio
      shell: bash
      run: |
        if [ -n "$VERDACCIO_PID" ]; then
          kill -9 $VERDACCIO_PID || true
          sleep 2
        fi

    - name: Run Verdaccio (using install config)
      shell: bash
      run: |
        nohup ./node_modules/.bin/verdaccio --config ./verdaccio.install.yaml & echo "VERDACCIO_PID=$!" >> $GITHUB_ENV
        # Wait for Verdaccio to start and verify it's responding
        for i in {1..10}; do
          if curl -f ${{ inputs.registry }}/ > /dev/null 2>&1; then
            echo "Verdaccio is up and running"
            break
          fi
          echo "Waiting for Verdaccio to start (attempt $i)..."
          sleep 2
        done
        pnpm config set $(echo ${{ inputs.registry }} | sed -E 's/https?://')/:_authToken secretToken
        # Verify proxy is working by trying to fetch a known package
        pnpm view semver > /dev/null 2>&1 || echo "Warning: Could not fetch semver package, proxy might not be working"
