/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { remap as remap$ } from '../../lib/primitives.js';
import { safeParse } from '../../lib/schemas.js';
import { Result as SafeParseResult } from '../../types/fp.js';
import { SDKValidationError } from '../errors/sdkvalidationerror.js';

export type CreateOAuthApplicationRequestBody = {
  /**
   * The name of the new OAuth application.
   *
   * @remarks
   * Max length: 256
   */
  name: string;
  /**
   * An array of redirect URIs of the new OAuth application
   */
  redirectUris?: Array<string> | null | undefined;
  /**
   * The callback URL of the new OAuth application
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  callbackUrl?: string | null | undefined;
  /**
   * Define the allowed scopes for the new OAuth applications that dictate the user payload of the OAuth user info endpoint. Available scopes are `profile`, `email`, `public_metadata`, `private_metadata`. Provide the requested scopes as a string, separated by spaces.
   */
  scopes?: string | null | undefined;
  /**
   * If true, this client is public and you can use the Proof Key of Code Exchange (PKCE) flow.
   */
  public?: boolean | null | undefined;
};

/** @internal */
export const CreateOAuthApplicationRequestBody$inboundSchema: z.ZodType<
  CreateOAuthApplicationRequestBody,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    name: z.string(),
    redirect_uris: z.nullable(z.array(z.string())).optional(),
    callback_url: z.nullable(z.string()).optional(),
    scopes: z.nullable(z.string().default('profile email')),
    public: z.nullable(z.boolean()).optional(),
  })
  .transform(v => {
    return remap$(v, {
      redirect_uris: 'redirectUris',
      callback_url: 'callbackUrl',
    });
  });

/** @internal */
export type CreateOAuthApplicationRequestBody$Outbound = {
  name: string;
  redirect_uris?: Array<string> | null | undefined;
  callback_url?: string | null | undefined;
  scopes: string | null;
  public?: boolean | null | undefined;
};

/** @internal */
export const CreateOAuthApplicationRequestBody$outboundSchema: z.ZodType<
  CreateOAuthApplicationRequestBody$Outbound,
  z.ZodTypeDef,
  CreateOAuthApplicationRequestBody
> = z
  .object({
    name: z.string(),
    redirectUris: z.nullable(z.array(z.string())).optional(),
    callbackUrl: z.nullable(z.string()).optional(),
    scopes: z.nullable(z.string().default('profile email')),
    public: z.nullable(z.boolean()).optional(),
  })
  .transform(v => {
    return remap$(v, {
      redirectUris: 'redirect_uris',
      callbackUrl: 'callback_url',
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOAuthApplicationRequestBody$ {
  /** @deprecated use `CreateOAuthApplicationRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateOAuthApplicationRequestBody$inboundSchema;
  /** @deprecated use `CreateOAuthApplicationRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateOAuthApplicationRequestBody$outboundSchema;
  /** @deprecated use `CreateOAuthApplicationRequestBody$Outbound` instead. */
  export type Outbound = CreateOAuthApplicationRequestBody$Outbound;
}

export function createOAuthApplicationRequestBodyToJSON(
  createOAuthApplicationRequestBody: CreateOAuthApplicationRequestBody,
): string {
  return JSON.stringify(CreateOAuthApplicationRequestBody$outboundSchema.parse(createOAuthApplicationRequestBody));
}

export function createOAuthApplicationRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateOAuthApplicationRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    x => CreateOAuthApplicationRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOAuthApplicationRequestBody' from JSON`,
  );
}
