/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailAndSmsTemplatesUpsert } from '../funcs/emailAndSmsTemplatesUpsert.js';
import { ClientSDK, RequestOptions } from '../lib/sdks.js';
import * as components from '../models/components/index.js';
import * as operations from '../models/operations/index.js';
import { unwrapAsync } from '../types/fp.js';

export class EmailAndSmsTemplates extends ClientSDK {
  /**
   * Update a template for a given type and slug
   *
   * @remarks
   * Updates the existing template of the given type and slug
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async upsert(request: operations.UpsertTemplateRequest, options?: RequestOptions): Promise<components.Template> {
    return unwrapAsync(emailAndSmsTemplatesUpsert(this, request, options));
  }
}
