blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://clerk.com/discord
    about: Ask questions, get help, and discuss new things you're building with the Clerk community
  - name: Documentation
    url: https://clerk.com/docs
    about: Learn more about Clerk and how to use it