import { MODEL_COMPATIBILITY, PROPERTY_COMPATIBILITY } from './compatibility';
import {
  emitRef,
  type GeneratedSwiftFile,
  isOptionalRef,
  optionalize,
  type SwiftDecl,
  type SwiftEnum,
  type SwiftMethod,
  type SwiftMethodFacade,
  type SwiftMethodParam,
  type SwiftProperty,
  type SwiftRef,
  type SwiftStruct,
} from './model';
import { escapeSwiftString, swiftIdent } from './naming';

const GENERATED_HEADER = `// Generated by packages/shared/scripts/generate-swift-models.ts. Do not edit.\n`;

export function emitHelperFile(): string {
  return `${GENERATED_HEADER}
import Foundation

public enum JSONValue: Codable, Equatable, Hashable, Sendable {
  case null
  case bool(Bool)
  case number(Double)
  case string(String)
  case array([JSONValue])
  case object([String: JSONValue])

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() {
      self = .null
    } else if let value = try? container.decode(Bool.self) {
      self = .bool(value)
    } else if let value = try? container.decode(Double.self) {
      self = .number(value)
    } else if let value = try? container.decode(String.self) {
      self = .string(value)
    } else if let value = try? container.decode([JSONValue].self) {
      self = .array(value)
    } else if let value = try? container.decode([String: JSONValue].self) {
      self = .object(value)
    } else {
      throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unsupported JSON value")
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .null:
      try container.encodeNil()
    case .bool(let value):
      try container.encode(value)
    case .number(let value):
      try container.encode(value)
    case .string(let value):
      try container.encode(value)
    case .array(let value):
      try container.encode(value)
    case .object(let value):
      try container.encode(value)
    }
  }
}

public struct FAPIJSONKey: CodingKey {
  public var stringValue: String
  public var intValue: Int?

  public init(_ value: String) {
    stringValue = value
    intValue = nil
  }

  public init?(stringValue: String) {
    self.stringValue = stringValue
    intValue = nil
  }

  public init?(intValue: Int) {
    self.stringValue = String(intValue)
    self.intValue = intValue
  }
}

extension KeyedDecodingContainer where Key == FAPIJSONKey {
  public func decodeFlexible<T: Decodable>(_ type: T.Type, snake: String, camel: String) throws -> T {
    if let value = try? decode(type, forKey: FAPIJSONKey(snake)) {
      return value
    }
    return try decode(type, forKey: FAPIJSONKey(camel))
  }

  public func decodeIfPresentFlexible<T: Decodable>(_ type: T.Type, snake: String, camel: String) throws -> T? {
    if let value = try? decodeIfPresent(type, forKey: FAPIJSONKey(snake)) {
      return value
    }
    return try decodeIfPresent(type, forKey: FAPIJSONKey(camel))
  }

  public func decodeFlexibleDefault<T: Decodable>(
    _ type: T.Type,
    snake: String,
    camel: String,
    default defaultValue: @autoclosure () -> T
  ) throws -> T {
    try decodeIfPresentFlexible(type, snake: snake, camel: camel) ?? defaultValue()
  }

  public func decodeMillisecondsDate(snake: String, camel: String) throws -> Date {
    let millis = try decodeFlexible(Int64.self, snake: snake, camel: camel)
    return Date(timeIntervalSince1970: TimeInterval(millis) / 1000)
  }

  public func decodeIfPresentMillisecondsDate(snake: String, camel: String) throws -> Date? {
    guard let millis = try decodeIfPresentFlexible(Int64.self, snake: snake, camel: camel) else {
      return nil
    }
    return Date(timeIntervalSince1970: TimeInterval(millis) / 1000)
  }
}

extension KeyedDecodingContainer {
  func decodeMillisecondsDate(forKey key: Key) throws -> Date {
    let millis = try decode(Int64.self, forKey: key)
    return Date(timeIntervalSince1970: TimeInterval(millis) / 1000)
  }

  func decodeIfPresentMillisecondsDate(forKey key: Key) throws -> Date? {
    guard let millis = try decodeIfPresent(Int64.self, forKey: key) else {
      return nil
    }
    return Date(timeIntervalSince1970: TimeInterval(millis) / 1000)
  }
}

extension KeyedEncodingContainer {
  mutating func encodeMillisecondsDate(_ date: Date, forKey key: Key) throws {
    try encode(Int64((date.timeIntervalSince1970 * 1000).rounded()), forKey: key)
  }

  mutating func encodeIfPresentMillisecondsDate(_ date: Date?, forKey key: Key) throws {
    guard let date else {
      return
    }
    try encodeMillisecondsDate(date, forKey: key)
  }
}
`;
}

function emitEnum(decl: SwiftEnum): string {
  const rawValue = MODEL_COMPATIBILITY[decl.name]?.rawValueEnum
    ? [
        '',
        '  public var rawValue: String {',
        '    switch self {',
        ...decl.cases.map(item => `    case .${item.name}:\n      "${escapeSwiftString(item.raw)}"`),
        '    case .unknown(let value):\n      value',
        '    }',
        '  }',
        '',
        '  public init(rawValue: String) {',
        '    switch rawValue {',
        ...decl.cases.map(item => `    case "${escapeSwiftString(item.raw)}":\n      self = .${item.name}`),
        '    default:\n      self = .unknown(rawValue)',
        '    }',
        '  }',
      ]
    : [];
  return [
    GENERATED_HEADER,
    'import Foundation',
    '',
    `public enum ${decl.name}: Codable, Equatable, Hashable, Sendable {`,
    ...decl.cases.map(item => `  case ${item.name}`),
    '  case unknown(String)',
    ...rawValue,
    '',
    '  public init(from decoder: Decoder) throws {',
    '    let container = try decoder.singleValueContainer()',
    '    let value = try container.decode(String.self)',
    '    switch value {',
    ...decl.cases.map(item => `    case "${escapeSwiftString(item.raw)}":\n      self = .${item.name}`),
    '    default:\n      self = .unknown(value)',
    '    }',
    '  }',
    '',
    '  public func encode(to encoder: Encoder) throws {',
    '    var container = encoder.singleValueContainer()',
    '    switch self {',
    ...decl.cases.map(item => `    case .${item.name}:\n      try container.encode("${escapeSwiftString(item.raw)}")`),
    '    case .unknown(let value):\n      try container.encode(value)',
    '    }',
    '  }',
    '}',
    '',
  ].join('\n');
}

function emitDecode(property: SwiftProperty, owner: string): string {
  const custom = PROPERTY_COMPATIBILITY[`${owner}.${property.wireName}`]?.decode;
  if (custom) {
    return custom;
  }
  const snake = escapeSwiftString(property.wireName);
  const camel = escapeSwiftString(property.name.replace(/`/g, ''));
  const optional = isOptionalRef(property.type);
  const defaultValue = PROPERTY_COMPATIBILITY[`${owner}.${property.wireName}`]?.decodeDefault;
  if (property.isDate) {
    if (defaultValue !== undefined) {
      return `    self.${property.name} = try container.decodeIfPresentMillisecondsDate(snake: "${snake}", camel: "${camel}") ?? ${defaultValue}`;
    }
    return optional
      ? `    self.${property.name} = try container.decodeIfPresentMillisecondsDate(snake: "${snake}", camel: "${camel}")`
      : `    self.${property.name} = try container.decodeMillisecondsDate(snake: "${snake}", camel: "${camel}")`;
  }
  const typeName = emitRef(optional && property.type.kind === 'optional' ? property.type.of : property.type);
  if (defaultValue !== undefined) {
    return `    self.${property.name} = try container.decodeFlexibleDefault(${typeName}.self, snake: "${snake}", camel: "${camel}", default: ${defaultValue})`;
  }
  return optional
    ? `    self.${property.name} = try container.decodeIfPresentFlexible(${typeName}.self, snake: "${snake}", camel: "${camel}")`
    : `    self.${property.name} = try container.decodeFlexible(${typeName}.self, snake: "${snake}", camel: "${camel}")`;
}

function emitEncode(property: SwiftProperty, owner: string): string {
  const custom = PROPERTY_COMPATIBILITY[`${owner}.${property.wireName}`]?.encode;
  if (custom) {
    return custom;
  }
  const key = `.${property.name}`;
  const optional = isOptionalRef(property.type);
  if (property.isDate) {
    return optional
      ? `    try container.encodeIfPresentMillisecondsDate(${property.name}, forKey: ${key})`
      : `    try container.encodeMillisecondsDate(${property.name}, forKey: ${key})`;
  }
  return optional
    ? `    try container.encodeIfPresent(${property.name}, forKey: ${key})`
    : `    try container.encode(${property.name}, forKey: ${key})`;
}

function emitInitDefault(property: SwiftProperty, owner: string): string {
  const typeName = emitRef(property.type);
  const initDefault = PROPERTY_COMPATIBILITY[`${owner}.${property.wireName}`]?.initDefault;
  if (initDefault !== undefined) {
    return `    ${property.name}: ${typeName} = ${initDefault}`;
  }
  return isOptionalRef(property.type) ? `    ${property.name}: ${typeName} = nil` : `    ${property.name}: ${typeName}`;
}

function emitHash(decl: SwiftStruct): string[] {
  const fields = MODEL_COMPATIBILITY[decl.name]?.hashFields;
  if (!fields) {
    return [];
  }
  return [
    '',
    '  public func hash(into hasher: inout Hasher) {',
    ...fields.map(field => `    hasher.combine(${field})`),
    '  }',
  ];
}

function emitEquals(decl: SwiftStruct): string[] {
  const fields = MODEL_COMPATIBILITY[decl.name]?.equalityFields;
  if (!fields?.length) {
    return [];
  }
  return [
    '',
    `  public static func == (lhs: ${decl.name}, rhs: ${decl.name}) -> Bool {`,
    `    lhs.${fields[0]} == rhs.${fields[0]}`,
    ...fields.slice(1).map(field => `      && lhs.${field} == rhs.${field}`),
    '  }',
  ];
}

function emitErrorClass(decl: SwiftStruct): string {
  const initParams = decl.properties.map(property => emitInitDefault(property, decl.name));
  const initBody = decl.properties.map(property => `    self.${property.name} = ${property.name}`);
  const codingKeys = decl.properties.map(property => {
    const caseName = property.name.replace(/`/g, '');
    return caseName === property.wireName
      ? `    case ${property.name}`
      : `    case ${property.name} = "${escapeSwiftString(property.wireName)}"`;
  });
  const equals = decl.properties.map(property => `      && lhs.${property.name} == rhs.${property.name}`);
  equals[0] = `    lhs.${decl.properties[0].name} == rhs.${decl.properties[0].name}`;
  return [
    GENERATED_HEADER,
    'import Foundation',
    '',
    'public final class ClerkAPIError: Codable, Equatable, @unchecked Sendable, Error, LocalizedError {',
    ...decl.properties.map(property => `  public var ${property.name}: ${emitRef(property.type)}`),
    '',
    '  public static var empty: ClerkAPIError { ClerkAPIError(code: "", message: "") }',
    '',
    '  public init(',
    initParams.join(',\n'),
    '  ) {',
    ...initBody,
    '  }',
    '',
    '  public var errorDescription: String? {',
    '    longMessage ?? (message.isEmpty ? nil : message)',
    '  }',
    '',
    '  public static func == (lhs: ClerkAPIError, rhs: ClerkAPIError) -> Bool {',
    ...equals,
    '  }',
    '',
    '  public enum CodingKeys: String, CodingKey {',
    ...codingKeys,
    '  }',
    '',
    '  public required init(from decoder: Decoder) throws {',
    '    let container = try decoder.container(keyedBy: FAPIJSONKey.self)',
    ...decl.properties.map(property => emitDecode(property, decl.name)),
    '  }',
    '',
    '  public func encode(to encoder: Encoder) throws {',
    '    var container = encoder.container(keyedBy: CodingKeys.self)',
    ...decl.properties.map(property => emitEncode(property, decl.name)),
    '  }',
    '}',
    '',
  ].join('\n');
}

function emitStruct(decl: SwiftStruct): string {
  if (decl.asClass) {
    return emitErrorClass(decl);
  }
  const conformances = ['Codable', 'Equatable'];
  if (MODEL_COMPATIBILITY[decl.name]?.hashable) {
    conformances.push('Hashable');
  }
  conformances.push('Sendable');
  if (decl.identifiable) {
    conformances.push('Identifiable');
  }
  const needsCustomCodable = decl.properties.some(property => property.isDate);
  const hasCustomEncode = decl.properties.some(
    property => PROPERTY_COMPATIBILITY[`${decl.name}.${property.wireName}`]?.encode,
  );
  const initParams = decl.properties.map(property => emitInitDefault(property, decl.name));
  const initBody = decl.properties.map(property => `    self.${property.name} = ${property.name}`);
  const codingKeys = decl.properties.map(property => {
    const caseName = property.name.replace(/`/g, '');
    return caseName === property.wireName
      ? `    case ${property.name}`
      : `    case ${property.name} = "${escapeSwiftString(property.wireName)}"`;
  });
  const lines = [
    GENERATED_HEADER,
    'import Foundation',
    '',
    `public struct ${decl.name}: ${conformances.join(', ')} {`,
    ...decl.properties.map(property => `  public var ${property.name}: ${emitRef(property.type)}`),
    '',
    '  public init(',
    initParams.join(',\n'),
    '  ) {',
    ...initBody,
    '  }',
    ...emitHash(decl),
    ...emitEquals(decl),
  ];
  if (decl.properties.length > 0) {
    lines.push('', '  public enum CodingKeys: String, CodingKey {', ...codingKeys, '  }');
  }
  if (decl.properties.length > 0) {
    lines.push(
      '',
      '  public init(from decoder: Decoder) throws {',
      '    let container = try decoder.container(keyedBy: FAPIJSONKey.self)',
      ...decl.properties.map(property => emitDecode(property, decl.name)),
      '  }',
    );
  }
  if (needsCustomCodable || hasCustomEncode || decl.properties.some(property => isOptionalRef(property.type))) {
    lines.push(
      '',
      '  public func encode(to encoder: Encoder) throws {',
      '    var container = encoder.container(keyedBy: CodingKeys.self)',
      ...decl.properties.map(property => emitEncode(property, decl.name)),
      '  }',
    );
  }
  lines.push('}', '');
  return lines.join('\n');
}

export function emitDecl(decl: SwiftDecl): string {
  return decl.kind === 'enum' ? emitEnum(decl) : emitStruct(decl);
}

function emitMethodNamesFile(facade: SwiftMethodFacade): string {
  const enumCases = facade.methods.map(
    method => `  case ${swiftIdent(method.jsName)} = "${escapeSwiftString(method.jsName)}"`,
  );
  const lines = [
    GENERATED_HEADER,
    'import Foundation',
    '',
    `public enum ${facade.owner}JSMethod: String, Sendable {`,
    ...enumCases,
    '}',
    '',
  ];
  return lines.join('\n');
}

function paramSwiftType(param: SwiftMethodParam): string {
  return emitRef(param.optional ? optionalize(param.type) : param.type);
}

function isParamsStructRef(ref: SwiftRef): boolean {
  const core = ref.kind === 'optional' ? ref.of : ref;
  return core.kind === 'named';
}

function emitJSCallAssociated(method: SwiftMethod): string {
  if (method.params.length === 0) {
    return '';
  }
  const unlabeledStruct = method.params.length === 1 && isParamsStructRef(method.params[0].type);
  const parts = method.params.map(param => {
    const typeName = paramSwiftType(param);
    return unlabeledStruct ? typeName : `${param.name}: ${typeName}`;
  });
  return `(${parts.join(', ')})`;
}

function emitJSCallArgBody(method: SwiftMethod): string {
  const ident = swiftIdent(method.jsName);
  if (method.params.length === 0) {
    return `    case .${ident}:\n      return []`;
  }
  const bindings = method.params.map(param => `let ${param.name}`).join(', ');
  const lines = [`    case .${ident}(${bindings}):`, '      var args: [JSONValue] = []'];
  for (const param of method.params) {
    if (param.optional) {
      lines.push(`      if let ${param.name} { args.append(try JSONValue(encoding: ${param.name})) }`);
    } else {
      lines.push(`      args.append(try JSONValue(encoding: ${param.name}))`);
    }
  }
  lines.push('      return args');
  return lines.join('\n');
}

function emitJSCallFile(facade: SwiftMethodFacade): string {
  const identCases = facade.methods.map(method => swiftIdent(method.jsName));
  const lines = [
    GENERATED_HEADER,
    'import Foundation',
    '',
    `public enum ${facade.owner}JSCall: ClerkJSCallable {`,
    ...facade.methods.map(method => `  case ${swiftIdent(method.jsName)}${emitJSCallAssociated(method)}`),
    '',
    '  public var jsMethod: String {',
    '    switch self {',
    ...identCases.map(ident => `    case .${ident}:\n      return ${facade.owner}JSMethod.${ident}.rawValue`),
    '    }',
    '  }',
    '',
    '  public func jsArguments() throws -> [JSONValue] {',
    '    switch self {',
    ...facade.methods.map(emitJSCallArgBody),
    '    }',
    '  }',
    '}',
    '',
  ];
  return lines.join('\n');
}

export function emitMethodFiles(facades: SwiftMethodFacade[], paramDecls: SwiftDecl[]): GeneratedSwiftFile[] {
  return [
    ...facades.map(facade => ({
      filename: `methods/${facade.owner}JSMethod.swift`,
      contents: emitMethodNamesFile(facade),
    })),
    ...facades.map(facade => ({
      filename: `methods/${facade.owner}JSCall.swift`,
      contents: emitJSCallFile(facade),
    })),
    ...paramDecls.map(decl => ({
      filename: `methods/${decl.name}.swift`,
      contents: emitDecl(decl),
    })),
  ];
}
