export const PROVIDERS = [
  { name: 'Apple', icon: 'Apple' },
  { name: 'Atlassian', icon: 'Atlassian' },
  { name: 'Bitbucket', icon: 'Bitbucket' },
  { name: 'Box', icon: 'Box' },
  { name: 'Coinbase', icon: 'Coinbase' },
  { name: 'Discord', icon: 'Discord' },
  { name: 'Dropbox', icon: 'Dropbox' },
  { name: 'Facebook', icon: 'Facebook' },
  { name: 'GitHub', icon: 'GitHub' },
  { name: 'GitLab', icon: 'GitLab' },
  { name: 'Google', icon: 'Google' },
  { name: 'HubSpot', icon: 'HubSpot' },
  { name: 'Instagram', icon: 'Instagram' },
  { name: 'Line', icon: 'Line' },
  { name: 'Linear', icon: 'Linear' },
  { name: 'LinkedIn', icon: 'LinkedInOIDC' },
  { name: 'MetaMask', icon: 'MetaMask' },
  { name: 'Microsoft', icon: 'Microsoft' },
  { name: 'Notion', icon: 'Notion' },
  { name: 'Slack', icon: 'Slack' },
  { name: 'TikTok', icon: 'TikTok' },
  { name: 'Twitch', icon: 'Twitch' },
  { name: 'Twitter', icon: 'Twitter' },
  { name: 'Xero', icon: 'Xero' },
] as const;
