export const PROVIDERS = [
  { id: 'apple', name: 'Apple', icon: 'Apple' },
  { id: 'atlassian', name: 'Atlassian', icon: 'Atlassian' },
  { id: 'bitbucket', name: 'Bitbucket', icon: 'Bitbucket' },
  { id: 'box', name: 'Box', icon: 'Box' },
  { id: 'coinbase', name: 'Coinbase', icon: 'Coinbase' },
  { id: 'discord', name: 'Discord', icon: 'Discord' },
  { id: 'dropbox', name: 'Dropbox', icon: 'Dropbox' },
  { id: 'facebook', name: 'Facebook', icon: 'Facebook' },
  { id: 'github', name: 'GitHub', icon: 'GitHub' },
  { id: 'gitlab', name: 'GitLab', icon: 'GitLab' },
  { id: 'google', name: 'Google', icon: 'Google' },
  { id: 'hubspot', name: 'HubSpot', icon: 'HubSpot' },
  { id: 'instagram', name: 'Instagram', icon: 'Instagram' },
  { id: 'line', name: 'Line', icon: 'Line' },
  { id: 'linear', name: 'Linear', icon: 'Linear' },
  { id: 'linkedin', name: 'LinkedIn', icon: 'LinkedInOIDC' },
  { id: 'metamask', name: 'MetaMask', icon: 'MetaMask' },
  { id: 'microsoft', name: 'Microsoft', icon: 'Microsoft' },
  { id: 'notion', name: 'Notion', icon: 'Notion' },
  { id: 'slack', name: 'Slack', icon: 'Slack' },
  { id: 'tiktok', name: 'TikTok', icon: 'TikTok' },
  { id: 'twitch', name: 'Twitch', icon: 'Twitch' },
  { id: 'twitter', name: 'Twitter', icon: 'Twitter' },
  { id: 'xero', name: 'Xero', icon: 'Xero' },
] as const;
