import type { OAuthProvider, Web3Provider } from '@clerk/types';

export const PROVIDER_ICON_MAP: Record<OAuthProvider | Web3Provider, string> = {
  facebook: 'Facebook',
  google: 'Google',
  hubspot: 'HubSpot',
  github: 'GitHub',
  tiktok: 'TikTok',
  gitlab: 'GitLab',
  discord: 'Discord',
  twitter: 'Twitter',
  twitch: 'Twitter',
  linkedin: 'LinkedIn',
  linkedin_oidc: 'LinkedIn',
  dropbox: 'Dropbox',
  atlassian: 'Atlassian',
  bitbucket: 'Bitbucket',
  microsoft: 'microsoft',
  notion: 'Notion',
  apple: 'Apple',
  line: 'Line',
  instagram: 'Instagram',
  coinbase: 'Coinbase',
  spotify: 'Spotify',
  xero: 'Xero',
  box: 'Box',
  slack: 'Slack',
  linear: 'Linear',
  x: 'Twitter',
  enstall: 'Enstall',
  metamask: 'MetaMask',
};
