import * as stylex from '@stylexjs/stylex';

import { colorVars, durationVars, fontFamilyVars, radiusVars, space, typeScaleVars } from '../../tokens.stylex';

export const styles = stylex.create({
  root: {
    padding: space['2'],
    borderRadius: radiusVars['--cl-radius-md'],
    gap: space['2'],
    alignContent: 'flex-start',
    alignItems: 'center',
    cursor: 'text',
    display: 'flex',
    flexWrap: 'wrap',
    fontFamily: fontFamilyVars['--cl-font-family-sans'],
    minHeight: space['20'],
    width: '100%',
  },
  disabled: {
    borderColor: colorVars['--cl-color-border'],
    backgroundColor: `color-mix(in oklab, ${colorVars['--cl-color-brand']} 5%, transparent)`,
    cursor: 'not-allowed',
  },
  list: {
    display: 'contents',
  },
  tag: {
    borderRadius: radiusVars['--cl-radius-sm'],
    paddingInline: space['1'],
    alignItems: 'center',
    backgroundColor: colorVars['--cl-color-neutral-alpha-100'],
    color: colorVars['--cl-color-foreground'],
    cursor: 'default',
    display: 'inline-flex',
    fontSize: {
      default: typeScaleVars['--cl-text-sm-size'],
      '@media (pointer: coarse)': `max(1rem, ${typeScaleVars['--cl-text-sm-size']})`,
    },
    lineHeight: typeScaleVars['--cl-text-sm-leading'],
    opacity: { default: 1, ':where([data-starting-style], [data-ending-style])': 0 },
    transform: {
      default: 'scale(1)',
      ':where([data-starting-style], [data-ending-style])': 'scale(0.9)',
      '@media (prefers-reduced-motion: reduce)': {
        default: 'scale(1)',
        ':where([data-starting-style], [data-ending-style])': 'scale(1)',
      },
    },
    transitionDuration: '150ms',
    transitionProperty: {
      default: 'opacity, transform',
      '@media (prefers-reduced-motion: reduce)': 'opacity',
    },
    transitionTimingFunction: { default: 'ease-out', ':where([data-ending-style])': 'ease-in' },
    height: space['6'],
    maxWidth: '100%',
    minWidth: 0,
  },
  tagInvalid: {
    backgroundColor: colorVars['--cl-color-negative-alpha-100'],
    color: colorVars['--cl-color-negative'],
  },
  tagLabel: {
    overflow: 'hidden',
    paddingInline: space['1'],
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tagRemove: {
    padding: 0,
    borderRadius: radiusVars['--cl-radius-sm'],
    borderStyle: 'none',
    borderWidth: 0,
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':enabled:active': colorVars['--cl-color-neutral-alpha-300'],
      '@media (hover: hover)': {
        default: null,
        ':enabled:hover:not(:active)': colorVars['--cl-color-neutral-alpha-200'],
      },
    },
    color: 'inherit',
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    display: 'inline-flex',
    flexShrink: 0,
    justifyContent: 'center',
    transitionDuration: durationVars['--cl-duration-base'],
    transitionProperty: 'background-color',
    transitionTimingFunction: 'linear',
    height: space['4'],
    width: space['4'],
  },
  input: {
    borderStyle: 'none',
    borderWidth: 0,
    outline: 'none',
    paddingBlock: 0,
    paddingInline: space['1'],
    backgroundColor: 'transparent',
    color: colorVars['--cl-color-foreground'],
    cursor: { default: null, ':disabled': 'not-allowed' },
    flexBasis: '8ch',
    flexGrow: 1,
    fontFamily: 'inherit',
    fontSize: {
      default: typeScaleVars['--cl-text-sm-size'],
      '@media (pointer: coarse)': `max(1rem, ${typeScaleVars['--cl-text-sm-size']})`,
    },
    lineHeight: typeScaleVars['--cl-text-sm-leading'],
    height: space['6'],
    minWidth: 0,
    '::placeholder': {
      color: colorVars['--cl-color-input-placeholder'],
    },
  },
});
