/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { remap as remap$ } from '../../lib/primitives.js';
import { safeParse } from '../../lib/schemas.js';
import { ClosedEnum } from '../../types/enums.js';
import { Result as SafeParseResult } from '../../types/fp.js';
import { SDKValidationError } from '../errors/sdkvalidationerror.js';

export const JWKSSymmetricKeyKty = {
  Oct: 'oct',
} as const;
export type JWKSSymmetricKeyKty = ClosedEnum<typeof JWKSSymmetricKeyKty>;

export type JWKSSymmetricKey = {
  kid: string;
  alg: string;
  use: string;
  kty: JWKSSymmetricKeyKty;
  k: string;
  x5c?: Array<string> | undefined;
  x5t?: string | undefined;
  x5tNumberS256?: string | undefined;
  x5u?: string | undefined;
};

/** @internal */
export const JWKSSymmetricKeyKty$inboundSchema: z.ZodNativeEnum<typeof JWKSSymmetricKeyKty> =
  z.nativeEnum(JWKSSymmetricKeyKty);

/** @internal */
export const JWKSSymmetricKeyKty$outboundSchema: z.ZodNativeEnum<typeof JWKSSymmetricKeyKty> =
  JWKSSymmetricKeyKty$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JWKSSymmetricKeyKty$ {
  /** @deprecated use `JWKSSymmetricKeyKty$inboundSchema` instead. */
  export const inboundSchema = JWKSSymmetricKeyKty$inboundSchema;
  /** @deprecated use `JWKSSymmetricKeyKty$outboundSchema` instead. */
  export const outboundSchema = JWKSSymmetricKeyKty$outboundSchema;
}

/** @internal */
export const JWKSSymmetricKey$inboundSchema: z.ZodType<JWKSSymmetricKey, z.ZodTypeDef, unknown> = z
  .object({
    kid: z.string(),
    alg: z.string(),
    use: z.string(),
    kty: JWKSSymmetricKeyKty$inboundSchema,
    k: z.string(),
    x5c: z.array(z.string()).optional(),
    x5t: z.string().optional(),
    'x5t#S256': z.string().optional(),
    x5u: z.string().optional(),
  })
  .transform(v => {
    return remap$(v, {
      'x5t#S256': 'x5tNumberS256',
    });
  });

/** @internal */
export type JWKSSymmetricKey$Outbound = {
  kid: string;
  alg: string;
  use: string;
  kty: string;
  k: string;
  x5c?: Array<string> | undefined;
  x5t?: string | undefined;
  'x5t#S256'?: string | undefined;
  x5u?: string | undefined;
};

/** @internal */
export const JWKSSymmetricKey$outboundSchema: z.ZodType<JWKSSymmetricKey$Outbound, z.ZodTypeDef, JWKSSymmetricKey> = z
  .object({
    kid: z.string(),
    alg: z.string(),
    use: z.string(),
    kty: JWKSSymmetricKeyKty$outboundSchema,
    k: z.string(),
    x5c: z.array(z.string()).optional(),
    x5t: z.string().optional(),
    x5tNumberS256: z.string().optional(),
    x5u: z.string().optional(),
  })
  .transform(v => {
    return remap$(v, {
      x5tNumberS256: 'x5t#S256',
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JWKSSymmetricKey$ {
  /** @deprecated use `JWKSSymmetricKey$inboundSchema` instead. */
  export const inboundSchema = JWKSSymmetricKey$inboundSchema;
  /** @deprecated use `JWKSSymmetricKey$outboundSchema` instead. */
  export const outboundSchema = JWKSSymmetricKey$outboundSchema;
  /** @deprecated use `JWKSSymmetricKey$Outbound` instead. */
  export type Outbound = JWKSSymmetricKey$Outbound;
}

export function jwksSymmetricKeyToJSON(jwksSymmetricKey: JWKSSymmetricKey): string {
  return JSON.stringify(JWKSSymmetricKey$outboundSchema.parse(jwksSymmetricKey));
}

export function jwksSymmetricKeyFromJSON(jsonString: string): SafeParseResult<JWKSSymmetricKey, SDKValidationError> {
  return safeParse(
    jsonString,
    x => JWKSSymmetricKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JWKSSymmetricKey' from JSON`,
  );
}
