/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { remap as remap$ } from '../../lib/primitives.js';
import { safeParse } from '../../lib/schemas.js';
import { Result as SafeParseResult } from '../../types/fp.js';
import { SDKValidationError } from '../errors/sdkvalidationerror.js';
import {
  OrganizationDomain,
  OrganizationDomain$inboundSchema,
  OrganizationDomain$Outbound,
  OrganizationDomain$outboundSchema,
} from './organizationdomain.js';

/**
 * A list of organization domains
 */
export type OrganizationDomains = {
  data: Array<OrganizationDomain>;
  /**
   * Total number of organization domains
   *
   * @remarks
   */
  totalCount: number;
};

/** @internal */
export const OrganizationDomains$inboundSchema: z.ZodType<OrganizationDomains, z.ZodTypeDef, unknown> = z
  .object({
    data: z.array(OrganizationDomain$inboundSchema),
    total_count: z.number().int(),
  })
  .transform(v => {
    return remap$(v, {
      total_count: 'totalCount',
    });
  });

/** @internal */
export type OrganizationDomains$Outbound = {
  data: Array<OrganizationDomain$Outbound>;
  total_count: number;
};

/** @internal */
export const OrganizationDomains$outboundSchema: z.ZodType<
  OrganizationDomains$Outbound,
  z.ZodTypeDef,
  OrganizationDomains
> = z
  .object({
    data: z.array(OrganizationDomain$outboundSchema),
    totalCount: z.number().int(),
  })
  .transform(v => {
    return remap$(v, {
      totalCount: 'total_count',
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationDomains$ {
  /** @deprecated use `OrganizationDomains$inboundSchema` instead. */
  export const inboundSchema = OrganizationDomains$inboundSchema;
  /** @deprecated use `OrganizationDomains$outboundSchema` instead. */
  export const outboundSchema = OrganizationDomains$outboundSchema;
  /** @deprecated use `OrganizationDomains$Outbound` instead. */
  export type Outbound = OrganizationDomains$Outbound;
}

export function organizationDomainsToJSON(organizationDomains: OrganizationDomains): string {
  return JSON.stringify(OrganizationDomains$outboundSchema.parse(organizationDomains));
}

export function organizationDomainsFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDomains, SDKValidationError> {
  return safeParse(
    jsonString,
    x => OrganizationDomains$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDomains' from JSON`,
  );
}
