/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsDelete } from '../../funcs/domainsDelete.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteDomainRequest$inboundSchema,
};

export const tool$domainsDelete: ToolDefinition<typeof args> = {
  name: 'domains-delete',
  description: `Delete a satellite domain

Deletes a satellite domain for the instance.
It is currently not possible to delete the instance's primary domain.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainsDelete(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
