/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailSMSTemplatesGet } from '../../funcs/emailSMSTemplatesGet.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.GetTemplateRequest$inboundSchema,
};

export const tool$emailSMSTemplatesGet: ToolDefinition<typeof args> = {
  name: 'email-SMS-templates-get',
  description: `Retrieve a template

Returns the details of a template`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emailSMSTemplatesGet(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
