/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailSMSTemplatesToggleTemplateDelivery } from '../../funcs/emailSMSTemplatesToggleTemplateDelivery.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.ToggleTemplateDeliveryRequest$inboundSchema,
};

export const tool$emailSMSTemplatesToggleTemplateDelivery: ToolDefinition<typeof args> = {
  name: 'email-SMS-templates-toggle-template-delivery',
  description: `Toggle the delivery by Clerk for a template of a given type and slug

Toggles the delivery by Clerk for a template of a given type and slug.
If disabled, Clerk will not deliver the resulting email or SMS.
The app developer will need to listen to the \`email.created\` or \`sms.created\` webhooks in order to handle delivery themselves.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emailSMSTemplatesToggleTemplateDelivery(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
