/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailAddressesDelete } from '../../funcs/emailAddressesDelete.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteEmailAddressRequest$inboundSchema,
};

export const tool$emailAddressesDelete: ToolDefinition<typeof args> = {
  name: 'email-addresses-delete',
  description: `Delete an email address

Delete the email address with the given ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emailAddressesDelete(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
