/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { instanceSettingsGet } from '../../funcs/instanceSettingsGet.js';
import { formatResult, ToolDefinition } from '../tools.js';

export const tool$instanceSettingsGet: ToolDefinition = {
  name: 'instance-settings-get',
  description: `Fetch the current instance

Fetches the current instance`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await instanceSettingsGet(client, { fetchOptions: { signal: ctx.signal } }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
