/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { instanceSettingsUpdateRestrictions } from '../../funcs/instanceSettingsUpdateRestrictions.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.UpdateInstanceRestrictionsRequestBody$inboundSchema.optional(),
};

export const tool$instanceSettingsUpdateRestrictions: ToolDefinition<typeof args> = {
  name: 'instance-settings-update-restrictions',
  description: `Update instance restrictions

Updates the restriction settings of an instance`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await instanceSettingsUpdateRestrictions(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
