/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jwtTemplatesUpdate } from '../../funcs/jwtTemplatesUpdate.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.UpdateJWTTemplateRequest$inboundSchema,
};

export const tool$jwtTemplatesUpdate: ToolDefinition<typeof args> = {
  name: 'jwt-templates-update',
  description: `Update a JWT template

Updates an existing JWT template`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await jwtTemplatesUpdate(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
