/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthApplicationsDelete } from '../../funcs/oauthApplicationsDelete.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteOAuthApplicationRequest$inboundSchema,
};

export const tool$oauthApplicationsDelete: ToolDefinition<typeof args> = {
  name: 'oauth-applications-delete',
  description: `Delete an OAuth application

Deletes the given OAuth application.
This is not reversible.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await oauthApplicationsDelete(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
