/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationDomainsDelete } from '../../funcs/organizationDomainsDelete.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteOrganizationDomainRequest$inboundSchema,
};

export const tool$organizationDomainsDelete: ToolDefinition<typeof args> = {
  name: 'organization-domains-delete',
  description: `Remove a domain from an organization.

Removes the given domain from the organization.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationDomainsDelete(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
