/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsDelete } from '../../funcs/organizationsDelete.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteOrganizationRequest$inboundSchema,
};

export const tool$organizationsDelete: ToolDefinition<typeof args> = {
  name: 'organizations-delete',
  description: `Delete an organization

Deletes the given organization.
Please note that deleting an organization will also delete all memberships and invitations.
This is not reversible.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationsDelete(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
