/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationMembershipsCreate } from '../../funcs/organizationMembershipsCreate.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.CreateOrganizationMembershipRequest$inboundSchema,
};

export const tool$organizationMembershipsCreate: ToolDefinition<typeof args> = {
  name: 'organization-memberships-create',
  description: `Create a new organization membership

Adds a user as a member to the given organization.
Only users in the same instance as the organization can be added as members.

This organization will be the user's [active organization] (https://clerk.com/docs/organizations/overview#active-organization)
the next time they create a session, presuming they don't explicitly set a
different organization as active before then.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationMembershipsCreate(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
