/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { samlConnectionsCreate } from '../../funcs/samlConnectionsCreate.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.CreateSAMLConnectionRequestBody$inboundSchema.optional(),
};

export const tool$samlConnectionsCreate: ToolDefinition<typeof args> = {
  name: 'saml-connections-create',
  description: `Create a SAML Connection

Create a new SAML Connection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await samlConnectionsCreate(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
