/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { samlConnectionsGet } from '../../funcs/samlConnectionsGet.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.GetSAMLConnectionRequest$inboundSchema,
};

export const tool$samlConnectionsGet: ToolDefinition<typeof args> = {
  name: 'saml-connections-get',
  description: `Retrieve a SAML Connection by ID

Fetches the SAML Connection whose ID matches the provided \`saml_connection_id\` in the path.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await samlConnectionsGet(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
