/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsRefresh } from '../../funcs/sessionsRefresh.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.RefreshSessionRequest$inboundSchema,
};

export const tool$sessionsRefresh: ToolDefinition<typeof args> = {
  name: 'sessions-refresh',
  description: `Refresh a session

Refreshes a session by creating a new session token. A 401 is returned when there
are validation errors, which signals the SDKs to fallback to the handshake flow.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sessionsRefresh(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
