/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testingTokensCreate } from '../../funcs/testingTokensCreate.js';
import { formatResult, ToolDefinition } from '../tools.js';

export const tool$testingTokensCreate: ToolDefinition = {
  name: 'testing-tokens-create',
  description: `Retrieve a new testing token

Retrieve a new testing token.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await testingTokensCreate(client, { fetchOptions: { signal: ctx.signal } }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
