/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetInstanceOrganizationMemberships } from '../../funcs/usersGetInstanceOrganizationMemberships.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.InstanceGetOrganizationMembershipsRequest$inboundSchema,
};

export const tool$usersGetInstanceOrganizationMemberships: ToolDefinition<typeof args> = {
  name: 'users-get-instance-organization-memberships',
  description: `Get a list of all organization memberships within an instance.

Retrieves all organization user memberships for the given instance.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersGetInstanceOrganizationMemberships(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
