/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersDeleteExternalAccount } from '../../funcs/usersDeleteExternalAccount.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.DeleteExternalAccountRequest$inboundSchema,
};

export const tool$usersDeleteExternalAccount: ToolDefinition<typeof args> = {
  name: 'users-delete-external-account',
  description: `Delete External Account

Delete an external account by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersDeleteExternalAccount(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
