/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGet } from '../../funcs/usersGet.js';
import * as operations from '../../models/operations/index.js';
import { formatResult, ToolDefinition } from '../tools.js';

const args = {
  request: operations.GetUserRequest$inboundSchema,
};

export const tool$usersGet: ToolDefinition<typeof args> = {
  name: 'users-get',
  description: `Retrieve a user

Retrieve the details of a user`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
