/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksDeleteSvixApp } from '../../funcs/webhooksDeleteSvixApp.js';
import { formatResult, ToolDefinition } from '../tools.js';

export const tool$webhooksDeleteSvixApp: ToolDefinition = {
  name: 'webhooks-delete-svix-app',
  description: `Delete a Svix app

Delete a Svix app and disassociate it from the current instance`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await webhooksDeleteSvixApp(client, { fetchOptions: { signal: ctx.signal } }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: 'text', text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
