import type { LocalizationResource } from '@clerk/types';

const commonTexts = {
  signIn: {
    phoneCode: {
      title: 'Проверете вашия телефон',
      subtitle: 'за да продължите към {{applicationName}}',
      inputLabel: 'Код за потвърждение',
      resendButton: 'Не сте получили код? Изпрати отново',
      formTitle: 'Код за потвърждение',
      formSubtitle: 'Въведете кода за потвърждение, изпратен на вашия телефонен номер',
    },
  },
} as const;

export const bgBG: LocalizationResource = {
  locale: 'bg-BG',
  socialButtonsBlockButton: 'Продължи с {{provider|titleize}}',
  dividerText: 'или',
  formFieldLabel__emailAddress: 'Имейл адрес',
  formFieldLabel__emailAddresses: 'Имейл адреси',
  formFieldLabel__phoneNumber: 'Телефонен номер',
  formFieldLabel__username: 'Потребителско име',
  formFieldLabel__emailAddress_username: 'Имейл адрес или потребителско име',
  formFieldLabel__password: 'Парола',
  formFieldLabel__currentPassword: 'Текуща парола',
  formFieldLabel__newPassword: 'Нова парола',
  formFieldLabel__confirmPassword: 'Потвърдете паролата',
  formFieldLabel__signOutOfOtherSessions: 'Изход от всички други устройства',
  formFieldLabel__automaticInvitations: 'Включи автоматични покани за този домейн',
  formFieldLabel__firstName: 'Име',
  formFieldLabel__lastName: 'Фамилия',
  formFieldLabel__backupCode: 'Резервен код',
  formFieldLabel__organizationName: 'Име',
  formFieldLabel__organizationSlug: 'Slug',
  formFieldLabel__organizationDomain: 'Домейн',
  formFieldLabel__organizationDomainEmailAddress: 'Имейл адрес за потвърждение',
  formFieldLabel__organizationDomainEmailAddressDescription:
    'Въведете имейл адрес под този домейн, за да получите код и да потвърдите домейна.',
  formFieldLabel__organizationDomainDeletePending: 'Изтриване на изчакващи покани и предложения',
  formFieldLabel__confirmDeletion: 'Потвърждение',
  formFieldLabel__role: 'Роля',
  formFieldInputPlaceholder__emailAddress: '',
  formFieldInputPlaceholder__emailAddresses: 'example@email.com, example2@email.com',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: '',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: '',
  formFieldInputPlaceholder__lastName: '',
  formFieldInputPlaceholder__backupCode: '',
  formFieldInputPlaceholder__organizationName: '',
  formFieldInputPlaceholder__organizationSlug: '',
  formFieldInputPlaceholder__organizationDomain: '',
  formFieldInputPlaceholder__organizationDomainEmailAddress: '',
  formFieldInputPlaceholder__confirmDeletionUserAccount: 'Изтрий акаунта',
  formFieldError__notMatchingPasswords: 'Паролите не съвпадат.',
  formFieldError__matchingPasswords: 'Паролите съвпадат.',
  formFieldError__verificationLinkExpired: 'Линкът за потвърждение е изтекъл. Моля, заявете нов линк.',
  formFieldAction__forgotPassword: 'Забравена парола?',
  formFieldHintText__optional: 'По избор',
  formFieldHintText__slug: 'Slug е четим идентификатор, който трябва да бъде уникален. Често се използва в URL адреси.',
  formButtonPrimary: 'Продължи',
  formButtonPrimary__verify: 'Потвърди',
  signInEnterPasswordTitle: 'Въведете вашата парола',
  backButton: 'Назад',
  footerActionLink__useAnotherMethod: 'Използвайте друг метод',
  badge__primary: 'Основен',
  badge__thisDevice: 'Това устройство',
  badge__userDevice: 'Потребителско устройство',
  badge__otherImpersonatorDevice: 'Друго устройство за имитация',
  badge__default: 'По подразбиране',
  badge__unverified: 'Непотвърден',
  badge__requiresAction: 'Изисква действие',
  badge__you: 'Вие',
  footerPageLink__help: 'Помощ',
  footerPageLink__privacy: 'Поверителност',
  footerPageLink__terms: 'Условия',
  paginationButton__previous: 'Предишен',
  paginationButton__next: 'Следващ',
  paginationRowText__displaying: 'Показване на',
  paginationRowText__of: 'от',
  membershipRole__admin: 'Админ',
  membershipRole__basicMember: 'Член',
  membershipRole__guestMember: 'Гост',
  signUp: {
    start: {
      title: 'Създайте своя акаунт',
      subtitle: 'Добре дошли! Моля, попълнете данните, за да започнете.',
      actionText: 'Вече имате акаунт?',
      actionLink: 'Влезте',
    },
    emailLink: {
      title: 'Потвърдете вашия имейл',
      subtitle: 'за да продължите към {{applicationName}}',
      formTitle: 'Линк за потвърждение',
      formSubtitle: 'Използвайте линка за потвърждение, изпратен на вашия имейл адрес',
      resendButton: 'Не сте получили линк? Изпрати отново',
      verified: {
        title: 'Успешно регистриран',
      },
      loading: {
        title: 'Регистриране...',
      },
      verifiedSwitchTab: {
        title: 'Успешно потвърден имейл',
        subtitle: 'Върнете се към новоотворения таб, за да продължите',
        subtitleNewTab: 'Върнете се към предходния таб, за да продължите',
      },
    },
    emailCode: {
      title: 'Потвърдете вашия имейл',
      subtitle: 'Въведете кода за потвърждение, изпратен на вашия имейл',
      formTitle: 'Код за потвърждение',
      formSubtitle: 'Въведете кода за потвърждение, изпратен на вашия имейл адрес',
      resendButton: 'Не сте получили код? Изпрати отново',
    },
    phoneCode: {
      title: 'Потвърдете вашия телефон',
      subtitle: 'Въведете кода за потвърждение, изпратен на вашия телефон',
      formTitle: 'Код за потвърждение',
      formSubtitle: 'Въведете кода за потвърждение, изпратен на вашия телефонен номер',
      resendButton: 'Не сте получили код? Изпрати отново',
    },
    continue: {
      title: 'Попълнете липсващите полета',
      subtitle: 'Моля, попълнете останалите данни, за да продължите.',
      actionText: 'Вече имате акаунт?',
      actionLink: 'Влезте',
    },
  },
  signIn: {
    start: {
      title: 'Влезте в {{applicationName}}',
      subtitle: 'Добре дошли обратно! Моля, влезте, за да продължите',
      actionText: 'Нямате акаунт?',
      actionLink: 'Регистрирайте се',
      actionLink__use_email: 'Използвайте имейл',
      actionLink__use_phone: 'Използвайте телефон',
      actionLink__use_username: 'Използвайте потребителско име',
      actionLink__use_email_username: 'Използвайте имейл или потребителско име',
    },
    password: {
      title: 'Въведете вашата парола',
      subtitle: 'Въведете паролата, свързана с вашия акаунт',
      actionLink: 'Използвайте друг метод',
    },
    forgotPasswordAlternativeMethods: {
      title: 'Забравена парола?',
      label__alternativeMethods: 'Или, влезте с друг метод',
      blockButton__resetPassword: 'Нулирайте вашата парола',
    },
    forgotPassword: {
      title: 'Нулиране на парола',
      subtitle_email: 'Първо, въведете кода, изпратен на вашия имейл',
      subtitle_phone: 'Първо, въведете кода, изпратен на вашия телефон',
      resendButton: 'Не сте получили код? Изпрати отново',
      subtitle: 'за да нулирате паролата си',
      formTitle: 'Код за нулиране на парола',
    },
    resetPassword: {
      title: 'Задайте нова парола',
      formButtonPrimary: 'Нулирай паролата',
      successMessage: 'Паролата ви беше успешно променена. Влизане, моля изчакайте момент.',
      requiredMessage: 'Вече съществува акаунт с непотвърден имейл адрес. Моля, нулирайте паролата си за сигурност.',
    },
    resetPasswordMfa: {
      detailsLabel: 'Трябва да потвърдим вашата самоличност, преди да нулираме паролата ви.',
    },
    emailCode: {
      title: 'Проверете вашия имейл',
      subtitle: 'за да продължите към {{applicationName}}',
      formTitle: 'Код за потвърждение',
      resendButton: 'Не сте получили код? Изпрати отново',
    },
    emailLink: {
      title: 'Проверете вашия имейл',
      subtitle: 'за да продължите към {{applicationName}}',
      formTitle: 'Линк за потвърждение',
      formSubtitle: 'Използвайте линкът за потвърждение, изпратен на вашия имейл адрес',
      resendButton: 'Не сте получили линк? Изпрати отново',
      unusedTab: {
        title: 'Можете да затворите този таб',
      },
      verified: {
        title: 'Успешно влезли',
        subtitle: 'Ще бъдете пренасочени скоро',
      },
      verifiedSwitchTab: {
        subtitle: 'Върнете се в оригиналния таб, за да продължите',
        titleNewTab: 'Влезнали сте в друг таб',
        subtitleNewTab: 'Върнете се в новоотворения таб, за да продължите',
      },
      loading: {
        title: 'Влизане...',
        subtitle: 'Ще бъдете пренасочени скоро',
      },
      failed: {
        title: 'Този линк за потвърждение е невалиден',
        subtitle: 'Върнете се в оригиналния таб, за да продължите.',
      },
      expired: {
        title: 'Този линк за потвърждение е изтекъл',
        subtitle: 'Върнете се в оригиналния таб, за да продължите.',
      },
    },
    phoneCode: { ...commonTexts.signIn.phoneCode },
    phoneCodeMfa: {
      ...commonTexts.signIn.phoneCode,
      subtitle: 'За да продължите, моля въведете кода за потвърждение, изпратен на вашия телефон',
    },
    totpMfa: {
      title: 'Двустепенна верификация',
      subtitle:
        'За да продължите, моля въведете кода за потвърждение, генериран от вашето приложение за удостоверяване',
      formTitle: 'Код за потвърждение',
    },
    backupCodeMfa: {
      title: 'Въведете резервен код',
      subtitle: 'Вашият резервен код е този, който сте получили при настройване на двустепенната аутентикация.',
    },
    alternativeMethods: {
      title: 'Използвайте друг метод',
      subtitle: 'Имате проблеми? Можете да използвате някой от тези методи за влизане.',
      actionLink: 'Получете помощ',
      actionText: 'Нямате нито един от тях?',
      blockButton__emailLink: 'Изпрати линк по имейл до {{identifier}}',
      blockButton__emailCode: 'Изпрати код по имейл до {{identifier}}',
      blockButton__phoneCode: 'Изпрати SMS код до {{identifier}}',
      blockButton__password: 'Влез с парола',
      blockButton__totp: 'Използвай приложение за удостоверяване',
      blockButton__backupCode: 'Използвай резервен код',
      getHelp: {
        title: 'Получи помощ',
        content: `Ако имате затруднения при влизане в профила си, изпратете ни имейл и ще работим с вас, за да възстановим достъпа възможно най-скоро.`,
        blockButton__emailSupport: 'Имейл поддръжка',
      },
    },
    noAvailableMethods: {
      title: 'Неуспешно влизане',
      subtitle: 'Възникна грешка',
      message: 'Не може да се продължи с влизането. Няма наличен метод за удостоверяване.',
    },
  },
  userProfile: {
    mobileButton__menu: 'Меню',
    formButtonPrimary__continue: 'Продължи',
    formButtonPrimary__finish: 'Завърши',
    formButtonReset: 'Откажи',
    navbar: {
      title: 'Профил',
      description: 'Управлявайте информацията в профила си.',
    },
    start: {
      profileSection: {
        title: 'Профил',
        primaryButton: 'Редактирайте профила',
      },
      headerTitle__account: 'Профил',
      headerTitle__security: 'Сигурност',
      usernameSection: {
        title: 'Потребителско име',
        primaryButton__changeUsername: 'Промени потребителското име',
        primaryButton__setUsername: 'Задай потребителско име',
      },
      emailAddressesSection: {
        title: 'Имейл адреси',
        primaryButton: 'Добави имейл адрес',
        detailsAction__primary: 'Завърши потвърждение',
        detailsAction__nonPrimary: 'Задайте като основен',
        detailsAction__unverified: 'Потвърдете',
        destructiveAction: 'Премахни имейл',
      },
      phoneNumbersSection: {
        title: 'Телефонни номера',
        primaryButton: 'Добави телефонен номер',
        detailsAction__primary: 'Завърши потвърждение',
        detailsAction__nonPrimary: 'Задайте като основен',
        detailsAction__unverified: 'Потвърдете телефонния номер',
        destructiveAction: 'Премахни телефонен номер',
      },
      connectedAccountsSection: {
        title: 'Свързани акаунти',
        primaryButton: 'Свържи акаунт',
        actionLabel__connectionFailed: 'Опитайте отново',
        actionLabel__reauthorize: 'Авторизирайте сега',
        destructiveActionTitle: 'Премахни',
      },
      enterpriseAccountsSection: {
        title: 'Корпоративни акаунти',
      },
      passwordSection: {
        title: 'Парола',
        primaryButton__changePassword: 'Промени паролата',
        primaryButton__setPassword: 'Задай парола',
      },
      mfaSection: {
        title: 'Двустепенна верификация',
        primaryButton: 'Добави двустепенна верификация',
        phoneCode: {
          destructiveActionLabel: 'Премахни',
          actionLabel__setDefault: 'Задай като стандартен',
        },
        backupCodes: {
          headerTitle: 'Резервни кодове',
          title__regenerate: 'Прегенерирай резервни кодове',
          subtitle__regenerate:
            'Вземете нов набор от сигурни резервни кодове. Предходните резервни кодове ще бъдат изтрити и не могат да бъдат използвани.',
          actionLabel__regenerate: 'Прегенерирай',
        },
        totp: {
          headerTitle: 'Приложение за удостоверяване',
          destructiveActionTitle: 'Премахни',
        },
      },
      activeDevicesSection: {
        title: 'Активни устройства',
        destructiveAction: 'Излез от устройството',
      },
      web3WalletsSection: {
        title: 'Web3 портфейли',
        primaryButton: 'Web3 портфейли',
        destructiveAction: 'Премахни портфейл',
      },
      dangerSection: {
        title: 'Прекратяване на профила',
        deleteAccountButton: 'Изтрий профила',
      },
    },
    profilePage: {
      title: 'Актуализиране на профила',
      imageFormTitle: 'Профилна снимка',
      imageFormSubtitle: 'Качи',
      imageFormDestructiveActionSubtitle: 'Премахни',
      fileDropAreaHint: 'Препоръчителен размер 1:1, до 10MB.',
      readonly: 'Информацията ви за профила е предоставена от корпоративната връзка и не може да бъде редактирана.',
      successMessage: 'Вашият профил е актуализиран.',
    },
    usernamePage: {
      title: 'Актуализиране на потребителското име',
      successMessage: 'Вашето потребителско име е актуализирано.',
    },
    emailAddressPage: {
      title: 'Добави имейл адрес',
      emailCode: {
        formHint: 'На този имейл адрес ще бъде изпратен имейл с код за потвърждение.',
        formTitle: 'Код за потвърждение',
        formSubtitle: 'Въведете кода за потвърждение, изпратен на {{identifier}}',
        resendButton: 'Не сте получили код? Изпрати отново',
        successMessage: 'Имейлът {{identifier}} беше добавен към вашия профил.',
      },
      emailLink: {
        formHint: 'На този имейл адрес ще бъде изпратен имейл с линк за потвърждение.',
        formTitle: 'Линк за потвърждение',
        formSubtitle: 'Кликнете върху линка за потвърждение в имейла, изпратен на {{identifier}}',
        resendButton: 'Не сте получили линк? Изпрати отново',
        successMessage: 'Имейлът {{identifier}} беше добавен към вашия профил.',
      },
      removeResource: {
        title: 'Премахни имейл адрес',
        messageLine1: '{{identifier}} ще бъде премахнат от този профил.',
        messageLine2: 'Няма да можете да влезете в профила си, използвайки този имейл адрес.',
        successMessage: '{{emailAddress}} беше премахнат от вашия профил.',
      },
    },
    phoneNumberPage: {
      title: 'Добави телефонен номер',
      successMessage: '{{identifier}} беше добавен към вашия профил.',
      infoText: 'Съобщение, съдържащо линк за потвърждение, ще бъде изпратено на този телефонен номер.',
      infoText__secondary: 'Могат да се прилагат такси за съобщения и данни.',
      removeResource: {
        title: 'Премахни телефонен номер',
        messageLine1: '{{identifier}} ще бъде премахнат от този профил.',
        messageLine2: 'Няма да можете да влезете в профила си, използвайки този телефонен номер.',
        successMessage: '{{phoneNumber}} беше премахнат от вашия профил.',
      },
    },
    connectedAccountPage: {
      title: 'Добави свързан акаунт',
      formHint: 'Изберете доставчик, за да свържете вашия профил.',
      formHint__noAccounts: 'Няма налични външни акаунт доставчици.',
      socialButtonsBlockButton: 'Свържи акаунт {{provider|titleize}}',
      successMessage: 'Доставчикът беше добавен към вашия профил',
      removeResource: {
        title: 'Премахни свързан акаунт',
        messageLine1: '{{identifier}} ще бъде премахнат от този профил.',
        messageLine2:
          'Няма да можете да използвате този свързан акаунт, и всякакви зависими функции няма да работят повече.',
        successMessage: '{{connectedAccount}} беше премахнат от вашия профил.',
      },
    },
    web3WalletPage: {
      title: 'Добави web3 портфейл',
      subtitle__availableWallets: 'Изберете web3 портфейл, за да го свържете с вашия профил.',
      subtitle__unavailableWallets: 'Няма налични web3 портфейли.',
      successMessage: 'Портфейлът беше добавен към вашия профил.',
      removeResource: {
        title: 'Премахни web3 портфейл',
        messageLine1: '{{identifier}} ще бъде премахнат от този профил.',
        messageLine2: 'Няма да можете да влезете в профила си, използвайки този web3 портфейл.',
        successMessage: '{{web3Wallet}} беше премахнат от вашия профил.',
      },
    },
    passwordPage: {
      title: 'Задай парола',
      changePasswordTitle: 'Промени паролата',
      readonly:
        'Вашата парола в момента не може да бъде редактирана, тъй като можете да влизате само чрез корпоративна връзка.',
      successMessage: 'Паролата ви беше зададена.',
      changePasswordSuccessMessage: 'Паролата ви беше обновена.',
      sessionsSignedOutSuccessMessage: 'Всички други устройства бяха излезли.',
    },
    mfaPage: {
      title: 'Добави двустепенна верификация',
      formHint: 'Изберете метод, който да добавите.',
    },
    mfaTOTPPage: {
      title: 'Добавяне на приложение за удостоверяване',
      verifyTitle: 'Код за потвърждение',
      verifySubtitle: 'Въведете код за потвърждение, генериран от вашето удостоверително приложение',
      successMessage:
        'Двустепенното удостоверяване е активирано. При влизане, ще трябва да въведете код за потвърждение от това удостоверително приложение като допълнителна стъпка.',
      authenticatorApp: {
        infoText__ableToScan:
          'Настройте нов метод за влизане във вашия удостоверителен апликатор и сканирайте следващия QR код, за да го свържете с вашия акаунт.',
        infoText__unableToScan:
          'Настройте нов метод за влизане във вашия удостоверител и въведете предоставения по-долу ключ.',
        inputLabel__unableToScan1:
          'Уверете се, че времевите или еднократните пароли са активирани, след което завършете свързването на вашия акаунт.',
        inputLabel__unableToScan2:
          'Алтернативно, ако вашият удостоверител поддържа TOTP URI, можете също да копирате пълния URI.',
        buttonAbleToScan__nonPrimary: 'Сканирай QR кода вместо това',
        buttonUnableToScan__nonPrimary: 'Не може да се сканира QR кода?',
      },
      removeResource: {
        title: 'Премахване на двустепенното удостоверяване',
        messageLine1: 'Кодовете за потвърждение от този удостоверител вече няма да са необходими при влизане.',
        messageLine2: 'Вашият акаунт може да не е толкова сигурен. Сигурни ли сте, че искате да продължите?',
        successMessage: 'Двустепенното удостоверяване чрез приложение за удостоверяване беше премахнато.',
      },
    },
    mfaPhoneCodePage: {
      title: 'Добавяне на SMS код за потвърждение',
      primaryButton__addPhoneNumber: 'Добави телефонен номер',
      subtitle__availablePhoneNumbers:
        'Изберете телефонен номер, за да се регистрирате за двустепенното удостоверяване с SMS код.',
      subtitle__unavailablePhoneNumbers:
        'Няма налични телефонни номера за регистрация за двустепенното удостоверяване с SMS код.',
      successMessage:
        'Двустепенното удостоверяване с SMS код вече е активирано за този телефонен номер. При влизане, ще трябва да въведете код за потвърждение, изпратен на този телефонен номер като допълнителна стъпка.',
      removeResource: {
        title: 'Премахване на двустепенното удостоверяване',
        messageLine1: '{{identifier}} няма да получава повече кодове за потвърждение при влизане.',
        messageLine2: 'Вашият акаунт може да не е толкова сигурен. Сигурни ли сте, че искате да продължите?',
        successMessage: 'Двустепенното удостоверяване с SMS код беше премахнато за {{mfaPhoneCode}}',
      },
    },
    backupCodePage: {
      title: 'Добавяне на резервен код за потвърждение',
      title__codelist: 'Резервни кодове',
      subtitle__codelist: 'Запазете ги сигурно и ги държете в тайна.',
      infoText1: 'Резервните кодове ще бъдат активирани за този акаунт.',
      infoText2:
        'Дръжте резервните кодове в тайна и ги съхранявайте сигурно. Можете да генерирате нови резервни кодове, ако подозирате, че те са били компрометирани.',
      successSubtitle:
        'Можете да използвате един от тях, за да влезете в акаунта си, ако загубите достъпа до устройството си за удостоверяване.',
      successMessage:
        'Резервните кодове са активирани. Можете да използвате един от тях, за да влезете в акаунта си, ако загубите достъпа до устройството си за удостоверяване. Всеки код може да се използва само веднъж.',
      actionLabel__copy: 'Копиране на всички',
      actionLabel__copied: 'Копирано!',
      actionLabel__download: 'Изтегляне на .txt',
      actionLabel__print: 'Отпечатване',
    },
    deletePage: {
      title: 'Изтриване на акаунта',
      messageLine1: 'Сигурни ли сте, че искате да изтриете акаунта си?',
      messageLine2: 'Това действие е перманентно и необратимо.',
      actionDescription: 'Напишете "Изтриване на акаунта" по-долу, за да продължите.',
      confirm: 'Изтриване на акаунта',
    },
  },
  userButton: {
    action__manageAccount: 'Управление на акаунта',
    action__signOut: 'Изход',
    action__signOutAll: 'Изход от всички акаунти',
    action__addAccount: 'Добавяне на акаунт',
  },
  organizationSwitcher: {
    personalWorkspace: 'Личен акаунт',
    notSelected: 'Няма избрана организация',
    action__createOrganization: 'Създаване на организация',
    action__manageOrganization: 'Управление',
    action__invitationAccept: 'Присъединяване',
    action__suggestionsAccept: 'Заявка за присъединяване',
    suggestionsAcceptedLabel: 'Чакащо одобрение',
  },
  impersonationFab: {
    title: 'Влезли сте като {{identifier}}',
    action__signOut: 'Изход',
  },
  organizationProfile: {
    navbar: {
      title: 'Организация',
      description: 'Управление на вашата организация.',
      general: 'Общи',
      members: 'Членове',
    },
    badge__unverified: 'Неверифициран',
    badge__automaticInvitation: 'Автоматични покани',
    badge__automaticSuggestion: 'Автоматични предложения',
    badge__manualInvitation: 'Няма автоматично включване',
    start: {
      headerTitle__members: 'Членове',
    },
    profilePage: {
      title: 'Актуализиране на профила',
      successMessage: 'Организацията е актуализирана.',
      dangerSection: {
        title: 'Опасност',
        leaveOrganization: {
          title: 'Напускане на организацията',
          messageLine1:
            'Сигурни ли сте, че искате да напуснете тази организация? Ще загубите достъп до тази организация и нейните приложения.',
          messageLine2: 'Това действие е перманентно и необратимо.',
          successMessage: 'Излязохте от организацията.',
          actionDescription: 'Въведете "{{organizationName}}" по-долу, за да продължите.',
        },
        deleteOrganization: {
          title: 'Изтриване на организацията',
          messageLine1: 'Сигурни ли сте, че искате да изтриете тази организация?',
          messageLine2: 'Това действие е перманентно и необратимо.',
          actionDescription: 'Въведете "{{organizationName}}" по-долу, за да продължите.',
          successMessage: 'Изтрихте организацията.',
        },
      },
      domainSection: {
        title: 'Верифицирани домейни',
        subtitle:
          'Позволява на потребителите да се присъединяват към организацията автоматично или да заявят да се присъединят на база верифициран имейл домейн.',
        primaryButton: 'Добавяне на домейн',
      },
    },
    createDomainPage: {
      title: 'Добавяне на домейн',
      subtitle:
        'Добавете домейн за верификация. Потребителите с имейл адреси на този домейн могат да се присъединят към организацията автоматично или да заявят да се присъединят.',
    },
    verifyDomainPage: {
      title: 'Верификация на домейн',
      subtitle: 'Домейнът {{domainName}} трябва да бъде верифициран чрез имейл.',
      subtitleVerificationCodeScreen:
        'Беше изпратен код за верификация на {{emailAddress}}. Въведете кода, за да продължите.',
      formTitle: 'Код за верификация',
      formSubtitle: 'Въведете кода за верификация, изпратен на вашия имейл адрес',
      resendButton: 'Не сте получили код? Изпрати отново',
    },
    verifiedDomainPage: {
      title: 'Актуализиране на {{domain}}',
      subtitle: 'Домейнът {{domain}} вече е верифициран. Продължете, като изберете режим на записване.',
      start: {
        headerTitle__enrollment: 'Опции за записване',
        headerTitle__danger: 'Опасност',
      },
      enrollmentTab: {
        subtitle: 'Изберете как потребителите от този домейн могат да се присъединят към организацията.',
        manualInvitationOption__label: 'Без автоматично записване',
        manualInvitationOption__description: 'Потребителите могат да бъдат поканени само ръчно в организацията.',
        automaticInvitationOption__label: 'Автоматични покани',
        automaticInvitationOption__description:
          'Потребителите се поканват автоматично да се присъединят към организацията, когато се регистрират и могат да се присъединят по всяко време.',
        automaticSuggestionOption__label: 'Автоматични предложения',
        automaticSuggestionOption__description:
          'Потребителите получават предложение да заявят да се присъединят, но трябва да бъдат одобрени от администратор, преди да могат да се присъединят към организацията.',
        formButton__save: 'Запазване',
        calloutInfoLabel: 'Промяната на режима на записване ще засегне само новите потребители.',
        calloutInvitationCountLabel: 'Чакащи покани, изпратени на потребители: {{count}}',
        calloutSuggestionCountLabel: 'Чакащи предложения, изпратени на потребители: {{count}}',
      },
      dangerTab: {
        removeDomainTitle: 'Премахване на домейн',
        removeDomainSubtitle: 'Премахнете този домейн от верифицираните си домейни',
        removeDomainActionLabel__remove: 'Премахване на домейн',
        calloutInfoLabel: 'Премахването на този домейн ще засегне поканени потребители.',
      },
    },
    invitePage: {
      title: 'Покана за нови членове',
      subtitle: 'Въведете или поставете един или повече имейл адреси, разделени с интервали или запетая.',
      successMessage: 'Поканите бяха успешно изпратени',
      detailsTitle__inviteFailed:
        'Поканите не могат да бъдат изпратени. Вече има чакащи покани за следните имейл адреси: {{email_addresses}}.',
      formButtonPrimary__continue: 'Изпращане на покани',
    },
    removeDomainPage: {
      title: 'Премахване на домейн',
      messageLine1: 'Имейл домейнът {{domain}} ще бъде премахнат.',
      messageLine2: 'Потребителите няма да могат да се присъединяват автоматично към организацията след това.',
      successMessage: '{{domain}} беше премахнат.',
    },
    membersPage: {
      detailsTitle__emptyRow: 'Няма членове за показване',
      action__invite: 'Покани',
      start: {
        headerTitle__members: 'Членове',
        headerTitle__invitations: 'Покани',
        headerTitle__requests: 'Заявки',
      },
      activeMembersTab: {
        tableHeader__user: 'Потребител',
        tableHeader__joined: 'Присъединил се',
        tableHeader__role: 'Роля',
        tableHeader__actions: '',
        menuAction__remove: 'Премахване на член',
      },
      invitedMembersTab: {
        tableHeader__invited: 'Поканени',
        menuAction__revoke: 'Отмяна на поканата',
      },
      invitationsTab: {
        table__emptyRow: 'Няма покани за показване',
        manualInvitations: {
          headerTitle: 'Индивидуални покани',
          headerSubtitle: 'Ръчно поканете членове и управлявайте съществуващи покани.',
        },
        autoInvitations: {
          headerTitle: 'Автоматични покани',
          headerSubtitle:
            'Поканете потребители, свързващи имейл домейн с вашата организация. Всеки, който се регистрира със съответния имейл домейн, ще може да се присъедини към организацията по всяко време.',
          primaryButton: 'Управление на верифицираните домейни',
        },
      },
      requestsTab: {
        tableHeader__requested: 'Заявен достъп',
        menuAction__approve: 'Одобрение',
        menuAction__reject: 'Отхвърляне',
        table__emptyRow: 'Няма заявки за показване',
        requests: {
          headerTitle: 'Заявки',
          headerSubtitle:
            'Преглеждайте и управлявайте потребители, които са заявили да се присъединят към организацията.',
        },
        autoSuggestions: {
          headerTitle: 'Автоматични предложения',
          headerSubtitle:
            'Потребители, които се регистрират със съответния имейл домейн, ще видят предложение за заявка за присъединяване към вашата организация.',
          primaryButton: 'Управление на верифицираните домейни',
        },
      },
    },
  },
  createOrganization: {
    title: 'Създаване на организация',
    formButtonSubmit: 'Създаване на организация',
    invitePage: {
      formButtonReset: 'Пропусни',
    },
  },
  organizationList: {
    createOrganization: 'Създаване на организация',
    title: 'Изберете акаунт',
    titleWithoutPersonal: 'Изберете организация',
    subtitle: 'за продължаване към {{applicationName}}',
    action__invitationAccept: 'Присъединяване',
    invitationAcceptedLabel: 'Присъединен',
    action__suggestionsAccept: 'Заявка за присъединяване',
    suggestionsAcceptedLabel: 'Чакащо одобрение',
    action__createOrganization: 'Създаване на организация',
  },
  unstable__errors: {
    identification_deletion_failed: 'Не можете да изтриете последната си идентификация.',
    phone_number_exists: 'Този телефонен номер е зает. Моля, опитайте с друг.',
    form_identifier_not_found: '',
    captcha_unavailable:
      'Регистрацията неуспешна поради неуспешна валидация на бот. Моля, презаредете страницата, за да опитате отново, или се свържете с поддръжката за повече помощ.',
    captcha_invalid:
      'Регистрацията неуспешна поради неуспешни проверки за сигурност. Моля, презаредете страницата, за да опитате отново, или се свържете с поддръжката за повече помощ.',
    form_password_pwned: 'Тази парола е част от изтекли данни и не може да се използва. Моля, опитайте с друга парола.',
    form_username_invalid_length: '',
    form_username_invalid_character: '',
    form_param_format_invalid: '',
    form_param_format_invalid__phone_number: 'Телефонният номер трябва да бъде във валиден международен формат',
    form_param_format_invalid__email_address: 'Имейл адресът трябва да бъде във валиден имейл адрес.',
    form_password_length_too_short: '',
    form_param_nil: '',
    form_code_incorrect: '',
    form_password_incorrect: '',
    not_allowed_access: '',
    form_identifier_exists: '',
    form_password_validation_failed: 'Неправилна парола',
    form_password_not_strong_enough: 'Вашата парола не е достатъчно сигурна.',
    form_password_size_in_bytes_exceeded:
      'Паролата ви надвиши максималния брой байтове, позволен, моля, я скратете или премахнете някои специални знаци.',
    passwordComplexity: {
      sentencePrefix: 'Вашата парола трябва да съдържа',
      minimumLength: '{{length}} или повече символа',
      maximumLength: 'по-малко от {{length}} символа',
      requireNumbers: 'число',
      requireLowercase: 'малка буква',
      requireUppercase: 'главна буква',
      requireSpecialCharacter: 'специален символ',
    },
    zxcvbn: {
      notEnough: 'Вашата парола не е достатъчно сигурна.',
      couldBeStronger: 'Вашата парола работи, но може да бъде по-сигурна. Опитайте да добавите повече символи.',
      goodPassword: 'Вашата парола отговаря на всички необходими изисквания.',
      warnings: {
        straightRow: 'Редове от клавиши на клавиатурата са лесни за отгадване.',
        keyPattern: 'Кратки клавишни шаблони са лесни за отгадване.',
        simpleRepeat: 'Повтарящи се символи като "aaa" са лесни за отгадване.',
        extendedRepeat: 'Повтарящи се символни шаблони като "abcabcabc" са лесни за отгадване.',
        sequences: 'Обичайни символни последователности като "abc" са лесни за отгадване.',
        recentYears: 'Скорошни години са лесни за отгадване.',
        dates: 'Датите са лесни за отгадване.',
        topTen: 'Това е често използвана парола.',
        topHundred: 'Това е често използвана парола.',
        common: 'Това е често използвана парола.',
        similarToCommon: 'Това е подобно на често използвана парола.',
        wordByItself: 'Единични думи са лесни за отгадване.',
        namesByThemselves: 'Единични имена или фамилии са лесни за отгадване.',
        commonNames: 'Обичайни имена и фамилии са лесни за отгадване.',
        userInputs: 'Не трябва да има лични или свързани със страницата данни.',
        pwned: 'Вашата парола е била компроментирана от изтекли данни в Интернет.',
      },
      suggestions: {
        l33t: 'Избягвайте предвидими замествания на букви като "@" за "a".',
        reverseWords: 'Избягвайте обърнати написания на обичайни думи.',
        allUppercase: 'Направете главни някои, но не всички букви.',
        capitalization: 'Напревете главни повече от първата буква.',
        dates: 'Избягвайте дати и години, свързани с вас.',
        recentYears: 'Избягвайте скорошни години.',
        associatedYears: 'Избягвайте години, свързани с вас.',
        sequences: 'Избягвайте обичайни последователности от символи.',
        repeated: 'Избягвайте повтарящи се думи и символи.',
        longerKeyboardPattern: 'Използвайте по-дълги клавишни шаблони и променяйте посоката на набиране няколко пъти.',
        anotherWord: 'Добавете още думи, които са по-малко обичайни.',
        useWords: 'Използвайте няколко думи, но избягвайте обичайни фрази.',
        noNeed: 'Можете да създадете сигурни пароли и без да използвате символи, числа или главни букви.',
        pwned: 'Ако използвате тази парола на друго място, трябва да я промените.',
      },
    },
    form_param_max_length_exceeded__name: 'Името не трябва да надвишава 256 символа.',
    form_param_max_length_exceeded__first_name: 'Първото име не трябва да надвишава 256 символа.',
    form_param_max_length_exceeded__last_name: 'Фамилията не трябва да надвишава 256 символа.',
  },
  dates: {
    previous6Days: "Последно в {{ date | weekday('bg-BG','long') }} в {{ date | timeString('bg-BG') }}",
    lastDay: "Вчера в {{ date | timeString('bg-BG') }}",
    sameDay: "Днес в {{ date | timeString('bg-BG') }}",
    nextDay: "Утре в {{ date | timeString('bg-BG') }}",
    next6Days: "{{ date | weekday('bg-BG','long') }} в {{ date | timeString('bg-BG') }}",
    numeric: "{{ date | numeric('bg-BG') }}",
  },
} as const;
