import type { LocalizationResource } from '@clerk/types';

const commonTexts = {
  signIn: {
    phoneCode: {
      title: 'Tjek din telefon',
      subtitle: 'gå videre til {{applicationName}}',
      formTitle: 'Bekræftelseskode',
      formSubtitle: 'Indtast bekræftelseskoden sendt til dit telefonnummer',
      resendButton: 'Send kode igen',
    },
  },
} as const;

export const daDK: LocalizationResource = {
  socialButtonsBlockButton: 'Forsæt med {{provider|titleize}}',
  dividerText: 'eller',
  formFieldLabel__emailAddress: 'E-mailadresse',
  formFieldLabel__emailAddresses: 'E-mailadresser',
  formFieldLabel__phoneNumber: 'Telefonnummer',
  formFieldLabel__username: 'Brugernavn',
  formFieldLabel__emailAddress_phoneNumber: 'E-mailadresse eller telefonnummer',
  formFieldLabel__emailAddress_username: 'E-mailadresse eller brugernavn',
  formFieldLabel__phoneNumber_username: 'telefonnummer eller brugernavn',
  formFieldLabel__emailAddress_phoneNumber_username: 'E-mailadresse, telefonnummer eller brugernavn',
  formFieldLabel__password: 'Adgangskode',
  formFieldLabel__currentPassword: 'Nuværende adgangskode',
  formFieldLabel__newPassword: 'Ny adgangskode',
  formFieldLabel__confirmPassword: 'Bekræft adgangskode',
  formFieldLabel__signOutOfOtherSessions: 'Log ud af alle andre enheder',
  formFieldLabel__firstName: 'Fornavn',
  formFieldLabel__lastName: 'Efternavn',
  formFieldLabel__backupCode: 'Sikkerhedskode',
  formFieldLabel__organizationName: 'Organisationens navn',
  formFieldLabel__organizationSlug: 'Slug URL',
  formFieldLabel__role: 'Rolle',
  formFieldInputPlaceholder__emailAddress: '',
  formFieldInputPlaceholder__emailAddresses:
    'Indtast eller indsæt en eller flere e-mailadresser, adskilt af mellemrum eller kommaer',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber: '',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__phoneNumber_username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: '',
  formFieldInputPlaceholder__lastName: '',
  formFieldInputPlaceholder__backupCode: '',
  formFieldInputPlaceholder__organizationName: '',
  formFieldInputPlaceholder__organizationSlug: '',
  formFieldAction__forgotPassword: 'Glemt adgangskode',
  formFieldHintText__optional: 'Valgfri',
  formButtonPrimary: 'Fortsæt',
  signInEnterPasswordTitle: 'Indtast din adgangskode',
  backButton: 'Tilbage',
  footerActionLink__useAnotherMethod: 'Brug en anden metode',
  badge__primary: 'Primær',
  badge__thisDevice: 'Denne enhed',
  badge__userDevice: 'Bruger enhed',
  badge__otherImpersonatorDevice: '',
  badge__default: 'Standard',
  badge__unverified: 'Ikke verificeret',
  badge__requiresAction: 'Kræver handling',
  badge__you: 'Dig',
  footerPageLink__help: 'Hjælp',
  footerPageLink__privacy: 'Privatliv',
  footerPageLink__terms: 'Vilkår',
  paginationButton__previous: 'Forrige',
  paginationButton__next: 'Næste',
  paginationRowText__displaying: 'Viser',
  paginationRowText__of: 'af',
  membershipRole__admin: 'Administrator',
  membershipRole__basicMember: 'Medlem',
  membershipRole__guestMember: 'Gæst',
  signUp: {
    start: {
      title: 'Opret din konto',
      subtitle: 'Forsæt til {{applicationName}}',
      actionText: 'Har du en konto?',
      actionLink: 'Log ind',
    },
    emailLink: {
      title: 'Bekræft din email',
      subtitle: 'Forsæt til {{applicationName}}',
      formTitle: 'Bekræftelseslink',
      formSubtitle: 'Brug bekræftelseslinket sendt til din e-mailadresse',
      resendButton: 'Send link igen',
      verified: {
        title: 'Vellykket tilmelding',
      },
      loading: {
        title: 'Tilmelder...',
      },
      verifiedSwitchTab: {
        title: 'E-mail er bekræftet',
        subtitle: 'Vend tilbage til den nyligt åbnede fane for at fortsætte',
        subtitleNewTab: 'Vend tilbage til forrige fane for at fortsætte',
      },
    },
    emailCode: {
      title: 'Bekræft din email',
      subtitle: 'Fortsæt til {{applicationName}}',
      formTitle: 'Bekræftelseskode',
      formSubtitle: 'Indtast bekræftelseskoden sendt til din e-mailadresse',
      resendButton: 'Send kode igen',
    },
    phoneCode: {
      title: 'Bekræft din telefon',
      subtitle: 'Fortsæt til {{applicationName}}',
      formTitle: 'Bekræftelseskode',
      formSubtitle: 'Indtast bekræftelseskoden sendt til dit telefonnummer',
      resendButton: 'Send kode igen',
    },
    continue: {
      title: 'Udfyld manglende felter',
      subtitle: 'Forsæt til {{applicationName}}',
      actionText: 'Har du en konto?',
      actionLink: 'Log ind',
    },
  },
  signIn: {
    start: {
      title: 'Log ind',
      subtitle: 'Forsæt til {{applicationName}}',
      actionText: 'Ingen konto?',
      actionLink: 'Tilmeld dig',
      actionLink__use_email: 'Brug email',
      actionLink__use_phone: 'Brug telefon',
      actionLink__use_username: 'Brug brugenravn',
      actionLink__use_email_username: 'Brug email eller brugernavn',
    },
    password: {
      title: 'Indtast din adgangskode',
      subtitle: 'Fortsæt til {{applicationName}}',
      actionLink: 'Brug en anden metode',
    },
    emailCode: {
      title: 'Tjek din email',
      subtitle: 'Fortsæt til {{applicationName}}',
      formTitle: 'Bekræftelseskode',
      formSubtitle: 'Indtast bekræftelseskoden sendt til din e-mailadresse',
      resendButton: 'Send kode igen',
    },
    emailLink: {
      title: 'Tjek din email',
      subtitle: 'Fortsæt til {{applicationName}}',
      formTitle: 'Bekræftelseslink',
      formSubtitle: 'Brug bekræftelseslinket sendt til din e-mail',
      resendButton: 'Send link igen',
      unusedTab: {
        title: 'Du kan lukke denne fane',
      },
      verified: {
        title: 'Vellykket log ind forsøg',
        subtitle: 'Du vil snart blive viderestillet',
      },
      verifiedSwitchTab: {
        subtitle: 'Vend tilbage til den oprindelige fane for at fortsætte',
        titleNewTab: 'Logget ind på anden fane',
        subtitleNewTab: 'Vend tilbage til den nyligt åbnede fane for at fortsætte',
      },
      loading: {
        title: 'Logger ind...',
        subtitle: 'Du vil snart blive viderestillet',
      },
      failed: {
        title: 'Dette bekræftelseslink er ugyldigt',
        subtitle: 'Vend tilbage til den oprindelige fane for at fortsætte.',
      },
      expired: {
        title: 'Dette bekræftelseslink er udløbet',
        subtitle: 'Vend tilbage til den oprindelige fane for at fortsætte.',
      },
    },
    phoneCode: { ...commonTexts.signIn.phoneCode },
    phoneCodeMfa: { ...commonTexts.signIn.phoneCode, subtitle: '' },
    totpMfa: {
      title: 'Totrinsbekræftelse',
      subtitle: '',
      formTitle: 'Bekræftelseskode',
      formSubtitle: 'Indtast den bekræftelseskode, der er genereret af din godkendelsesapp',
    },
    backupCodeMfa: {
      title: 'Indtast en backup-kode',
      subtitle: 'Forsæt til {{applicationName}}',
      formTitle: '',
      formSubtitle: '',
    },
    alternativeMethods: {
      title: 'Brug en anden metode',
      actionLink: 'Få hjælp',
      blockButton__emailLink: 'Send link til {{identifier}}',
      blockButton__emailCode: 'Send kode til {{identifier}}',
      blockButton__phoneCode: 'Send kode til {{identifier}}',
      blockButton__password: 'Log ind med din adgangskode',
      blockButton__totp: 'Brug din godkendelsesapp',
      blockButton__backupCode: 'Brug en backup-kode',
      getHelp: {
        title: 'Få hjælp',
        content: `Hvis du har problemer med at logge ind på din konto, skal du sende en e-mail til os, og vi vil samarbejde med dig om at genoprette adgang så hurtigt som muligt.`,
        blockButton__emailSupport: 'E-mail support',
      },
    },
    noAvailableMethods: {
      title: 'Kan ikke logge ind',
      subtitle: 'En fejl opstod',
      message: "Kan ikke fortsætte med login. Der er ingen tilgængelig godkendelsesfaktor.",
    },
  },
  userProfile: {
    mobileButton__menu: 'Menu',
    formButtonPrimary__continue: 'Fortsæt',
    formButtonPrimary__finish: 'Afslut',
    formButtonReset: 'Annuller',
    start: {
      headerTitle__account: 'Konto',
      headerTitle__security: 'Sikkerhed',
      headerSubtitle__account: 'Administrere dine kontooplysninger',
      headerSubtitle__security: 'Administrere dine sikkerhedspræferencer',
      profileSection: {
        title: 'Profil',
      },
      usernameSection: {
        title: 'Brugernavn',
        primaryButton__changeUsername: 'Skift brugernavn',
        primaryButton__setUsername: 'Sæt brugernavn',
      },
      emailAddressesSection: {
        title: 'E-mailadresser',
        primaryButton: 'Tilføj en e-mailadresse',
        detailsTitle__primary: 'Primær e-mailadresse',
        detailsSubtitle__primary: 'Denne e-mailadresse er den primære e-mailadresse',
        detailsAction__primary: 'Færdiggøre bekræftelse',
        detailsTitle__nonPrimary: 'Angiv som primær e-mailadresse',
        detailsSubtitle__nonPrimary:
          'Indstil denne e-mailadresse som den primære til at modtage kommunikation vedrørende din konto.',
        detailsAction__nonPrimary: 'Sæt som primær',
        detailsTitle__unverified: 'Ubekræftet e-mailadresse',
        detailsSubtitle__unverified: 'Denne e-mailadresse er ikke blevet bekræftet, og kan være begrænset i funktionalitet',
        detailsAction__unverified: 'Færdiggøre bekræftelse',
        destructiveActionTitle: 'Fjern',
        destructiveActionSubtitle: 'Slet denne e-mailadresse og fjern den fra din konto',
        destructiveAction: 'Fjern e-mailadresse',
      },
      phoneNumbersSection: {
        title: 'Telefonnumre',
        primaryButton: 'Tilføj et telefonnummer',
        detailsTitle__primary: 'Primære telefonnummer',
        detailsSubtitle__primary: 'Dette telefonnummer er det primære telefonnummer',
        detailsAction__primary: 'Færdiggøre bekræftelse',
        detailsTitle__nonPrimary: 'Sæt som primært telefonnummer',
        detailsSubtitle__nonPrimary:
          'Indstil dette telefonnummer som det primære til at modtage kommunikation vedrørende din konto.',
        detailsAction__nonPrimary: 'Sæt som primær',
        detailsTitle__unverified: 'Ubekræftet telefonnummer',
        detailsSubtitle__unverified: 'Dette telefonnummer er ikke blevet bekræftet, og kan være begrænset i funktionalitet',
        detailsAction__unverified: 'Færdiggøre bekræftelse',
        destructiveActionTitle: 'Fjern',
        destructiveActionSubtitle: 'Slet dette telefonnummer og fjern det fra din konto',
        destructiveAction: 'Fjern telefonnummer',
      },
      connectedAccountsSection: {
        title: 'Tilknyttede kontier',
        primaryButton: 'Tilknyt konto',
        title__conectionFailed: 'Forsøg mislykkedes',
        title__connectionFailed: 'Andet forsøg mislykkedes',
        title__reauthorize: 'Godkendelse mangler',
        subtitle__reauthorize:
          'De påkrævede omfang er blevet opdateret, og du oplever muligvis begrænset funktionalitet. Godkend denne applikation igen for at undgå problemer',
        actionLabel__conectionFailed: 'Prøv igen',
        actionLabel__connectionFailed: 'Prøv igen',
        actionLabel__reauthorize: 'Godkend nu',
        destructiveActionTitle: 'Fjern',
        destructiveActionSubtitle: 'Fjern denne forbundne konto fra din konto',
        destructiveActionAccordionSubtitle: 'Fjern tilsluttet konto',
      },
      passwordSection: {
        title: 'Adgangskode',
        primaryButton__changePassword: 'Skift adgangskode',
        primaryButton__setPassword: 'Indtast adgangskode',
      },
      mfaSection: {
        title: 'Totrinsbekræftelse',
        primaryButton: 'Add two-step verification',
        phoneCode: {
          destructiveActionTitle: 'Remove',
          destructiveActionSubtitle: 'Remove this phone number from the two-step verification methods',
          destructiveActionLabel: 'Remove phone number',
          title__default: 'Default factor',
          title__setDefault: 'Set as Default factor',
          subtitle__default: 'This factor will be used as the default two-step verification method when signing in.',
          subtitle__setDefault:
            'Set this factor as the default factor to use it as the default two-step verification method when signing in.',
          actionLabel__setDefault: 'Set as default',
        },
        backupCodes: {
          headerTitle: 'Backup codes',
          title__regenerate: 'Regenerate backup codes',
          subtitle__regenerate:
            'Get a fresh set of secure backup codes. Prior backup codes will be deleted and cannot be used.',
          actionLabel__regenerate: 'Regenerate codes',
        },
        totp: {
          headerTitle: 'Authenticator application',
          title: 'Default factor',
          subtitle: 'This factor will be used as the default two-step verification method when signing in.',
          destructiveActionTitle: 'Remove',
          destructiveActionSubtitle: 'Remove authenticator application from the two-step verification methods',
          destructiveActionLabel: 'Remove authenticator application',
        },
      },
      activeDevicesSection: {
        title: 'Active devices',
        primaryButton: 'Active devices',
        detailsTitle: 'Current device',
        detailsSubtitle: 'This is the device you are currently using',
        destructiveActionTitle: 'Sign out',
        destructiveActionSubtitle: 'Sign out from your account on this device',
        destructiveAction: 'Sign out of device',
      },
      web3WalletsSection: {
        title: 'Web3 wallets',
        primaryButton: 'Web3 wallets',
        destructiveActionTitle: 'Remove',
        destructiveActionSubtitle: 'Remove this web3 wallet from your account',
        destructiveAction: 'Remove wallet',
      },
    },
    profilePage: {
      title: 'Update profile',
      imageFormTitle: 'Profile image',
      imageFormSubtitle: 'Upload image',
      imageFormDestructiveActionSubtitle: 'Remove image',
      fileDropAreaTitle: 'Drag file here, or...',
      fileDropAreaAction: 'Select file',
      fileDropAreaHint: 'Upload a JPG, PNG, GIF, or WEBP image smaller than 10 MB',
      successMessage: 'Your profile has been updated.',
    },
    usernamePage: {
      title: 'Update username',
      successMessage: 'Your username has been updated.',
    },
    emailAddressPage: {
      title: 'Add email address',
      emailCode: {
        formHint: 'An email containing a verification code will be sent to this email address.',
        formTitle: 'Verification code',
        formSubtitle: 'Enter the verification code sent to {{identifier}}',
        resendButton: 'Resend code',
        successMessage: 'The email {{identifier}} has been added to your account.',
      },
      emailLink: {
        formHint: 'An email containing a verification link will be sent to this email address.',
        formTitle: 'Verification link',
        formSubtitle: 'Click on the verification link in the email sent to {{identifier}}',
        resendButton: 'Resend link',
        successMessage: 'The email {{identifier}} has been added to your account.',
      },
      removeResource: {
        title: 'Remove email address',
        messageLine1: '{{identifier}} will be removed from this account.',
        messageLine2: 'You will no longer be able to sign in using this email address.',
        successMessage: '{{emailAddress}} has been removed from your account.',
      },
    },
    phoneNumberPage: {
      title: 'Add phone number',
      successMessage: '{{identifier}} has been added to your account.',
      infoText: 'A text message containing a verification link will be sent to this phone number.',
      infoText__secondary: 'Message and data rates may apply.',
      removeResource: {
        title: 'Remove phone number',
        messageLine1: '{{identifier}} will be removed from this account.',
        messageLine2: 'You will no longer be able to sign in using this phone number.',
        successMessage: '{{phoneNumber}} has been removed from your account.',
      },
    },
    connectedAccountPage: {
      title: 'Add connected account',
      formHint: 'Select a provider to connect your account.',
      formHint__noAccounts: 'There are no available external account providers.',
      socialButtonsBlockButton: 'Connect {{provider|titleize}} account',
      successMessage: 'The provider has been added to your account',
      removeResource: {
        title: 'Remove connected account',
        messageLine1: '{{identifier}} will be removed from this account.',
        messageLine2:
          'You will no longer be able to use this connected account and any dependent features will no longer work.',
        successMessage: '{{connectedAccount}} has been removed from your account.',
      },
    },
    web3WalletPage: {
      title: 'Add web3 wallet',
      subtitle__availableWallets: 'Select a web3 wallet to connect to your account.',
      subtitle__unavailableWallets: 'There are no available web3 wallets.',
      successMessage: 'The wallet has been added to your account.',
      removeResource: {
        title: 'Remove web3 wallet',
        messageLine1: '{{identifier}} will be removed from this account.',
        messageLine2: 'You will no longer be able to sign in using this web3 wallet.',
        successMessage: '{{web3Wallet}} has been removed from your account.',
      },
    },
    passwordPage: {
      title: 'Set password',
      changePasswordTitle: 'Change password',
      successMessage: 'Your password has been set.',
      changePasswordSuccessMessage: 'Your password has been updated.',
      sessionsSignedOutSuccessMessage: 'All other devices have been signed out.',
    },
    mfaPage: {
      title: 'Add two-step verification',
      formHint: 'Select a method to add.',
    },
    mfaTOTPPage: {
      title: 'Add authenticator application',
      verifyTitle: 'Verification code',
      verifySubtitle: 'Enter verification code generated by your authenticator',
      successMessage:
        'Two-step verification is now enabled. When signing in, you will need to enter a verification code from this authenticator as an additional step.',
      authenticatorApp: {
        infoText__ableToScan:
          'Set up a new sign-in method in your authenticator app and scan the following QR code to link it to your account.',
        infoText__unableToScan: 'Set up a new sign-in method in your authenticator and enter the Key provided below.',
        inputLabel__unableToScan1:
          'Make sure Time-based or One-time passwords is enabled, then finish linking your account.',
        inputLabel__unableToScan2:
          'Alternatively, if your authenticator supports TOTP URIs, you can also copy the full URI.',
        buttonAbleToScan__nonPrimary: 'Scan QR code instead',
        buttonUnableToScan__nonPrimary: 'Can’t scan QR code?',
      },
      removeResource: {
        title: 'Remove two-step verification',
        messageLine1: 'Verification codes from this authenticator will no longer be required when signing in.',
        messageLine2: 'Your account may not be as secure. Are you sure you want to continue?',
        successMessage: 'Two-step verification via authenticator application has been removed.',
      },
    },
    mfaPhoneCodePage: {
      title: 'Add SMS code verification',
      primaryButton__addPhoneNumber: 'Add a phone number',
      subtitle__availablePhoneNumbers: 'Select a phone number to register for SMS code two-step verification.',
      subtitle__unavailablePhoneNumbers:
        'There are no available phone numbers to register for SMS code two-step verification.',
      successMessage:
        'SMS code two-step verification is now enabled for this phone number. When signing in, you will need to enter a verification code sent to this phone number as an additional step.',
      removeResource: {
        title: 'Remove two-step verification',
        messageLine1: '{{identifier}} will be no longer receiving verification codes when signing in.',
        messageLine2: 'Your account may not be as secure. Are you sure you want to continue?',
        successMessage: 'SMS code two-step verification has been removed for {{mfaPhoneCode}}',
      },
    },
    backupCodePage: {
      title: 'Add backup code verification',
      title__codelist: 'Backup codes',
      subtitle__codelist: 'Store them securely and keep them secret.',
      infoText1: 'Backup codes will be enabled for this account.',
      infoText2:
        'Keep the backup codes secret and store them securely. You may regenerate backup codes if you suspect they have been compromised.',
      successSubtitle:
        'You can use one of these to sign in to your account, if you lose access to your authentication device.',
      successMessage:
        'Backup codes are now enabled. You can use one of these to sign in to your account, if you lose access to your authentication device. Each code can only be used once.',
      actionLabel__copy: 'Copy all',
      actionLabel__copied: 'Copied!',
      actionLabel__download: 'Download .txt',
      actionLabel__print: 'Print',
    },
  },
  userButton: {
    action__manageAccount: 'Manage account',
    action__signOut: 'Sign out',
    action__signOutAll: 'Sign out of all accounts',
    action__addAccount: 'Add account',
  },
  organizationSwitcher: {
    personalWorkspace: 'Personal Workspace',
    notSelected: 'No organization selected',
    action__createOrganization: 'Create Organization',
    action__manageOrganization: 'Manage Organization',
  },
  impersonationFab: {
    title: 'Signed in as {{identifier}}',
    action__signOut: 'Sign out',
  },
  organizationProfile: {
    start: {
      headerTitle__members: 'Members',
      headerTitle__settings: 'Settings',
      headerSubtitle__members: 'View and manage organization members',
      headerSubtitle__settings: 'Manage organization settings',
    },
    profilePage: {
      title: 'Organization Profile',
      subtitle: 'Manage organization profile',
      successMessage: 'The organization has been updated.',
      dangerSection: {
        title: 'Danger',
        leaveOrganization: {
          title: 'Leave organization',
          messageLine1:
            'Are you sure you want to leave this organization? You will lose access to this organization and its applications.',
          messageLine2: 'This action is permanent and irreversible.',
          successMessage: 'You have left the organization.',
        },
      },
    },
    invitePage: {
      title: 'Invite members',
      subtitle: 'Invite new members to this organization',
      successMessage: 'Invitations successfully sent',
      detailsTitle__inviteFailed: 'The invitations could not be sent. Fix the following and try again:',
      formButtonPrimary__continue: 'Send invitations',
    },
    membersPage: {
      detailsTitle__emptyRow: 'No members to display',
      action__invite: 'Invite',
      start: {
        headerTitle__active: 'Active',
        headerTitle__invited: 'Invited',
      },
      activeMembersTab: {
        tableHeader__user: 'User',
        tableHeader__joined: 'Joined',
        tableHeader__role: 'Role',
        tableHeader__actions: '',
        menuAction__remove: 'Remove member',
      },
      invitedMembersTab: {
        tableHeader__invited: 'Invited',
        menuAction__revoke: 'Revoke invitation',
      },
    },
  },
  createOrganization: {
    title: 'Create Organization',
    formButtonSubmit: 'Create organization',
    subtitle: 'Set the organization profile',
    invitePage: {
      formButtonReset: 'Skip',
    },
  },
  unstable__errors: {
    form_identifier_not_found: '',
    form_password_pwned: '',
    form_username_invalid_length: '',
    form_param_format_invalid: '',
    form_password_length_too_short: '',
    form_param_nil: '',
    form_code_incorrect: '',
    form_password_incorrect: '',
    not_allowed_access: '',
    form_identifier_exists: '',
  },
  dates: {
    previous6Days: "Last {{ date | weekday('en-US','long') }} at {{ date | timeString('en-US') }}",
    lastDay: "Yesterday at {{ date | timeString('en-US') }}",
    sameDay: "Today at {{ date | timeString('en-US') }}",
    nextDay: "Tomorrow at {{ date | timeString('en-US') }}",
    next6Days: "{{ date | weekday('en-US','long') }} at {{ date | timeString('en-US') }}",
    numeric: "{{ date | numeric('en-US') }}",
  },
} as const;
