import type { LocalizationResource } from '@clerk/types';

const commonTexts = {
  signIn: {
    phoneCode: {
      title: 'Periksa telepon mu',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: 'Kode verifikasi',
      formSubtitle: 'Masukkan kode verifikasi yang dikirim ke nomor telepon Anda',
      resendButton: 'Ulang kode',
    },
  },
} as const;

export const idID: LocalizationResource = {
  socialButtonsBlockButton: 'Lanjutkan dengan {{provider|titleize}}',
  dividerText: 'atau',
  formFieldLabel__emailAddress: 'Alamat email',
  formFieldLabel__emailAddresses: 'Alamat email',
  formFieldLabel__phoneNumber: 'Nomor telepon',
  formFieldLabel__username: 'Nama belakang',
  formFieldLabel__emailAddress_phoneNumber: 'Alamat email atau nomor telepon',
  formFieldLabel__emailAddress_username: 'Alamat email atau username',
  formFieldLabel__phoneNumber_username: 'nomor telepon atau nama pengguna',
  formFieldLabel__emailAddress_phoneNumber_username: 'Alamat email, nomor telepon atau nama pengguna',
  formFieldLabel__password: 'Kata sandi',
  formFieldLabel__currentPassword: 'Kata sandi saat ini',
  formFieldLabel__newPassword: 'Kata sandi baru',
  formFieldLabel__confirmPassword: 'Konfirmasi sandi',
  formFieldLabel__signOutOfOtherSessions: 'Keluar dari semua perangkat lain',
  formFieldLabel__firstName: 'Nama depan',
  formFieldLabel__lastName: 'Nama keluarga',
  formFieldLabel__backupCode: 'Kode cadangan',
  formFieldLabel__organizationName: 'Nama Organisasi',
  formFieldLabel__organizationSlug: 'URL Slug',
  formFieldLabel__role: 'Peran',
  formFieldInputPlaceholder__emailAddress: '',
  formFieldInputPlaceholder__emailAddresses:
    'Masukkan atau tempel satu atau lebih alamat email, dipisahkan oleh spasi atau koma',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber: '',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__phoneNumber_username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: '',
  formFieldInputPlaceholder__lastName: '',
  formFieldInputPlaceholder__backupCode: '',
  formFieldInputPlaceholder__organizationName: '',
  formFieldInputPlaceholder__organizationSlug: '',
  formFieldAction__forgotPassword: 'Tidak ingat kata sandi',
  formFieldHintText__optional: 'Opsional',
  formButtonPrimary: 'Lanjutkan',
  signInEnterPasswordTitle: 'Masukkan kata sandi Anda',
  backButton: 'Kembali',
  footerActionLink__useAnotherMethod: 'Gunakan metode lain',
  badge__primary: 'Utama',
  badge__thisDevice: 'Alat ini',
  badge__userDevice: 'Perangkat pengguna',
  badge__otherImpersonatorDevice: 'Perangkat peniru lainnya',
  badge__default: 'Bawaan',
  badge__unverified: 'Tidak diverifikasi',
  badge__requiresAction: 'Membutuhkan tindakan',
  badge__you: 'Anda',
  footerPageLink__help: 'Membantu',
  footerPageLink__privacy: 'Pribadi',
  footerPageLink__terms: 'Ketentuan',
  paginationButton__previous: 'Sebelumnya',
  paginationButton__next: 'Berikutnya',
  paginationRowText__displaying: 'Menampilkan',
  paginationRowText__of: 'dari',
  membershipRole__admin: 'admin',
  membershipRole__basicMember: 'Anggota',
  membershipRole__guestMember: 'Tamu',
  signUp: {
    start: {
      title: 'buat akun Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      actionText: 'Punya akun?',
      actionLink: 'Masuk',
    },
    emailLink: {
      Judul: 'Verifikasi email Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      FormTitle: 'Tautan Verifikasi',
      Formsubtitle: 'Gunakan tautan verifikasi yang dikirim ke alamat email Anda',
      ResendButton: 'Rekomendasikan Tautan',
      verified: {
        Judul: 'berhasil mendaftar',
      },
      loading: {
        Judul: 'Mendaftar ...',
      },
      verifiedSwitchTab: {
        Judul: 'Email yang berhasil diverifikasi',
        Subtitle: 'Kembali ke tab yang baru dibuka untuk dilanjutkan',
        subtitlenewtab: 'Kembali ke tab sebelumnya untuk melanjutkan',
      },
    },
    emailCode: {
      title: 'Verifikasi email Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: 'Kode verifikasi',
      formSubtitle: 'Masukkan kode verifikasi yang dikirim ke alamat email Anda',
      resendButton: 'Ulang kode',
    },
    phoneCode: {
      title: 'Verifikasi ponsel Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: 'Kode verifikasi',
      formSubtitle: 'Masukkan kode verifikasi yang dikirim ke nomor telepon Anda',
      resendButton: 'Ulang kode',
    },
    continue: {
      title: 'Isi bidang yang hilang',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      actionText: 'Punya akun?',
      actionLink: 'Masuk',
    },
  },
  signIn: {
    start: {
      title: 'Masuk',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      actionText: 'Tidak ada akun?',
      actionLink: 'Mendaftar',
      actionLink__use_email: 'Gunakan email',
      actionLink__use_phone: 'Gunakan telepon',
      actionLink__use_username: 'Gunakan nama pengguna',
      actionLink__use_email_username: 'Gunakan email atau nama pengguna',
    },
    password: {
      title: 'Masukkan kata sandi Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      actionLink: 'Gunakan metode lain',
    },
    emailCode: {
      title: 'Periksa email Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: 'Kode verifikasi',
      formSubtitle: 'Masukkan kode verifikasi yang dikirim ke alamat email Anda',
      resendButton: 'Ulang kode',
    },
    emailLink: {
      title: 'Periksa email Anda',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: 'Tautan verifikasi',
      formSubtitle: 'Gunakan tautan verifikasi yang dikirim ke email Anda',
      resendButton: 'Ulang tautan',
      unusedTab: {
        title: 'Anda dapat menutup tab ini',
      },
      verified: {
        title: 'Berhasil masuk',
        subtitle: 'Anda akan segera dialihkan',
      },
      verifiedSwitchTab: {
        subtitle: 'Kembali ke tab asli untuk melanjutkan',
        titleNewTab: 'Masuk di tab lain',
        subtitleNewTab: 'Kembali ke tab yang baru dibuka untuk melanjutkan',
      },
      loading: {
        title: 'Masuk...',
        subtitle: 'Anda akan segera dialihkan',
      },
      failed: {
        title: 'Tautan verifikasi ini tidak valid',
        subtitle: 'Kembali ke tab asli untuk melanjutkan.',
      },
      expired: {
        title: 'Tautan verifikasi ini telah kedaluwarsa',
        subtitle: 'Kembali ke tab asli untuk melanjutkan.',
      },
    },
    phoneCode: { ...commonTexts.signIn.phoneCode },
    phoneCodeMfa: { ...commonTexts.signIn.phoneCode, subtitle: '' },
    totpMfa: {
      title: 'Verifikasi dua langkah',
      subtitle: '',
      formTitle: 'Kode verifikasi',
      formSubtitle: 'Masukkan kode verifikasi yang dihasilkan oleh aplikasi Authenticator Anda',
    },
    backupCodeMfa: {
      title: 'Masukkan kode cadangan',
      subtitle: 'untuk melanjutkan ke {{applicationName}}',
      formTitle: '',
      formSubtitle: '',
    },
    alternativeMethods: {
      title: 'Gunakan metode lain',
      actionLink: 'Mendapatkan bantuan',
      blockButton__emailLink: 'Kirim tautan ke {{identifier}}',
      blockButton__emailCode: 'Kirim kode ke {{identifier}}',
      blockButton__phoneCode: 'Kirim kode ke {{identifier}}',
      blockButton__password: 'Masuk dengan Kata Sandi Anda',
      blockButton__totp: 'Gunakan aplikasi Authenticator Anda',
      blockButton__backupCode: 'Gunakan kode cadangan',
      getHelp: {
        title: 'Mendapatkan bantuan',
        content: `Jika Anda mengalami kesulitan masuk ke akun Anda, email kami dan kami akan bekerja dengan Anda untuk mengembalikan akses sesegera mungkin.`,
        blockButton__emailSupport: 'Dukungan email',
      },
    },
    noAvailableMethods: {
      title: 'Tidak bisa masuk',
      subtitle: 'Terjadi kesalahan',
      message: "Tidak dapat melanjutkan dengan masuk. Tidak ada faktor otentikasi yang tersedia.",
    },
  },
  userProfile: {
    mobileButton__menu: 'menu',
    formButtonPrimary__continue: 'Lanjutkan',
    formButtonPrimary__finish: 'Selesaikan',
    formButtonReset: 'Batalkan',
    start: {
      headerTitle__account: 'Akun',
      headerTitle__security: 'Keamanan',
      headerSubtitle__account: 'Kelola Informasi Akun Anda',
      headerSubtitle__security: 'Kelola Preferensi Keamanan Anda',
      profileSection: {
        title: 'Profil',
      },
      usernameSection: {
        title: 'Nama pengguna',
        primaryButton__changeUsername: 'Ubah Nama Pengguna',
        primaryButton__setUsername: 'Atur nama pengguna',
      },
      emailAddressesSection: {
        title: 'Alamat email',
        primaryButton: 'Tambahkan alamat email',
        detailsTitle__primary: 'Alamat email utama',
        detailsSubtitle__primary: 'Alamat email ini adalah alamat email utama',
        detailsAction__primary: 'Verifikasi lengkap',
        detailsTitle__nonPrimary: 'Ditetapkan sebagai alamat email utama',
        detailsSubtitle__nonPrimary:
          'Tetapkan alamat email ini sebagai yang utama untuk menerima komunikasi mengenai akun Anda.',
        detailsAction__nonPrimary: 'Tetapkan sebagai utama',
        detailsTitle__unverified: 'Alamat email yang tidak diverifikasi',
        detailsSubtitle__unverified: 'Alamat email ini belum diverifikasi dan mungkin terbatas dalam fungsionalitas',
        detailsAction__unverified: 'Verifikasi lengkap',
        destructiveActionTitle: 'Menghapus',
        destructiveActionSubtitle: 'Hapus alamat email ini dan hapus dari akun Anda',
        destructiveAction: 'Hapus alamat email',
      },
      phoneNumbersSection: {
        title: 'Nomor telepon',
        primaryButton: 'Tambahkan nomor telepon',
        detailsTitle__primary: 'Nomor Telepon Utama',
        detailsSubtitle__primary: 'Nomor telepon ini adalah nomor telepon utama',
        detailsAction__primary: 'Verifikasi lengkap',
        detailsTitle__nonPrimary: 'Setel sebagai nomor telepon utama',
        detailsSubtitle__nonPrimary:
          'Tetapkan nomor telepon ini sebagai yang utama untuk menerima komunikasi mengenai akun Anda.',
        detailsAction__nonPrimary: 'Tetapkan sebagai utama',
        detailsTitle__unverified: 'Nomor telepon yang tidak diverifikasi',
        detailsSubtitle__unverified: 'Nomor telepon ini belum diverifikasi dan mungkin terbatas dalam fungsionalitas',
        detailsAction__unverified: 'Verifikasi lengkap',
        destructiveActionTitle: 'Menghapus',
        destructiveActionSubtitle: 'Hapus nomor telepon ini dan hapus dari akun Anda',
        destructiveAction: 'Hapus nomor telepon',
      },
      connectedAccountsSection: {
        title: 'Akun yang terhubung',
        primaryButton: 'Hubungkan Akun',
        title__conectionFailed: 'Coba lagi koneksi yang gagal',
        title__reauthorize: 'Diperlukan otorisasi ulang',
        subtitle__reauthorize:
          'Lingkup yang diperlukan telah diperbarui, dan Anda mungkin mengalami fungsionalitas terbatas.Harap amati ulang aplikasi ini untuk menghindari masalah apa pun',
        actionLabel__conectionFailed: 'Coba lagi',
        actionLabel__reauthorize: 'Otorisasi sekarang',
        destructiveActionTitle: 'Menghapus',
        destructiveActionSubtitle: 'Hapus akun yang terhubung ini dari akun Anda',
        destructiveActionAccordionSubtitle: 'Hapus akun yang terhubung',
      },
      passwordSection: {
        title: 'Kata sandi',
        primaryButton__changePassword: 'Ganti kata sandi',
        primaryButton__setPassword: 'Atur kata sandi',
      },
      mfaSection: {
        title: 'Verifikasi dua langkah',
        primaryButton: 'Tambahkan verifikasi dua langkah',
        phoneCode: {
          destructiveActionTitle: 'Menghapus',
          destructiveActionSubtitle: 'Hapus nomor telepon ini dari metode verifikasi dua langkah',
          destructiveActionLabel: 'Hapus nomor telepon',
          title__default: 'Faktor default',
          title__setDefault: 'Tetapkan sebagai faktor default',
          subtitle__default: 'Faktor ini akan digunakan sebagai metode verifikasi dua langkah default saat masuk.',
          subtitle__setDefault:
            'Tetapkan faktor ini sebagai faktor default untuk menggunakannya sebagai metode verifikasi dua langkah default saat masuk.',
          actionLabel__setDefault: 'Ditetapkan sebagai default',
        },
        backupCodes: {
          headerTitle: 'Kode cadangan',
          title__regenerate: 'Kode Cadangan Regenerasi',
          subtitle__regenerate:
            'Dapatkan satu set kode cadangan yang aman.Kode cadangan sebelumnya akan dihapus dan tidak dapat digunakan.',
          actionLabel__regenerate: 'Buat ulang kode',
        },
        totp: {
          headerTitle: 'Aplikasi Authenticator',
          title: 'Faktor default',
          subtitle: 'Faktor ini akan digunakan sebagai metode verifikasi dua langkah default saat masuk.',
          destructiveActionTitle: 'Menghapus',
          destructiveActionSubtitle: 'Hapus aplikasi Authenticator dari metode verifikasi dua langkah',
          destructiveActionLabel: 'Hapus Aplikasi Authenticator',
        },
      },
      activeDevicesSection: {
        title: 'Perangkat aktif',
        primaryButton: 'Perangkat aktif',
        detailsTitle: 'Perangkat saat ini',
        detailsSubtitle: 'Ini adalah perangkat yang sedang Anda gunakan',
        destructiveActionTitle: 'Keluar',
        destructiveActionSubtitle: 'Keluar dari akun Anda di perangkat ini',
        destructiveAction: 'Keluar dari perangkat',
      },
      web3WalletsSection: {
        title: 'Web3 Wallet',
        primaryButton: 'Web3 Wallet',
        destructiveActionTitle: 'Menghapus',
        destructiveActionSubtitle: 'Hapus dompet web3 ini dari akun Anda',
        destructiveAction: 'Lepaskan dompet',
      },
    },
    profilePage: {
      title: 'Memperbaharui profil',
      imageFormTitle: 'Gambar profil',
      imageFormSubtitle: 'Unggah gambar',
      imageFormDestructiveActionSubtitle: 'Hapus gambar',
      fileDropAreaTitle: 'Seret file di sini, atau ...',
      fileDropAreaAction: 'Pilih file',
      fileDropAreaHint: 'Unggah gambar jpg, png, gif, atau webp lebih kecil dari 10 MB',
      successMessage: 'Profil Anda telah diperbarui.',
    },
    usernamePage: {
      title: 'Perbarui Nama Pengguna',
      successMessage: 'Nama pengguna Anda telah diperbarui.',
    },
    emailAddressPage: {
      title: 'Tambahkan alamat email',
      emailCode: {
        formHint: 'Email yang berisi kode verifikasi akan dikirim ke alamat email ini.',
        formTitle: 'Kode verifikasi',
        formSubtitle: 'Masukkan kode verifikasi yang dikirim ke {{identifier}}',
        resendButton: 'Kirim ulang kode',
        successMessage: 'Alamat email {{identifier}} has telah ditambahkan ke akun Anda.',
      },
      emailLink: {
        formHint: 'An email containing a verification link will be sent to this email address.',
        formTitle: 'Verification link',
        formSubtitle: 'Click on the verification link in the email sent to {{identifier}}',
        resendButton: 'Resend link',
        successMessage: 'Alamat email {{identifier}} has telah ditambahkan ke akun Anda.',
      },
      removeResource: {
        title: 'Hapus alamat email',
        messageLine1: '{{identifier}} akan dihapus dari akun Anda.',
        messageLine2: 'Anda tidak akan lagi dapat masuk menggunakan alamat email ini.',
        successMessage: '{{emailAddress}} telah dihapus dari akun Anda.',
      },
    },
    phoneNumberPage: {
      title: 'Tambahkan nomor telepon',
      successMessage: '{{identifier}} telah ditambahkan ke akun Anda.',
      infoText: 'Pesan teks yang berisi tautan verifikasi akan dikirim ke nomor telepon ini.',
      infoText__secondary: 'Pesan dan tarif data dapat berlaku.',
      removeResource: {
        title: 'Hapus nomor telepon',
        messageLine1: '{{identifier}} akan dihapus dari akun Anda.',
        messageLine2: 'Anda tidak akan lagi dapat masuk menggunakan nomor telepon ini.',
        successMessage: '{{phoneNumber}} telah dihapus dari akun Anda.',
      },
    },
    connectedAccountPage: {
      title: 'Tambahkan akun yang terhubung',
      formHint: 'Pilih penyedia untuk menghubungkan akun Anda.',
      formHint__noAccounts: 'Tidak ada penyedia akun eksternal yang tersedia.',
      socialButtonsBlockButton: 'Hubungkan akun {{provider|titleize}}',
      successMessage: 'Penyedia telah ditambahkan ke akun Anda',
      removeResource: {
        title: 'Hapus akun yang terhubung',
        messageLine1: '{{identifier}} akan dihapus dari akun Anda.',
        messageLine2:
          'Anda tidak akan lagi dapat menggunakan akun yang terhubung ini dan fitur tergantung apa pun tidak lagi berfungsi.',
        successMessage: '{{connectedAccount}} telah dihapus dari akun Anda.',
      },
    },
    web3WalletPage: {
      title: 'Tambahkan dompet web3',
      subtitle__availableWallets: 'Pilih dompet Web3 untuk terhubung ke akun Anda.',
      subtitle__unavailableWallets: 'Tidak ada dompet web3 yang tersedia.',
      successMessage: 'Dompet telah ditambahkan ke akun Anda.',
      removeResource: {
        title: 'Lepaskan dompet web3',
        messageLine1: '{{identifier}} akan dihapus dari akun Anda.',
        messageLine2: 'Anda tidak akan lagi dapat masuk menggunakan dompet web3 ini.',
        successMessage: '{{web3Wallet}} telah dihapus dari akun Anda.',
      },
    },
    passwordPage: {
      title: 'Atur Kata Sandi',
      changePasswordTitle: 'Ganti kata sandi',
      successMessage: 'Kata sandi Anda telah ditetapkan.',
      changePasswordSuccessMessage: 'Kata sandi Anda telah diperbarui.',
      sessionsSignedOutSuccessMessage: 'Semua perangkat lain telah keluar.',
    },
    mfaPage: {
      title: 'Tambahkan verifikasi dua langkah',
      formHint: 'Pilih metode untuk ditambahkan.',
    },
    mfaTOTPPage: {
      title: 'Tambahkan Aplikasi Authenticator',
      verifyTitle: 'Kode verifikasi',
      verifySubtitle: 'Masukkan kode verifikasi yang dihasilkan oleh authenticator Anda',
      successMessage:
        'Verifikasi dua langkah sekarang diaktifkan.Saat masuk, Anda harus memasukkan kode verifikasi dari authenticator ini sebagai langkah tambahan.',
      authenticatorApp: {
        infoText__ableToScan:
          'Siapkan metode masuk baru di aplikasi authenticator Anda dan pindai kode QR berikut untuk menautkannya ke akun Anda.',
        infoText__unableToScan: 'Siapkan metode masuk baru di authenticator Anda dan masukkan kunci yang disediakan di bawah ini.',
        inputLabel__unableToScan1:
          'Pastikan kata sandi berbasis waktu atau satu kali diaktifkan, lalu selesaikan menautkan akun Anda.',
        inputLabel__unableToScan2:
          'Atau, jika authenticator Anda mendukung TOTP URI, Anda juga dapat menyalin URI lengkap.',
        buttonAbleToScan__nonPrimary: 'Pindai kode QR sebagai gantinya',
        buttonUnableToScan__nonPrimary: 'Tidak dapat memindai kode QR?',
      },
      removeResource: {
        title: 'Hapus verifikasi dua langkah',
        messageLine1: 'Kode verifikasi dari authenticator ini tidak akan lagi diperlukan saat masuk.',
        messageLine2: 'Akun Anda mungkin tidak aman.Apakah anda yakin ingin melanjutkan?',
        successMessage: 'Verifikasi dua langkah melalui aplikasi authenticator telah dihapus.',
      },
    },
    mfaPhoneCodePage: {
      title: 'Tambahkan verifikasi kode SMS',
      primaryButton__addPhoneNumber: 'Tambahkan nomor telepon',
      subtitle__availablePhoneNumbers: 'Pilih nomor telepon untuk mendaftar kode SMS verifikasi dua langkah.',
      subtitle__unavailablePhoneNumbers:
        'Tidak ada nomor telepon yang tersedia untuk mendaftar untuk Verifikasi Dua Langkah Kode SMS.',
      successMessage:
        'Kode SMS Verifikasi dua langkah sekarang diaktifkan untuk nomor telepon ini.Saat masuk, Anda harus memasukkan kode verifikasi yang dikirim ke nomor telepon ini sebagai langkah tambahan.',
      removeResource: {
        title: 'Hapus verifikasi dua langkah',
        messageLine1: '{{identifier}} tidak akan lagi menerima kode verifikasi saat masuk.',
        messageLine2: 'Akun Anda mungkin tidak aman.Apakah anda yakin ingin melanjutkan?',
        successMessage: 'Kode SMS Verifikasi dua langkah telah dihapus untuk {{mfaPhoneCode}}',
      },
    },
    backupCodePage: {
      title: 'Tambahkan verifikasi kode cadangan',
      title__codelist: 'Kode cadangan',
      subtitle__codelist: 'Simpan mereka dengan aman dan merahasiakannya.',
      infoText1: 'Kode cadangan akan diaktifkan untuk akun ini.',
      infoText2:
        'Rahasiakan kode cadangan dan simpan dengan aman.Anda dapat meregenerasi kode cadangan jika Anda curiga telah dikompromikan.',
      successSubtitle:
        'Anda dapat menggunakan salah satunya untuk masuk ke akun Anda, jika Anda kehilangan akses ke perangkat otentikasi Anda.',
      successMessage:
        'Kode cadangan sekarang diaktifkan.Anda dapat menggunakan salah satunya untuk masuk ke akun Anda, jika Anda kehilangan akses ke perangkat otentikasi Anda.Setiap kode hanya dapat digunakan sekali.',
      actionLabel__copy: 'Salin semua',
      actionLabel__copied: 'Disalin!',
      actionLabel__download: 'Unduh .txt',
      actionLabel__print: 'Mencetak',
    },
  },
  userButton: {
    action__manageAccount: 'Kelola akun',
    action__signOut: 'Keluar',
    action__signOutAll: 'Masuk dari semua akun',
    action__addAccount: 'Menambahkan akun',
  },
  organizationSwitcher: {
    personalWorkspace: 'Ruang kerja pribadi',
    notSelected: 'Tidak ada organisasi yang dipilih',
    action__createOrganization: 'Buat Organisasi',
    action__manageOrganization: 'Kelola Organisasi',
  },
  impersonationFab: {
    title: 'Masuk sebagai {{identifier}}',
    action__signOut: 'Keluar',
  },
  organizationProfile: {
    start: {
      headerTitle__members: 'Anggota',
      headerTitle__settings: 'Pengaturan',
      headerSubtitle__members: 'Lihat dan Kelola Anggota Organisasi',
      headerSubtitle__settings: 'Kelola Pengaturan Organisasi',
    },
    profilePage: {
      title: 'Profil Organisasi',
      subtitle: 'Kelola profil organisasi',
      successMessage: 'Organisasi telah diperbarui.',
      dangerSection: {
        title: 'Bahaya',
        leaveOrganization: {
          title: 'Tinggalkan Organisasi',
          messageLine1:
            'Apakah Anda yakin ingin meninggalkan organisasi ini?Anda akan kehilangan akses ke organisasi ini dan aplikasinya.',
          messageLine2: 'Tindakan ini permanen dan tidak dapat diubah.',
          successMessage: 'Anda telah meninggalkan organisasi.',
        },
      },
    },
    invitePage: {
      title: 'Undang Anggota',
      subtitle: 'Undang anggota baru ke organisasi ini',
      successMessage: 'Undangan berhasil dikirim',
      detailsTitle__inviteFailed: 'Undangan tidak dapat dikirim.Perbaiki yang berikut dan coba lagi:',
      formButtonPrimary__continue: 'Mengirim undangan',
    },
    membersPage: {
      detailsTitle__emptyRow: 'Tidak ada anggota untuk ditampilkan',
      action__invite: 'Mengundang',
      start: {
        headerTitle__active: 'Aktif',
        headerTitle__invited: 'Diundang',
      },
      activeMembersTab: {
        tableHeader__user: 'Pengguna',
        tableHeader__joined: 'Bergabung',
        tableHeader__role: 'Peran',
        tableHeader__actions: '',
        menuAction__remove: 'Hapus anggota',
      },
      invitedMembersTab: {
        tableHeader__invited: 'Diundang',
        menuAction__revoke: 'Tolak Undangan',
      },
    },
  },
  createOrganization: {
    title: 'Buat Organisasi',
    formButtonSubmit: 'Buat Organisasi',
    subtitle: 'Atur profil organisasi',
    invitePage: {
      formButtonReset: 'Lewati',
    },
  },
  unstable__errors: {
    form_identifier_not_found: '',
    form_password_pwned: '',
    form_username_invalid_length: '',
    form_param_format_invalid: '',
    form_password_length_too_short: '',
    form_param_nil: '',
    form_code_incorrect: '',
    form_password_incorrect: '',
    not_allowed_access: '',
    form_identifier_exists: '',
  },
  dates: {
    previous6Days: "Terakhir {{ date | weekday('en-US','long') }} pada {{ date | timeString('en-US') }}",
    lastDay: "Kemarin pada {{ date | timeString('en-US') }}",
    sameDay: "Hari ini pada {{ date | timeString('en-US') }}",
    nextDay: "Besok pada {{ date | timeString('en-US') }}",
    next6Days: "{{ date | weekday('en-US','long') }} pada {{ date | timeString('en-US') }}",
    numeric: "{{ date | numeric('en-US') }}",
  },
} as const;
