import type { LocalizationResource } from '@clerk/types';

const commonTexts = {
  signIn: {
    phoneCode: {
      title: 'Skontrolujte váš telefón',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací kód',
      formSubtitle: 'Zadajte overovací kód odoslaný na vaše telefónne číslo',
      resendButton: 'Znova odoslať kód',
    },
  },
} as const;

export const skSK: LocalizationResource = {
  locale: 'sk-SK',
  socialButtonsBlockButton: 'Pokračovať s {{provider|titleize}}',
  dividerText: 'alebo',
  formFieldLabel__emailAddress: 'Emailová adresa',
  formFieldLabel__emailAddresses: 'Emailové adresy',
  formFieldLabel__phoneNumber: 'Telefónne číslo',
  formFieldLabel__username: 'Užívateľské meno',
  formFieldLabel__emailAddress_phoneNumber: 'Emailová adresa alebo telefónne číslo',
  formFieldLabel__emailAddress_username: 'Emailová adresa alebo užívateľské meno',
  formFieldLabel__phoneNumber_username: 'Telefónne číslo alebo užívateľské meno',
  formFieldLabel__emailAddress_phoneNumber_username: 'Emailová adresa, telefónne číslo alebo užívateľské meno',
  formFieldLabel__password: 'Heslo',
  formFieldLabel__currentPassword: 'Súčasné heslo',
  formFieldLabel__newPassword: 'Nové heslo',
  formFieldLabel__confirmPassword: 'Potvrdiť heslo',
  formFieldLabel__signOutOfOtherSessions: 'Odhlásiť sa zo všetkých ostatných zariadení',
  formFieldLabel__firstName: 'Meno',
  formFieldLabel__lastName: 'Priezvisko',
  formFieldLabel__backupCode: 'Záložný kód',
  formFieldLabel__organizationName: 'Názov organizácie',
  formFieldLabel__organizationSlug: 'URL adresa',
  formFieldLabel__role: 'Rola',
  formFieldInputPlaceholder__emailAddress: '',
  formFieldInputPlaceholder__emailAddresses:
    'Zadajte alebo vložte jednu alebo viac emailových adries oddelených medzerou alebo čiarkou',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber: '',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__phoneNumber_username: '',
  formFieldInputPlaceholder__emailAddress_phoneNumber_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: '',
  formFieldInputPlaceholder__lastName: '',
  formFieldInputPlaceholder__backupCode: '',
  formFieldInputPlaceholder__organizationName: '',
  formFieldInputPlaceholder__organizationSlug: '',
  formFieldError__notMatchingPasswords: `Heslá sa nezhodujú.`,
  formFieldError__matchingPasswords: 'Heslá sa zhodujú.',
  formFieldAction__forgotPassword: 'Zabudli ste heslo?',
  formFieldHintText__optional: 'Voliteľné',
  formButtonPrimary: 'Pokračovať',
  signInEnterPasswordTitle: 'Zadajte svoje heslo',
  backButton: 'Späť',
  footerActionLink__useAnotherMethod: 'Použiť inú metódu',
  badge__primary: 'Hlavný',
  badge__thisDevice: 'Toto zariadenie',
  badge__userDevice: 'Zariadenie používateľa',
  badge__otherImpersonatorDevice: 'Iné zariadenie zástupcu',
  badge__default: 'Predvolené',
  badge__unverified: 'Nepotvrdené',
  badge__requiresAction: 'Vyžaduje akciu',
  badge__you: 'Vy',
  footerPageLink__help: 'Pomoc',
  footerPageLink__privacy: 'Ochrana súkromia',
  footerPageLink__terms: 'Podmienky',
  paginationButton__previous: 'Predchádzajúce',
  paginationButton__next: 'Ďalšie',
  paginationRowText__displaying: 'Zobrazuje sa',
  paginationRowText__of: 'z',
  membershipRole__admin: 'Správca',
  membershipRole__basicMember: 'Člen',
  membershipRole__guestMember: 'Host',
  signUp: {
    start: {
      title: 'Vytvorte si účet',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      actionText: 'Máte účet?',
      actionLink: 'Prihlásiť sa',
    },
    emailLink: {
      title: 'Overte svoj email',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací odkaz',
      formSubtitle: 'Použite overovací odkaz poslaný na vašu emailovú adresu',
      resendButton: 'Znovu poslať odkaz',
      verified: {
        title: 'Úspešne zaregistrované',
      },
      loading: {
        title: 'Prebieha registrácia...',
      },
      verifiedSwitchTab: {
        title: 'Email úspešne overený',
        subtitle: 'Vráťte sa do novootvoreného okna pre pokračovanie',
        subtitleNewTab: 'Vráťte sa do predchádzajúceho okna pre pokračovanie',
      },
    },
    emailCode: {
      title: 'Overte svoj email',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací kód',
      formSubtitle: 'Zadajte overovací kód poslaný na vašu emailovú adresu',
      resendButton: 'Znovu poslať kód',
    },
    phoneCode: {
      title: 'Overte svoj telefón',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací kód',
      formSubtitle: 'Zadajte overovací kód poslaný na vaše telefónne číslo',
      resendButton: 'Znovu poslať kód',
    },
    continue: {
      title: 'Vyplňte chýbajúce polia',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      actionText: 'Máte účet?',
      actionLink: 'Prihlásiť sa',
    },
  },
  signIn: {
    start: {
      title: 'Prihlásiť sa',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      actionText: 'Nemáte účet?',
      actionLink: 'Registrovať sa',
      actionLink__use_email: 'Použiť email',
      actionLink__use_phone: 'Použiť telefón',
      actionLink__use_username: 'Použiť užívateľské meno',
      actionLink__use_email_username: 'Použiť email alebo užívateľské meno',
    },
    password: {
      title: 'Zadajte svoje heslo',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      actionLink: 'Použiť inú metódu',
    },
    forgotPasswordAlternativeMethods: {
      title: 'Zabudli ste heslo?',
      label__alternativeMethods: 'Alebo sa prihláste pomocou inej metódy.',
      blockButton__resetPassword: 'Obnoviť heslo',
    },
    forgotPassword: {
      title_email: 'Skontrolujte svoj email',
      title_phone: 'Skontrolujte svoj telefón',
      subtitle: 'pre obnovenie hesla',
      formTitle: 'Overovací kód pre obnovenie hesla',
      formSubtitle_email: 'Zadajte kód zaslaný na vašu emailovú adresu',
      formSubtitle_phone: 'Zadajte kód zaslaný na vaše telefónne číslo',
      resendButton: 'Znovu poslať kód',
    },
    resetPassword: {
      title: 'Obnoviť heslo',
      formButtonPrimary: 'Obnoviť heslo',
      successMessage: 'Vaše heslo bolo úspešne zmenené. Prihlasujem vás, prosím počkajte okamžite.',
    },
    resetPasswordMfa: {
      detailsLabel: 'Pred obnovením hesla je potrebné overiť vašu totožnosť.',
    },
    emailCode: {
      title: 'Skontrolujte svoj email',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací kód',
      formSubtitle: 'Zadajte overovací kód zaslaný na vašu emailovú adresu',
      resendButton: 'Znovu poslať kód',
    },
    emailLink: {
      title: 'Skontrolujte svoj email',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: 'Overovací odkaz',
      formSubtitle: 'Použite overovací odkaz zaslaný na váš email',
      resendButton: 'Znovu poslať odkaz',
      unusedTab: {
        title: 'Môžete zatvoriť toto okno',
      },
      verified: {
        title: 'Úspešne prihlásené',
        subtitle: 'Čoskoro budete presmerovaní',
      },
      verifiedSwitchTab: {
        subtitle: 'Vráťte sa do pôvodného okna pre pokračovanie',
        titleNewTab: 'Prihlásené v inom okne',
        subtitleNewTab: 'Vráťte sa do novootvoreného okna pre pokračovanie',
      },
      loading: {
        title: 'Prihlasujem...',
        subtitle: 'Čoskoro budete presmerovaní',
      },
      failed: {
        title: 'Tento overovací odkaz je neplatný',
        subtitle: 'Vráťte sa do pôvodného okna pre pokračovanie.',
      },
      expired: {
        title: 'Tento overovací odkaz vypršal',
        subtitle: 'Vráťte sa do pôvodného okna pre pokračovanie.',
      },
    },
    phoneCode: { ...commonTexts.signIn.phoneCode },
    phoneCodeMfa: { ...commonTexts.signIn.phoneCode, subtitle: '' },
    totpMfa: {
      title: 'Dvojfaktorové overenie',
      subtitle: '',
      formTitle: 'Overovací kód',
      formSubtitle: 'Zadajte overovací kód vygenerovaný vašou autentifikačnou aplikáciou',
    },
    backupCodeMfa: {
      title: 'Zadajte záložný kód',
      subtitle: 'pre pokračovanie do {{applicationName}}',
      formTitle: '',
      formSubtitle: '',
    },
    alternativeMethods: {
      title: 'Použiť inú metódu',
      actionLink: 'Získať pomoc',
      blockButton__emailLink: 'Odoslať odkaz na email {{identifier}}',
      blockButton__emailCode: 'Odoslať overovací kód na email {{identifier}}',
      blockButton__phoneCode: 'Poslať SMS kód na telefónne číslo {{identifier}}',
      blockButton__password: 'Prihlásiť sa pomocou hesla',
      blockButton__totp: 'Použiť autentifikačnú aplikáciu',
      blockButton__backupCode: 'Použiť záložný kód',
      getHelp: {
        title: 'Získať pomoc',
        content:
          'Ak máte problémy s prihlásením do svojho účtu, kontaktujte nás emailom a pokúsime sa vám čo najskôr obnoviť prístup.',
        blockButton__emailSupport: 'Podpora cez email',
      },
    },
    noAvailableMethods: {
      title: 'Nie je možné sa prihlásiť',
      subtitle: 'Došlo k chybe',
      message: 'Nemožno pokračovať v prihlásení. Nie je k dispozícii žiadna dostupná autentifikačná metóda.',
    },
  },
  userProfile: {
    mobileButton__menu: 'Menu',
    formButtonPrimary__continue: 'Pokračovať',
    formButtonPrimary__finish: 'Dokončiť',
    formButtonReset: 'Zrušiť',
    start: {
      headerTitle__account: 'Účet',
      headerTitle__security: 'Bezpečnosť',
      headerSubtitle__account: 'Spravujte svoje údaje o účte',
      headerSubtitle__security: 'Spravujte svoje bezpečnostné nastavenia',
      profileSection: {
        title: 'Profil',
      },
      usernameSection: {
        title: 'Užívateľské meno',
        primaryButton__changeUsername: 'Zmeniť užívateľské meno',
        primaryButton__setUsername: 'Nastaviť užívateľské meno',
      },
      emailAddressesSection: {
        title: 'Emailové adresy',
        primaryButton: 'Pridať emailovú adresu',
        detailsTitle__primary: 'Hlavná emailová adresa',
        detailsSubtitle__primary: 'Táto emailová adresa je hlavná',
        detailsAction__primary: 'Dokončiť overenie',
        detailsTitle__nonPrimary: 'Nastaviť ako hlavnú emailovú adresu',
        detailsSubtitle__nonPrimary:
          'Nastavte túto emailovú adresu ako hlavnú pre prijímanie komunikácie týkajúcej sa vášho účtu.',
        detailsAction__nonPrimary: 'Nastaviť ako hlavnú',
        detailsTitle__unverified: 'Nepotvrdená emailová adresa',
        detailsSubtitle__unverified: 'Táto emailová adresa nebola overená a môže mať obmedzenú funkcionalitu',
        detailsAction__unverified: 'Dokončiť overenie',
        destructiveActionTitle: 'Odstrániť',
        destructiveActionSubtitle: 'Odstrániť túto emailovú adresu a odstrániť ju zo svojho účtu',
        destructiveAction: 'Odstrániť emailovú adresu',
      },
      phoneNumbersSection: {
        title: 'Telefónne čísla',
        primaryButton: 'Pridať telefónne číslo',
        detailsTitle__primary: 'Hlavné telefónne číslo',
        detailsSubtitle__primary: 'Toto telefónne číslo je hlavné',
        detailsAction__primary: 'Dokončiť overenie',
        detailsTitle__nonPrimary: 'Nastaviť ako hlavné telefónne číslo',
        detailsSubtitle__nonPrimary:
          'Nastavte toto telefónne číslo ako hlavné pre prijímanie komunikácie týkajúcej sa vášho účtu.',
        detailsAction__nonPrimary: 'Nastaviť ako hlavné',
        detailsTitle__unverified: 'Nepotvrdené telefónne číslo',
        detailsSubtitle__unverified: 'Toto telefónne číslo nebolo overené a môže mať obmedzenú funkcionalitu',
        detailsAction__unverified: 'Dokončiť overenie',
        destructiveActionTitle: 'Odstrániť',
        destructiveActionSubtitle: 'Odstrániť toto telefónne číslo a odstrániť ho zo svojho účtu',
        destructiveAction: 'Odstrániť telefónne číslo',
      },
      connectedAccountsSection: {
        title: 'Pripojené účty',
        primaryButton: 'Pripojiť účet',
        title__conectionFailed: 'Opakovať neúspešné pripojenie',
        title__connectionFailed: 'Opakovať neúspešné pripojenie',
        title__reauthorize: 'Vyžadované opätovné autorizovanie',
        subtitle__reauthorize:
          'Požadované oprávnenie bolo aktualizované a môžete mať obmedzenú funkcionalitu. Pre predchádzanie prípadným problémom autorizujte túto aplikáciu znovu.',
        actionLabel__conectionFailed: 'Skúsiť znovu',
        actionLabel__connectionFailed: 'Skúsiť znovu',
        actionLabel__reauthorize: 'Autorizovať teraz',
        destructiveActionTitle: 'Odstrániť',
        destructiveActionSubtitle: 'Odstrániť tento pripojený účet zo svojho účtu',
        destructiveActionAccordionSubtitle: 'Odstrániť pripojený účet',
      },
      passwordSection: {
        title: 'Heslo',
        primaryButton__changePassword: 'Zmeniť heslo',
        primaryButton__setPassword: 'Nastaviť heslo',
      },
      mfaSection: {
        title: 'Dvojfaktorová autentifikácia',
        primaryButton: 'Pridať dvojfaktorovú autentifikáciu',
        phoneCode: {
          destructiveActionTitle: 'Odstrániť',
          destructiveActionSubtitle: 'Odstrániť toto telefónne číslo zo spôsobov dvojfaktorovej autentifikácie',
          destructiveActionLabel: 'Odstrániť telefónne číslo',
          title__default: 'Predvolená metóda',
          title__setDefault: 'Nastaviť ako predvolenú metódu',
          subtitle__default:
            'Táto metóda bude použitá ako predvolená dvojfaktorová autentifikačná metóda pri prihlasovaní.',
          subtitle__setDefault:
            'Nastavte túto metódu ako predvolenú, tá sa použije ako predvolená dvojfaktorová autentifikačná metóda pri prihlasovaní.',
          actionLabel__setDefault: 'Nastaviť ako predvolené',
        },
        backupCodes: {
          headerTitle: 'Záložné kódy',
          title__regenerate: 'Obnoviť záložné kódy',
          subtitle__regenerate:
            'Získajte novú sadu zabezpečených záložných kódov. Predchádzajúce záložné kódy budú zmazané a nebudú použiteľné.',
          actionLabel__regenerate: 'Obnoviť kódy',
        },
        totp: {
          headerTitle: 'Aplikácia Authenticator',
          title: 'Predvolená metóda',
          subtitle: 'Táto metóda bude použitá ako predvolená dvojfaktorová autentifikačná metóda pri prihlasovaní.',
          destructiveActionTitle: 'Odstrániť',
          destructiveActionSubtitle: 'Odstrániť aplikáciu Authenticator zo spôsobov dvojfaktorovej autentifikácie',
          destructiveActionLabel: 'Odstrániť aplikáciu Authenticator',
        },
      },
      activeDevicesSection: {
        title: 'Aktívne zariadenia',
        primaryButton: 'Aktívne zariadenia',
        detailsTitle: 'Aktuálne zariadenie',
        detailsSubtitle: 'Toto je zariadenie, ktoré práve používate',
        destructiveActionTitle: 'Odhlásiť',
        destructiveActionSubtitle: 'Odhlásiť sa zo svojho účtu na tomto zariadení',
        destructiveAction: 'Odhlásiť sa zo zariadenia',
      },
      web3WalletsSection: {
        title: 'Web3 peňaženky',
        primaryButton: 'Web3 peňaženky',
        destructiveActionTitle: 'Odstrániť',
        destructiveActionSubtitle: 'Odstrániť túto Web3 peňaženku zo svojho účtu',
        destructiveAction: 'Odstrániť peňaženku',
      },
    },
    profilePage: {
      title: 'Aktualizovať profil',
      imageFormTitle: 'Profilový obrázok',
      imageFormSubtitle: 'Nahrať obrázok',
      imageFormDestructiveActionSubtitle: 'Odstrániť obrázok',
      fileDropAreaTitle: 'Presuňte súbor sem alebo...',
      fileDropAreaAction: 'Vybrať súbor',
      fileDropAreaHint: 'Nahrajte obrázok vo formátoch JPG, PNG, GIF alebo WEBP s veľkosťou menšou než 10 MB',
      successMessage: 'Váš profil bol aktualizovaný.',
    },
    usernamePage: {
      title: 'Aktualizovať užívateľské meno',
      successMessage: 'Vaše užívateľské meno bolo aktualizované.',
    },
    emailAddressPage: {
      title: 'Pridať e-mailovú adresu',
      emailCode: {
        formHint: 'Na túto e-mailovú adresu bude odoslaný overovací kód.',
        formTitle: 'Overovací kód',
        formSubtitle: 'Zadajte overovací kód zaslaný na adresu {{identifier}}',
        resendButton: 'Znovu odoslať kód',
        successMessage: 'E-mailová adresa {{identifier}} bola pridaná k vášmu účtu.',
      },
      emailLink: {
        formHint: 'Na túto e-mailovú adresu bude odoslaný overovací odkaz.',
        formTitle: 'Overovací odkaz',
        formSubtitle: 'Kliknite na overovací odkaz v e-maile zaslanom na adresu {{identifier}}',
        resendButton: 'Znovu odoslať odkaz',
        successMessage: 'E-mailová adresa {{identifier}} bola pridaná k vášmu účtu.',
      },
      removeResource: {
        title: 'Odstrániť e-mailovú adresu',
        messageLine1: '{{identifier}} bude odstránená z tohto účtu.',
        messageLine2: 'Nebudete sa môcť prihlásiť pomocou tejto e-mailovej adresy.',
        successMessage: '{{emailAddress}} bola odobraná z vášho účtu.',
      },
    },
    phoneNumberPage: {
      title: 'Pridať telefónne číslo',
      successMessage: '{{identifier}} bolo pridané k vášmu účtu.',
      infoText: 'Na toto telefónne číslo bude odoslaná textová správa obsahujúca overovací odkaz.',
      infoText__secondary: 'Mohú sa vzťahovať poplatky za správy a dáta.',
      removeResource: {
        title: 'Odstrániť telefónne číslo',
        messageLine1: '{{identifier}} bude odobrané z tohto účtu.',
        messageLine2: 'Nebudete sa môcť prihlásiť pomocou tohto telefónneho čísla.',
        successMessage: '{{phoneNumber}} bolo odstránené z vášho účtu.',
      },
    },
    connectedAccountPage: {
      title: 'Pridať pripojený účet',
      formHint: 'Vyberte poskytovateľa pre pripojenie vášho účtu.',
      formHint__noAccounts: 'Nie sú k dispozícii žiadni dostupní externí poskytovatelia účtov.',
      socialButtonsBlockButton: 'Pripojiť účet {{provider|titleize}}',
      successMessage: 'Poskytovateľ bol pridaný k vášmu účtu.',
      removeResource: {
        title: 'Odstrániť pripojený účet',
        messageLine1: '{{identifier}} bude odobraný z tohto účtu.',
        messageLine2: 'Nebudete už môcť používať tento pripojený účet a akékoľvek závislé funkcie prestanú fungovať.',
        successMessage: '{{connectedAccount}} bol odstránený z vášho účtu.',
      },
    },
    web3WalletPage: {
      title: 'Pridať web3 peňaženku',
      subtitle__availableWallets: 'Vyberte web3 peňaženku na pripojenie k vášmu účtu.',
      subtitle__unavailableWallets: 'Nie sú k dispozícii žiadne dostupné web3 peňaženky.',
      successMessage: 'Peňaženka bola pridaná k vášmu účtu.',
      removeResource: {
        title: 'Odstrániť web3 peňaženku',
        messageLine1: '{{identifier}} bude odobraná z tohto účtu.',
        messageLine2: 'Nebudete sa už môcť prihlásiť pomocou tejto web3 peňaženky.',
        successMessage: '{{web3Wallet}} bola odstránená z vášho účtu.',
      },
    },
    passwordPage: {
      title: 'Nastaviť heslo',
      changePasswordTitle: 'Zmeniť heslo',
      successMessage: 'Vaše heslo bolo nastavené.',
      changePasswordSuccessMessage: 'Vaše heslo bolo aktualizované.',
      sessionsSignedOutSuccessMessage: 'Všetky ostatné zariadenia boli odhlásené.',
    },
    mfaPage: {
      title: 'Pridať dvojfaktorové overenie',
      formHint: 'Vyberte spôsob pridania.',
    },
    mfaTOTPPage: {
      title: 'Pridať aplikáciu pre overovanie',
      verifyTitle: 'Overovací kód',
      verifySubtitle: 'Zadajte overovací kód generovaný vašou aplikáciou pre overovanie.',
      successMessage:
        'Dvojfaktorové overovanie je teraz povolené. Pri prihlásení budete musieť zadať overovací kód z tejto aplikácie pre overovanie ako ďalší krok.',
      authenticatorApp: {
        infoText__ableToScan:
          'Nastavte novú metódu prihlásenia vo vašej aplikácii pre overovanie a naskenujte nasledujúci QR kód, aby ste ju spojili so svojím účtom.',
        infoText__unableToScan:
          'Nastavte novú metódu prihlásenia vo vašej aplikácii pre overovanie a zadajte nižšie uvedený kľúč.',
        inputLabel__unableToScan1:
          'Uistite sa, že je povolené časovo závislé alebo jednorázové heslo a dokončite spojenie vášho účtu.',
        inputLabel__unableToScan2:
          'Alternatívne, ak vaša aplikácia pre overovanie podporuje TOTP URI, môžete tiež skopírovať celý URI.',
        buttonAbleToScan__nonPrimary: 'Namiesto toho naskenujte QR kód',
        buttonUnableToScan__nonPrimary: 'Nemôžete naskenovať QR kód?',
      },
      removeResource: {
        title: 'Odstrániť dvojfaktorové overovanie',
        messageLine1: 'Pri prihlasovaní už nebudú vyžadované overovacie kódy z tejto aplikácie pre overovanie.',
        messageLine2: 'Váš účet nemusí byť tak bezpečný. Naozaj chcete pokračovať?',
        successMessage: 'Dvojfaktorové overovanie pomocou aplikácie pre overovanie bolo odstránené.',
      },
    },
    mfaPhoneCodePage: {
      title: 'Pridať overovanie pomocou SMS kódu',
      primaryButton__addPhoneNumber: 'Pridať telefónne číslo',
      subtitle__availablePhoneNumbers:
        'Vyberte telefónne číslo pre registráciu dvojfaktorového overovania pomocou SMS kódu.',
      subtitle__unavailablePhoneNumbers:
        'Nie sú k dispozícii žiadne dostupné telefónne čísla pre registráciu dvojfaktorového overovania pomocou SMS kódu.',
      successMessage:
        'Dvojfaktorové overovanie pomocou SMS kódu je teraz povolené pre toto telefónne číslo. Pri prihlásení budete musieť zadať overovací kód zaslaný na toto telefónne číslo ako ďalší krok.',
      removeResource: {
        title: 'Odstrániť dvojfaktorové overovanie',
        messageLine1: '{{identifier}} už nebude dostávať overovacie kódy pri prihlasovaní.',
        messageLine2: 'Váš účet nemusí byť tak bezpečný. Naozaj chcete pokračovať?',
        successMessage: 'Dvojfaktorové overovanie pomocou SMS kódu bolo odstránené pre {{mfaPhoneCode}}',
      },
    },
    backupCodePage: {
      title: 'Pridať overovanie pomocou záložných kódov',
      title__codelist: 'Záložné kódy',
      subtitle__codelist: 'Uchovávajte ich bezpečne a tajne.',
      infoText1: 'Pre tento účet budú povolené záložné kódy.',
      infoText2:
        'Záložné kódy uchovávajte tajne a bezpečne. Môžete vygenerovať nové záložné kódy, ak máte podozrenie, že boli skompromitované.',
      successSubtitle:
        'Použite jeden z týchto kódov na prihlásenie do vášho účtu, ak stratíte prístup k vášmu overovaciemu zariadeniu.',
      successMessage:
        'Záložné kódy sú teraz povolené. Ak stratíte prístup k vášmu overovaciemu zariadeniu, môžete použiť jeden z týchto kódov na prihlásenie do vášho účtu. Každý kód možno použiť iba raz.',
      actionLabel__copy: 'Kopírovať všetko',
      actionLabel__copied: 'Skopírované!',
      actionLabel__download: 'Stiahnuť .txt',
      actionLabel__print: 'Vytlačiť',
    },
  },
  userButton: {
    action__manageAccount: 'Spravovať účet',
    action__signOut: 'Odhlásiť sa',
    action__signOutAll: 'Odhlásiť sa zo všetkých účtov',
    action__addAccount: 'Pridať účet',
  },
  organizationSwitcher: {
    personalWorkspace: 'Osobný pracovný priestor',
    notSelected: 'Nie je vybraná žiadna organizácia',
    action__createOrganization: 'Vytvoriť organizáciu',
    action__manageOrganization: 'Spravovať organizáciu',
  },
  impersonationFab: {
    title: 'Prihlásený(á) ako {{identifier}}',
    action__signOut: 'Odhlásiť sa',
  },
  organizationProfile: {
    start: {
      headerTitle__members: 'Členovia',
      headerTitle__settings: 'Nastavenia',
      headerSubtitle__members: 'Zobraziť a spravovať členov organizácie',
      headerSubtitle__settings: 'Spravovať nastavenia organizácie',
    },
    profilePage: {
      title: 'Profil organizácie',
      subtitle: 'Spravovať profil organizácie',
      successMessage: 'Organizácia bola aktualizovaná.',
      dangerSection: {
        title: 'Upozornenie',
        leaveOrganization: {
          title: 'Opustiť organizáciu',
          messageLine1:
            'Naozaj chcete opustiť túto organizáciu? Stratíte prístup k tejto organizácii a jej aplikáciám.',
          messageLine2: 'Táto akcia je trvalá a nezvratná.',
          successMessage: 'Opustili ste organizáciu.',
        },
      },
    },
    invitePage: {
      title: 'Pozvať členov',
      subtitle: 'Pozvať nových členov do tejto organizácie',
      successMessage: 'Pozvánky boli úspešne odoslané.',
      detailsTitle__inviteFailed: 'Pozvánky sa nepodarilo odoslať. Opravte nasledujúce a skúste to znovu:',
      formButtonPrimary__continue: 'Odoslať pozvánky',
    },
    membersPage: {
      detailsTitle__emptyRow: 'Žiadni členovia na zobrazenie',
      action__invite: 'Pozvať',
      start: {
        headerTitle__active: 'Aktívni',
        headerTitle__invited: 'Pozvaní',
      },
      activeMembersTab: {
        tableHeader__user: 'Užívateľ',
        tableHeader__joined: 'Pripojil sa',
        tableHeader__role: 'Rola',
        tableHeader__actions: '',
        menuAction__remove: 'Odstrániť člena',
      },
      invitedMembersTab: {
        tableHeader__invited: 'Pozvaní',
        menuAction__revoke: 'Zrušiť pozvanie',
      },
    },
  },
  createOrganization: {
    title: 'Vytvoriť organizáciu',
    formButtonSubmit: 'Vytvoriť organizáciu',
    subtitle: 'Nastaviť profil organizácie',
    invitePage: {
      formButtonReset: 'Preskočiť',
    },
  },
  unstable__errors: {
    form_identifier_exists__email_address: undefined,
    form_identifier_exists__phone_number: undefined,
    form_identifier_exists__username: undefined,
    form_identifier_not_found: '',
    form_password_pwned: 'Toto heslo bolo nájdené v rámci úniku dát a nemôže byť použité, prosím zvoľte iné heslo.',
    form_username_invalid_length: '',
    form_username_invalid_character: '',
    form_param_format_invalid: '',
    form_password_length_too_short: '',
    form_param_nil: '',
    form_code_incorrect: '',
    form_password_incorrect: '',
    not_allowed_access: '',
    form_identifier_exists: '',
    form_password_validation_failed: 'Nesprávne heslo',
    form_password_not_strong_enough: 'Vaše heslo nie je dostatočne silné.',
    form_password_size_in_bytes_exceeded:
      'Vaše heslo prekročilo maximálny povolený počet bytov, prosím skráťte ho alebo odstráňte niektoré špeciálne znaky.',
    passwordComplexity: {
      sentencePrefix: 'Vaše heslo musí obsahovať',
      minimumLength: '{{length}} alebo viac znakov',
      maximumLength: 'menej ako {{length}} znakov',
      requireNumbers: 'číslicu',
      requireLowercase: 'malé písmeno',
      requireUppercase: 'veľké písmeno',
      requireSpecialCharacter: 'špeciálny znak',
    },
    zxcvbn: {
      notEnough: 'Vaše heslo není dostatočne silné.',
      couldBeStronger: 'Vaše heslo funguje, ale mohlo by byť silnejšie. Skúste pridať viac znakov.',
      goodPassword: 'Dobrá práca. Toto je vynikajúce heslo.',
      warnings: {
        straightRow: 'Rady klávesnice sú ľahko uhádnuteľné.',
        keyPattern: 'Krátke vzory na klávesnici sú ľahko uhádnuteľné.',
        simpleRepeat: 'Opakujúce sa znaky ako "aaa" sú ľahko uhádnuteľné.',
        extendedRepeat: 'Opakujúce sa vzory znakov ako "abcabcabc" sú ľahko uhádnuteľné.',
        sequences: 'Bežné sekvencie znakov ako "abc" sú ľahko uhádnuteľné.',
        recentYears: 'Nedávne roky sú ľahko uhádnuteľné.',
        dates: 'Dátum je ľahko uhádnuteľný.',
        topTen: 'Toto je často používané heslo.',
        topHundred: 'Toto je často používané heslo.',
        common: 'Toto je bežne používané heslo.',
        similarToCommon: 'Toto je podobné bežne používanému heslu.',
        wordByItself: 'Samostatné slová sú ľahko uhádnuteľné.',
        namesByThemselves: 'Samostatné mená alebo priezviská sú ľahko uhádnuteľné.',
        commonNames: 'Bežné mená a priezviská sú ľahko uhádnuteľné.',
        userInputs: 'Heslo by nemalo obsahovať osobné alebo stránkou súvisiace údaje.',
        pwned: 'Vaše heslo bolo odhalené pri úniku údajov na internete.',
      },
      suggestions: {
        l33t: "Vyhnite sa predvídateľným náhradám písmen, napríklad '@' miesto 'a'.",
        reverseWords: 'Vyhnite sa obráteným pravopisom bežných slov.',
        allUppercase: 'Použite veľké písmena len u niektorých, nie všetkých písmen.',
        capitalization: 'Písmená píšte s veľkým počiatočným písmenom a viac ako len prvým písmenom.',
        dates: 'Vyhnite sa dátumom a rokom, ktoré sú s vami spojené.',
        recentYears: 'Vyhnite sa nedávnym rokom.',
        associatedYears: 'Vyhnite sa rokom, ktoré sú s vami spojené.',
        sequences: 'Vyhnite sa bežným sekvenciám znakov.',
        repeated: 'Vyhnite sa opakujúcim sa slovám a znakom.',
        longerKeyboardPattern: 'Použite dlhšie vzory na klávesnici a menite smer písania viackrát.',
        anotherWord: 'Pridajte viac slov, ktoré nie sú tak bežné.',
        useWords: 'Použite viac slov, ale vyhnite sa bežným frázam.',
        noNeed: 'Môžete vytvárať silné heslá aj bez použitia symbolov, čísel alebo veľkých písmen.',
        pwned: 'Ak používate toto heslo aj niekde inde, mali by ste ho zmeniť.',
      },
    },
  },
  dates: {
    previous6Days: "Minulý {{ date | weekday('sk-SK','long') }} o {{ date | timeString('sk-SK') }}",
    lastDay: "Včera o {{ date | timeString('sk-SK') }}",
    sameDay: "Dnes o {{ date | timeString('sk-SK') }}",
    nextDay: "Zajtra o {{ date | timeString('sk-SK') }}",
    next6Days: "Příští {{ date | weekday('sk-SK','long') }} o {{ date | timeString('sk-SK') }}",
    numeric: "{{ date | numeric('sk-SK') }}",
  },
} as const;
