import type { LocalizationResource } from '@clerk/types';

const commonTexts = {
  signIn: {
    phoneCode: {
      title: 'Telefonunuza göz atın',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama kodu',
      formSubtitle: 'Telefonunuza gönderdiğimiz doğrulama kodunu giriniz',
      resendButton: 'Tekrar gönder',
    },
  },
} as const;

export const trTR: LocalizationResource = {
  locale: 'tr-TR',
  socialButtonsBlockButton: '{{provider|titleize}} ile giriş yapın',
  dividerText: 'veya',
  formFieldLabel__emailAddress: 'E-posta adresi',
  formFieldLabel__emailAddresses: 'E-posta adresleri',
  formFieldLabel__phoneNumber: 'Telefon numarası',
  formFieldLabel__username: 'Kullanıcı adı',
  formFieldLabel__emailAddress_username: 'E-posta adresi veya kullanıcı adı',
  formFieldLabel__password: 'Şifre',
  formFieldLabel__currentPassword: 'Mevcut şifre',
  formFieldLabel__newPassword: 'Yeni şifre',
  formFieldLabel__confirmPassword: 'Şifreyi onayla',
  formFieldLabel__signOutOfOtherSessions: 'Diğer cihazlardaki oturumlardan çık',
  formFieldLabel__firstName: 'Ad',
  formFieldLabel__lastName: 'Soyad',
  formFieldLabel__backupCode: 'Yedekleme kodu',
  formFieldLabel__organizationName: 'Organizasyon adı',
  formFieldLabel__organizationSlug: "Organizasyon slug'ı",
  formFieldLabel__role: 'Rol',
  formFieldInputPlaceholder__emailAddress: '',
  formFieldInputPlaceholder__emailAddresses:
    'Boşluklar veya virgüllerle ayırarak bir veya daha fazla e-posta adresi girin veya yapıştırın',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: '',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: '',
  formFieldInputPlaceholder__lastName: '',
  formFieldInputPlaceholder__backupCode: '',
  formFieldInputPlaceholder__organizationName: '',
  formFieldInputPlaceholder__organizationSlug: '',
  formFieldError__notMatchingPasswords: `Şifreler eşleşmiyor.`,
  formFieldError__matchingPasswords: 'Şifreler eşleşiyor.',
  formFieldAction__forgotPassword: 'Şifremi unuttum',
  formFieldHintText__optional: 'İsteğe bağlı',
  formButtonPrimary: 'İleri',
  signInEnterPasswordTitle: 'Şifrenizi girin',
  backButton: 'Geri',
  footerActionLink__useAnotherMethod: 'Başka bir yöntem kullan',
  badge__primary: 'Birincil',
  badge__thisDevice: 'Bu cihaz',
  badge__userDevice: 'Kullanıcı cihazı',
  badge__otherImpersonatorDevice: 'Farklı bir kılıkçı cihazı',
  badge__default: 'Varsayılan',
  badge__unverified: 'Doğrulanmamış',
  badge__requiresAction: 'Eylem gerekli',
  badge__you: 'Siz',
  footerPageLink__help: 'Yardım',
  footerPageLink__privacy: 'Gizlilik',
  footerPageLink__terms: 'Şartlar',
  paginationButton__previous: 'Geri',
  paginationButton__next: 'İleri',
  paginationRowText__displaying: 'Sayfa bilgisi:',
  paginationRowText__of: '-',
  membershipRole__admin: 'Admin',
  membershipRole__basicMember: 'Üye',
  membershipRole__guestMember: 'Misafir',
  signUp: {
    start: {
      title: 'Hesap oluştur',
      subtitle: '{{applicationName}} ile devam etmek için',
      actionText: 'Hesabınız var mı?',
      actionLink: 'Giriş yap',
    },
    emailLink: {
      title: 'E-posta adresinizi doğrulayın',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama bağlantısı',
      formSubtitle: 'E-posta adresinize gönderdiğimiz doğrulama bağlantısına tıklayın',
      resendButton: 'Tekrar gönder',
      verified: {
        title: 'Başarıyla doğrulandı',
      },
      loading: {
        title: 'Giriş yapılıyor...',
      },
      verifiedSwitchTab: {
        title: 'E-posta adresiniz başarıyla doğrulandı',
        subtitle: 'Devam etmek için yeni açılmış sekmeye dönün',
        subtitleNewTab: 'Devam etmek için önceki sekmeye dönün',
      },
    },
    emailCode: {
      title: 'E-posta adresinizi doğrulayın',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama kodu',
      formSubtitle: 'E-posta adresinize gönderdiğimiz doğrulama kodunu giriniz',
      resendButton: 'Kodu tekrar gönder',
    },
    phoneCode: {
      title: 'Telefon numaranızı doğrulayın',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama kodu',
      formSubtitle: 'Telefon numaranıza gönderdiğimiz doğrulama kodunu giriniz',
      resendButton: 'Kodu tekrar gönder',
    },
    continue: {
      title: 'Eksik bilgileri tamamlayın',
      subtitle: '{{applicationName}} ile devam etmek için',
      actionText: 'Hesabınız var mı?',
      actionLink: 'Giriş yap',
    },
  },
  signIn: {
    start: {
      title: 'Giriş yap',
      subtitle: '{{applicationName}} ile devam etmek için',
      actionText: 'Hesabınız yok mu?',
      actionLink: 'Kayıt ol',
      actionLink__use_email: 'E-posta kullan',
      actionLink__use_phone: 'Telefon kullan',
      actionLink__use_username: 'Kullanıcı adı kullan',
      actionLink__use_email_username: 'E-posta veya kullanıcı adı kullan',
    },
    password: {
      title: 'Şifrenizi girin',
      subtitle: '{{applicationName}} ile devam etmek için',
      actionLink: 'Başka bir yöntem kullan',
    },
    forgotPasswordAlternativeMethods: {
      title: 'Şifremi unuttum',
      label__alternativeMethods: 'Veya başka bir yöntem kullanın:',
      blockButton__resetPassword: 'Şifremi sıfırla',
    },
    forgotPassword: {
      title_email: 'E-posta kutunuzu kontrol edin',
      title_phone: 'SMS kutunuzu kontrol edin',
      subtitle: 'şifrenizi sıfırlamak için',
      formTitle: 'Şifre sıfırlama kodu',
      formSubtitle_email: 'E-posta adresinize gönderdiğimiz kodu girin',
      formSubtitle_phone: 'Telefonunuza gönderdiğimiz kodu girin',
      resendButton: 'Tekrar gönder',
    },
    resetPassword: {
      title: 'Şifre sıfırlama',
      formButtonPrimary: 'Şifremi sıfırla',
      successMessage: 'Şifreniz başarıyla sıfırlandı. Oturumunuz açılıyor...',
    },
    resetPasswordMfa: {
      detailsLabel: 'Şifrenizi sıfırlamadan önce kimliğinizi doğrulamamız gerekiyor.',
    },
    emailCode: {
      title: 'E-posta kutunuzu kontrol edin',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama kodu',
      formSubtitle: 'E-posta adresinize gönderdiğimiz doğrulama kodunu giriniz',
      resendButton: 'Kodu tekrar gönder',
    },
    emailLink: {
      title: 'E-posta kutunuzu kontrol edin',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: 'Doğrulama bağlantısı',
      formSubtitle: 'E-posta adresinize gönderdiğimiz doğrulama bağlantısına tıklayın',
      resendButton: 'Tekrar gönder',
      unusedTab: {
        title: 'Bu sekmeyi kapatabilirsiniz',
      },
      verified: {
        title: 'Başarıyla giriş yapıldı',
        subtitle: 'Yönlediriliyorsunuz...',
      },
      verifiedSwitchTab: {
        subtitle: 'Devam etmek için en baştaki sekmeye dönün',
        titleNewTab: 'Farklı bir sekmede giriş yapıldı',
        subtitleNewTab: 'Devam etmek için yeni açılmış sekmeye dönün',
      },
      loading: {
        title: 'Giriş yapılıyor...',
        subtitle: 'Yönlediriliyorsunuz...',
      },
      failed: {
        title: 'Bu doğrulama bağlantısı geçersiz',
        subtitle: 'Devam etmek için en baştaki sekmeye dönün',
      },
      expired: {
        title: 'Bu doğruşlama bağlantısının süresi dolmuş',
        subtitle: 'Devam etmek için en baştaki sekmeye dönün',
      },
    },
    phoneCode: { ...commonTexts.signIn.phoneCode },
    phoneCodeMfa: { ...commonTexts.signIn.phoneCode, subtitle: '' },
    totpMfa: {
      title: 'İki aşamalı doğrulama',
      subtitle: '',
      formTitle: 'Doğrulama kodu',
      formSubtitle: 'Authenticator uygulamanızda oluşturulan kodu girin',
    },
    backupCodeMfa: {
      title: 'Yedekleme kodu girişi',
      subtitle: '{{applicationName}} ile devam etmek için',
      formTitle: '',
      formSubtitle: '',
    },
    alternativeMethods: {
      title: 'Farklı bir yöntem kullan',
      actionLink: 'Yardım al',
      blockButton__emailLink: '{{identifier}} adresine doğrulama bağlantısı gönder',
      blockButton__emailCode: '{{identifier}} adresine doğrulama kodu gönder',
      blockButton__phoneCode: '{{identifier}} numarasına doğrulama kodu gönder',
      blockButton__password: 'Şifreyle giriş yap',
      blockButton__totp: 'Authenticator uygulaması kullan',
      blockButton__backupCode: 'Yedekleme kodu kullan',
      getHelp: {
        title: 'Yardım al',
        content: `Eğer hesabınıza giriş yapmakta zorluk yaşıyorsanız, hesabınıza erişiminizi sağlayabilmemiz için bize bir e-posta gönderin ve size yardımcı olalım.`,
        blockButton__emailSupport: 'E-posta desteği',
      },
    },
    noAvailableMethods: {
      title: 'Giriş yapılamıyor',
      subtitle: 'Bir hata oluştu',
      message: 'Hesabınızda giriş yapmak için kullanabileceğiniz bir yöntem bulunmuyor.',
    },
  },
  userProfile: {
    mobileButton__menu: 'Menü',
    formButtonPrimary__continue: 'İlerle',
    formButtonPrimary__finish: 'Bitir',
    formButtonReset: 'İptal',
    start: {
      headerTitle__account: 'Hesap',
      headerTitle__security: 'Güvenlik',
      profileSection: {
        title: 'Profil',
      },
      usernameSection: {
        title: 'Kullanıcı adı',
        primaryButton__changeUsername: 'Kullanıcı adını değiştir',
        primaryButton__setUsername: 'Güncelle',
      },
      emailAddressesSection: {
        title: 'E-posta adresleri',
        primaryButton: 'E-posta adresi ekle',
        detailsTitle__primary: 'Birincil e-posta adresi',
        detailsSubtitle__primary: 'Bu e-posta adresi birincil e-posta adresidir',
        detailsAction__primary: 'Doğrulamayı tamamla',
        detailsTitle__nonPrimary: 'Birincil yap',
        detailsSubtitle__nonPrimary: 'Hesabınızla ilgili iletiler birincil e-posta adresinize gönderilir.',
        detailsAction__nonPrimary: 'Birincil e-posta adresi yap',
        detailsTitle__unverified: 'Doğrulanmamış e-posta adresi',
        detailsSubtitle__unverified: 'Bu e-posta adresi doğrulanmamıştır ve işlevselliği sınırlı olabilir',
        detailsAction__unverified: 'Doğrulamayı tamamla',
        destructiveActionTitle: 'Kaldır',
        destructiveActionSubtitle: 'Bu e-posta adresini silin ve hesabınızdan kaldırın',
        destructiveAction: 'E-posta adresini kaldır',
      },
      phoneNumbersSection: {
        title: 'Telefon numaraları',
        primaryButton: 'Telefon numarası ekle',
        detailsTitle__primary: 'Birincil telefon numarası',
        detailsSubtitle__primary: 'Bu telefon numarası birincil telefon numarasıdır',
        detailsAction__primary: 'Doğrulamayı tamamla',
        detailsTitle__nonPrimary: 'Birincil telefon numarası olarak ayarla',
        detailsSubtitle__nonPrimary: 'Hesabınızla ilgili iletiler birincil telefon numaranıza gönderilir.',
        detailsAction__nonPrimary: 'Birincil yap',
        detailsTitle__unverified: 'Doğrulanmamış telefon numarası',
        detailsSubtitle__unverified: 'Bu telefon numarası doğrulanmamıştır ve işlevselliği sınırlı olabilir',
        detailsAction__unverified: 'Doğrulamayı tamamla',
        destructiveActionTitle: 'Kaldır',
        destructiveActionSubtitle: 'Bu telefon numarasını silin ve hesabınızdan kaldırın',
        destructiveAction: 'Telefon numarasını kaldır',
      },
      connectedAccountsSection: {
        title: 'Bağlı hesaplar',
        primaryButton: 'Hesap bağla',
        title__connectionFailed: 'Yeniden bağlanmayı dene',
        title__reauthorize: 'Yeniden bir yetkilendirme gerekiyor',
        subtitle__reauthorize:
          'Gerekli kapsamlar güncellendi. Bir süreliğine işlevsellikte sınırlanmalar görülebilir. Herhangi bir sorun yaşamamak için bu uygulamayı yeniden yetkilendirin',
        actionLabel__connectionFailed: 'Yeniden dene',
        actionLabel__reauthorize: 'Yetkilendir',
        destructiveActionTitle: 'Kaldır',
        destructiveActionSubtitle: 'Bağlı hesabı kaldır',
        destructiveActionAccordionSubtitle: 'Bağlı hesabı kaldır',
      },
      passwordSection: {
        title: 'Şifre',
        primaryButton__changePassword: 'Şifreyi değiştir',
        primaryButton__setPassword: 'Şifreyi güncelle',
      },
      mfaSection: {
        title: 'İki aşamalı doğrulama',
        primaryButton: 'İki aşamalı doğrulama ekle',
        phoneCode: {
          destructiveActionTitle: 'Kaldır',
          destructiveActionSubtitle: 'Bu telefon numarasını iki aşamalı doğrulama yöntemlerinden kaldırın',
          destructiveActionLabel: 'Telefon numarasını kaldır',
          title__default: 'Varsayılan faktör',
          title__setDefault: 'Varsayılan faktör olarak ayarla',
          subtitle__default: 'Bu faktör iki aşamalı doğrulama yöntemleri arasında varsayılan olarak kullanılacaktır.',
          subtitle__setDefault:
            'Bu faktörü giriş yaparkenki varsayılan iki aşamalı doğrulama yöntemi olarak ayarlayın.',
          actionLabel__setDefault: 'Varsayılan olarak ayarla',
        },
        backupCodes: {
          headerTitle: 'Yedekleme kodları',
          title__regenerate: 'Yedekleme kodlarını yenile',
          subtitle__regenerate:
            'Yeni bir dizi güvenli yedekleme kodu alın. Önceki yedekleme kodları silinecek ve kullanılamayacaktır.',
          actionLabel__regenerate: 'Kodları yenile',
        },
        totp: {
          headerTitle: 'Authenticator uygulaması',
          title: 'Varsayılan faktör',
          subtitle: 'Bu faktör giriş yaparkenki varsayılan iki aşamalı doğrulama yöntemi olarak kullanılacaktır.',
          destructiveActionTitle: 'Kaldır',
          destructiveActionSubtitle: 'Bu authenticator uygulamasını iki aşamalı doğrulama yöntemlerinden kaldır',
          destructiveActionLabel: 'Authenticator uygulamasını kaldır',
        },
      },
      activeDevicesSection: {
        title: 'Aktif cihazlar',
        primaryButton: 'Aktif cihazlar',
        detailsTitle: 'Bu cihaz',
        detailsSubtitle: 'Şu anda bu cihazda oturum açtınız',
        destructiveActionTitle: 'Oturumu sonlandır',
        destructiveActionSubtitle: 'Bu cihazda hesabınızın oturumunu sonlandırın',
        destructiveAction: 'Cihaz oturumunu sonlandır',
      },
      web3WalletsSection: {
        title: 'Web3 cüzdanları',
        primaryButton: 'Web3 cüzdanları',
        destructiveActionTitle: 'Kaldır',
        destructiveActionSubtitle: 'Bu cüzdanı hesabınızdan kaldırın',
        destructiveAction: 'Cüzdanı kaldır',
      },
      dangerSection: {
        title: 'Tehlike',
        deleteAccountButton: 'Hesabı sil',
        deleteAccountTitle: 'Hesabı sil',
        deleteAccountDescription: 'Hesabınızı ve ilişkili tüm verilerini silin',
      },
    },
    profilePage: {
      title: 'Profili güncelle',
      imageFormTitle: 'Profil görseli',
      imageFormSubtitle: 'Görsel yükle',
      imageFormDestructiveActionSubtitle: 'Görseli kaldır',
      fileDropAreaTitle: 'Dosyayı buraya sürükle, veya...',
      fileDropAreaAction: 'Dosya seç',
      fileDropAreaHint: "10 MB'tan küçük boyutta bir JPG, PNG, GIF, veya WEBP dosyası yükle",
      successMessage: 'Profiliniz güncellendi.',
    },
    usernamePage: {
      title: 'Kullanıcı adını güncelle',
      successMessage: 'Kullanıcı adınız güncellendi.',
    },
    emailAddressPage: {
      title: 'E-posta adresi ekle',
      emailCode: {
        formHint: 'Doğrulama kodunu içeren bir e-posta belirttiğiniz adrese gönderilecektir.',
        formTitle: 'Doğrulama kodu',
        formSubtitle: '{{identifier}} adresine gönderilen doğrulama kodunu giriniz',
        resendButton: 'Yeniden gönder',
        successMessage: '{{identifier}} adresi hesabınıza eklendi.',
      },
      emailLink: {
        formHint: 'Doğrulama bağlantısını içeren bir e-posta belirttiğiniz adrese gönderilecektir.',
        formTitle: 'Doğrulama bağlantısı',
        formSubtitle: '{{identifier}} adresine gönderilen doğrulama bağlantısını tıklayınız',
        resendButton: 'Yeniden gönder',
        successMessage: '{{identifier}} adresi hesabınıza eklendi.',
      },
      removeResource: {
        title: 'E-posta adresini kaldır',
        messageLine1: '{{identifier}} adresi hesabınızdan kaldırılacaktır.',
        messageLine2: 'Artık bu e-posta adresini kullanarak oturum açmanız mümkün olmayacaktır.',
        successMessage: '{{emailAddress}} adresi hesabınızdan kaldırıldı.',
      },
    },
    phoneNumberPage: {
      title: 'Telefon numarası ekle',
      successMessage: '{{identifier}} numarası hesabınıza eklendi.',
      infoText: 'Belirtilen numaraya doğrulama kodunu içeren bir SMS gönderilecektir.',
      infoText__secondary: 'Ücretlendirmeye tabii olabilir.',
      removeResource: {
        title: 'Telefon numarasını kaldır',
        messageLine1: '{{identifier}} numarası hesabınızdan kaldırılacaktır.',
        messageLine2: 'Artık bu telefon numarasını kullanarak oturum açmanız mümkün olmayacaktır.',
        successMessage: '{{phoneNumber}} numarası hesabınızdan kaldırıldı.',
      },
    },
    connectedAccountPage: {
      title: 'Hesap bağla',
      formHint: 'Yeni bir hesap bağlamak için bir sağlayıcı seçiniz.',
      formHint__noAccounts: 'Kullanılabilir bir sağlayıcı yok.',
      socialButtonsBlockButton: '{{provider|titleize}} hesabı bağla',
      successMessage: 'Sağlayıcı hesabınıza bağlandı.',
      removeResource: {
        title: 'Bağlı hesabı kaldır',
        messageLine1: '{{identifier}} hesabınızdan kaldırılacaktır.',
        messageLine2:
          'Artık bu bağlı hesabı kullanarak oturum açmanız mümkün olmayacaktır ve buna bağlı özellikler çalışmayacaktır.',
        successMessage: '{{connectedAccount}} hesabınızdan kaldırıldı.',
      },
    },
    web3WalletPage: {
      title: 'Web3 cüzdanı ekle',
      subtitle__availableWallets: 'Hesabınıza eklemek için bir web3 cüzdanı seçiniz.',
      subtitle__unavailableWallets: 'Kullanılabilir bir web3 cüzdanı yok.',
      successMessage: 'Web3 cüzdanınız hesabınıza eklendi.',
      removeResource: {
        title: 'Web3 cüzdanını kaldır',
        messageLine1: '{{identifier}} cüzdanı hesabınızdan kaldırılacaktır.',
        messageLine2: 'Artık bu cüzdanı kullanarak oturum açmanız mümkün olmayacaktır.',
        successMessage: '{{web3Wallet}} cüzdanı hesabınızdan kaldırıldı.',
      },
    },
    passwordPage: {
      title: 'Şifreyi değiştir',
      changePasswordTitle: 'Yeni şifre girin',
      successMessage: 'Şifreniz başarıyla değiştirildi.',
      changePasswordSuccessMessage: 'Şifreniz günceellendi.',
      sessionsSignedOutSuccessMessage: 'Diğer tüm cihazlardaki oturumlarınız sonlandırıldı.',
    },
    mfaPage: {
      title: 'İki aşamalı doğrulama yöntemi ekle',
      formHint: 'Eklemek için bir yöntem seçiniz.',
    },
    mfaTOTPPage: {
      title: 'Authenticator uygulaması ekle',
      verifyTitle: 'Doğrulama kodu',
      verifySubtitle: 'Authenticator uygulamanızda oluşturulan doğrulama kodunu giriniz',
      successMessage:
        'İki aşamalı doğrulama yöntemi başarıyla eklendi. Oturum açarken, ek bir adım olarak bu doğrulayıcıdan bir doğrulama kodu girmeniz gerekecektir.',
      authenticatorApp: {
        infoText__ableToScan:
          'Authenticator uygulamanızda yeni bir giriş yöntemi ayarlayın ve hesabınızla bağlamak için aşağıdaki QR kodunu tarayın.',
        infoText__unableToScan:
          'Authenticator uygulamanızda yeni bir giriş yöntemi ekleme seçeneğini bulun ve aşağıda verilen değeri girin:',
        inputLabel__unableToScan1:
          'Zaman bazlı veya tek seferlik şifrelerin etkinleştirildiğinden emin olun, ardından hesabınızı bağlamayı tamamlayın.',
        inputLabel__unableToScan2:
          'Alternatif olarak doğrulayıcınız TOTP URI’leri destekliyorsa, tam URI’yi de kopyalayabilirsiniz.',
        buttonAbleToScan__nonPrimary: 'Veya QR kodunu tarat',
        buttonUnableToScan__nonPrimary: 'QR kodunu tarayamıyorum',
      },
      removeResource: {
        title: 'İki aşamalı doğrulamayı kaldır',
        messageLine1: "Artık giriş yaparken authenticator'dan gelecek doğrulama kodları gerekmeyecektir.",
        messageLine2: 'Hesabınızın güvenliği azalabilir. Devam etmek istediğinizden emin misiniz?',
        successMessage: 'İki aşamalı doğrulama yöntemi kaldırıldı.',
      },
    },
    mfaPhoneCodePage: {
      title: 'SMS kodu doğrulaması ekle',
      primaryButton__addPhoneNumber: 'Telefon numarası ekle',
      subtitle__availablePhoneNumbers: 'İki aşamalı SMS kodu doğrulaması için bir telefon numarası seçin.',
      subtitle__unavailablePhoneNumbers:
        'İki aşamalı SMS kodu doğrulaması için kullanılabilir bir telefon numarası yok.',
      successMessage:
        'İki aşamalı doğrulama yöntemi başarıyla eklendi. Oturum açarken, ek bir adım olarak bu telefon numarasına gönderilen bir doğrulama kodu girmeniz gerekecektir.',
      removeResource: {
        title: 'İki aşamalı doğrulamayı kaldır',
        messageLine1: 'Giriş yaparken artık {{identifier}} numarasına SMS kodu gönderilmeyecektir.',
        messageLine2: 'Hesabınızın güvenliği azalabilir. Devam etmek istediğinizden emin misiniz?',
        successMessage: 'İki aşamalı SMS kodu doğrulaması {{mfaPhoneCode}} numarasından kaldırıldı.',
      },
    },
    backupCodePage: {
      title: 'Yedekleme kodu doğrulaması ekle',
      title__codelist: 'Yedekleme kodları',
      subtitle__codelist: 'Yedekleme kodlarınızı güvenli bir yerde saklayın.',
      infoText1: 'Yedekleme kodları bu hesap için etkinleştirilecektir.',
      infoText2:
        'Yedekleme kodlarınızı güvenli bir yerde saklayın. Eğer bu kodlarınızın başkasının eline geçtiğini düşünürseniz, yenilerini oluşturabilirsiniz.',
      successSubtitle:
        'Eğer Authenticator uygulamanızın olduğu cihazınıza erişiminizi kaybederseniz, bu kodlardan birini kullanarak hesabınıza giriş yapabilirsiniz.',
      successMessage:
        'Yedekleme kodları başarıyla eklendi. Eğer Authenticator uygulamanızın olduğu cihaza erişiminizi kaybettiyseniz, oturum açarken bu kodlardan birini girebilirsiniz. Her kod en fazla bir kez kullanılabilir.',
      actionLabel__copy: 'Hepsini kopayala',
      actionLabel__copied: 'Kopyalandı!',
      actionLabel__download: '.txt olarak indir',
      actionLabel__print: 'Yazdır',
    },
  },
  userButton: {
    action__manageAccount: 'Hesabı yönet',
    action__signOut: 'Çıkış yap',
    action__signOutAll: 'Tüm hesaplardan çıkış yap',
    action__addAccount: 'Hesap ekle',
  },
  organizationSwitcher: {
    personalWorkspace: 'Kişisel Çalışma Alanı',
    notSelected: 'Organizasyon seçilmedi',
    action__createOrganization: 'Organizasyon oluştur',
    action__manageOrganization: 'Organizasyonu yönet',
  },
  impersonationFab: {
    title: '{{identifier}} olarak giriş yapıldı',
    action__signOut: 'Çıkış yap',
  },
  organizationProfile: {
    start: {
      headerTitle__members: 'Üyeler',
      headerTitle__settings: 'Ayarlar',
    },
    profilePage: {
      title: 'Organizasyon profili',
      subtitle: 'Organizasyon profilini düzenle',
      successMessage: 'Organizasyon güncellendi.',
      dangerSection: {
        title: 'Tehlike',
        leaveOrganization: {
          title: 'Organizasyondan ayrıl',
          messageLine1:
            'Bu organizasyondan ayrılmak istediğinizden emin misiniz? Bu organizasyona ve uygulamalarına erişiminizi kaybedeceksiniz.',
          messageLine2: 'bu eylem kalıcıdır ve geri alınamaz.',
          successMessage: 'Organizasyondan ayrıldınız.',
        },
      },
    },
    invitePage: {
      title: 'Davetiye gönder',
      subtitle: 'Bu organizasyona yeni üyeler davet edin',
      successMessage: 'Davetiyeler başarıyla gönderildi',
      detailsTitle__inviteFailed: 'Daveiyeler gönderilemedi. Aşağıda belirtilen sorunları giderip tekrar deneyin:',
      formButtonPrimary__continue: 'Davetiye gönder',
    },
    membersPage: {
      detailsTitle__emptyRow: 'Gösterilecek üye yok',
      action__invite: 'Davet et',
      start: {},
      activeMembersTab: {
        tableHeader__user: 'Kullanıcı',
        tableHeader__joined: 'Katılma tarihi',
        tableHeader__role: 'Rolü',
        tableHeader__actions: '',
        menuAction__remove: 'Üyeyi kaldır',
      },
      invitedMembersTab: {
        tableHeader__invited: 'Davetliler',
        menuAction__revoke: 'Davetiyeyi iptal et',
      },
    },
  },
  createOrganization: {
    title: 'Organizasyon oluştur',
    formButtonSubmit: 'Oluştur',
    invitePage: {
      formButtonReset: 'Atla',
    },
  },
  unstable__errors: {
    form_identifier_not_found: '',
    form_password_pwned:
      'Bu şifre bir veri saldırısında ele geçirildiği için kullanılamaz. Lütfen başka bir şifre deneyin.',
    form_username_invalid_length: '',
    form_username_invalid_character: '',
    form_param_format_invalid: '',
    form_password_length_too_short: '',
    form_param_nil: '',
    form_code_incorrect: 'Hatalı kod',
    form_password_incorrect: '',
    not_allowed_access: '',
    form_identifier_exists: '',
    form_password_validation_failed: 'Geçersiz şifre',
    form_password_not_strong_enough: 'Şifreniz fazla zayıf',
    form_password_size_in_bytes_exceeded:
      'Şifrenize ayrılan depolama alanını aştınız. Lütfen daha kısa bir şifre deneyin.',
    passwordComplexity: {
      sentencePrefix: 'Şifreniz;',
      minimumLength: '{{length}} veya daha fazla karakter içermeli',
      maximumLength: '{{length}} karakterden kısa olmalı',
      requireNumbers: 'bir sayı içermeli',
      requireLowercase: 'bir küçük harf içermeli',
      requireUppercase: 'bir büyük harf içermeli',
      requireSpecialCharacter: 'bir özel karakter içermeli',
    },
    zxcvbn: {
      notEnough: 'Şifreniz fazla zayıf',
      couldBeStronger: 'Şifreniz kriterleri sağlıyor, birkaç karakter daha eklerseniz daha güçlü olacaktır.',
      goodPassword: 'Harika! Şifreniz güçlü.',
      warnings: {
        straightRow: 'Klavyede ardışık karakterler kolay tahmin edilir.',
        keyPattern: 'Kısa klavye desenleri kolay tahmin edilir.',
        simpleRepeat: 'Tekrarlanan karakterler kolay tahmin edilir.',
        extendedRepeat: '"abcabcabc" gibi tekrarlanan desenler kolay tahmin edilir.',
        sequences: '"abc" gibi yaygın desenlerin tahmini kolaydır.',
        recentYears: 'Yakın yıllar kolay tahmin edilir.',
        dates: 'Tarihleri tahmin etmek kolaydır.',
        topTen: 'Bu epey yaygın bir şifre.',
        topHundred: 'Bu çok yaygın bir şifre.',
        common: 'Bu yaygın bir şifre.',
        similarToCommon: 'Bu yaygın kullanılan şifrelere çok benziyor.',
        wordByItself: 'Tek sözcükler kolay tahmin edilir.',
        namesByThemselves: 'Adlar ya da soyadlar kolay tahmin edilir.',
        commonNames: 'Yaygın adlar ve soyadlar kolay tahmin edilir.',
        userInputs: 'Şifreniz kişisel bilgiler içermemeli.',
        pwned: 'Bu şifre bir veri saldırısında ele geçirilmiş.',
      },
      suggestions: {
        l33t: '"a" yerine "@" kullanmak gibi tahmin edilebilir harf ikamelerinden kaçının.',
        reverseWords: 'Yaygın kelimelerin tersini kullanmaktan kaçının.',
        allUppercase: 'Tüm harfleri büyük yazmak yerine rastgele büyük harfler kullanın.',
        capitalization: 'Sadece ilk harfi büyük yazmak yerine rastgele büyük harfler kullanın.',
        dates: 'Kendinizle alakası olan tarihleri kullanmayın.',
        recentYears: 'Günümüze yakın yılları kullanmayın.',
        associatedYears: 'Kendinizle alakası olan yılları kullanmayın.',
        sequences: 'Yaygın desenleri kullanmayın.',
        repeated: 'Kelime veya karakterleri tekrarlamayın.',
        longerKeyboardPattern: 'Elinizin yönünü birden çok değiştirerek yazdığınız uzun klavye desenleri kullanın.',
        anotherWord: 'Şifreniz nadir görülen sözcüklerden daha fazla içersin.',
        useWords: 'Birden çok sözcük kullanın ama yaygın deyişlerden kaçının.',
        noNeed: 'Özel karakter, sayı veya büyük harf kullanmadan da güçlü bir şifre oluşturabilirsiniz.',
        pwned: 'Bu şifreyi başka bir yerde kullanıyorsanız, değiştirseniz iyi olur.',
      },
    },
  },
  dates: {
    previous6Days: "Geçen hafta {{ date | weekday('tr-TR','long') }} saat {{ date | timeString('tr-TR') }}",
    lastDay: "Dün saat {{ date | timeString('tr-TR') }}",
    sameDay: "Bugün saat {{ date | timeString('tr-TR') }}",
    nextDay: "Yarın saat {{ date | timeString('tr-TR') }}",
    next6Days: "{{ date | weekday('tr-TR','long') }} saat {{ date | timeString('tr-TR') }}",
    numeric: "{{ date | numeric('tr-TR') }}",
  },
} as const;
