import * as stylex from '@stylexjs/stylex';
import type { FormEvent, ReactNode } from 'react';
import { useId } from 'react';

import { AlertDialog } from '../components/alert-dialog';
import { Button, SubmitButton } from '../components/button';
import { Card } from '../components/card';
import { Dialog, type DialogProps } from '../components/dialog';
import { Field } from '../components/field';
import { Heading } from '../components/heading';
import { Text } from '../components/text';
import { themeProps } from '../props';
import { CodeInput, PhoneInput, ResendButton } from './dialogs/security-dialog-chrome';
import type { UserProfileMfaAddFlowState, UserProfileMfaRemoveFlowState } from './dialogs/flow.types';
import { mfaDialogStyles as styles } from './user-profile-mfa-dialog.styles';

export interface UserProfileMfaAddDialogViewProps extends Pick<DialogProps, 'open' | 'defaultOpen' | 'onOpenChange'> {
  state: UserProfileMfaAddFlowState;
  verificationDialog?: ReactNode;
  onPhoneNumberChange: (value: string) => void;
  onCodeChange: (value: string) => void;
  onSubmit: (completedCode?: string) => void;
  onResend: () => void;
  onToggleDisplayFormat: () => void;
}

export function UserProfileMfaAddDialogView({
  state,
  verificationDialog,
  onPhoneNumberChange,
  onCodeChange,
  onSubmit,
  onResend,
  onToggleDisplayFormat,
  ...dialogProps
}: UserProfileMfaAddDialogViewProps) {
  const title = state.method === 'sms' ? 'Add phone number' : 'Add authenticator app';
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!state.isSubmitting) {
      onSubmit();
    }
  };

  return (
    <Dialog.Root
      size='card'
      closedBy='closerequest'
      {...dialogProps}
    >
      <Dialog.Portal>
        <Dialog.Backdrop />
        <Dialog.Viewport>
          <Dialog.Popup
            render={
              <Card.Root
                elevation='overlay'
                renderBranding={false}
              />
            }
          >
            <Dialog.CloseButton />
            <form
              onSubmit={submit}
              {...stylex.props(styles.form)}
            >
              <Card.Header>
                <Dialog.Title render={<Heading size='sm' />}>{title}</Dialog.Title>
                <Dialog.Description render={<Text />}>
                  <AddDescription state={state} />
                </Dialog.Description>
              </Card.Header>
              <Card.Content {...stylex.props(styles.content)}>
                <AddContent
                  state={state}
                  onCodeChange={onCodeChange}
                  onPhoneNumberChange={onPhoneNumberChange}
                  onResend={onResend}
                  onSubmit={onSubmit}
                  onToggleDisplayFormat={onToggleDisplayFormat}
                />
                {state.errors.form ? (
                  <Text
                    color='negative'
                    role='alert'
                  >
                    {state.errors.form}
                  </Text>
                ) : null}
              </Card.Content>
              <Card.Footer {...themeProps('user-profile-mfa-add-dialog-actions')}>
                <Dialog.Close
                  render={props => (
                    <Button
                      {...props}
                      {...stylex.props(styles.footerButton)}
                      variant='outline'
                    >
                      Cancel
                    </Button>
                  )}
                />
                <SubmitButton
                  disabled={!canSubmit(state)}
                  isPending={state.isSubmitting || (state.step === 'verify' && state.status === 'verifying')}
                  pendingLabel={state.step === 'verify' ? 'Verifying code' : 'Continuing'}
                  {...stylex.props(styles.footerButton)}
                >
                  {state.step === 'verify' ? 'Verify' : 'Continue'}
                </SubmitButton>
              </Card.Footer>
            </form>
          </Dialog.Popup>
        </Dialog.Viewport>
      </Dialog.Portal>
      {verificationDialog}
    </Dialog.Root>
  );
}

function AddDescription({ state }: { state: UserProfileMfaAddFlowState }) {
  if (state.step === 'phone') {
    return <>We&apos;ll send a verification code to this phone number.</>;
  }
  if (state.step === 'setup') {
    return <>Scan the QR code with your authenticator app, then continue.</>;
  }
  if (state.method === 'sms') {
    return <>Enter the verification code sent to {state.identifier}.</>;
  }
  return <>Enter the verification code generated by your authenticator app.</>;
}

function AddContent({
  state,
  onPhoneNumberChange,
  onCodeChange,
  onSubmit,
  onResend,
  onToggleDisplayFormat,
}: Pick<
  UserProfileMfaAddDialogViewProps,
  'state' | 'onPhoneNumberChange' | 'onCodeChange' | 'onSubmit' | 'onResend' | 'onToggleDisplayFormat'
>) {
  const fieldId = useId();

  if (state.step === 'phone') {
    return (
      <Field.Root
        required
        disabled={state.isSubmitting}
        invalid={Boolean(state.errors.field)}
        {...stylex.props(styles.field)}
      >
        <Field.Label htmlFor={fieldId}>Phone number</Field.Label>
        <PhoneInput
          disabled={state.isSubmitting}
          id={fieldId}
          value={state.phoneNumber}
          onChange={onPhoneNumberChange}
        />
        {state.errors.field ? <Field.Error>{state.errors.field}</Field.Error> : null}
      </Field.Root>
    );
  }

  if (state.step === 'setup') {
    return (
      <div {...stylex.props(styles.setup)}>
        {state.displayFormat === 'qr' ? (
          <div
            aria-label='Authenticator QR code'
            role='img'
            {...stylex.props(styles.qrPlaceholder)}
          >
            QR code
          </div>
        ) : (
          <Text
            render={<code />}
            {...stylex.props(styles.secret)}
          >
            {state.secret}
          </Text>
        )}
        <Button
          color='neutral'
          size='sm'
          type='button'
          variant='link'
          onClick={onToggleDisplayFormat}
        >
          {state.displayFormat === 'qr' ? "Can't scan the QR code?" : 'Scan QR code instead'}
        </Button>
      </div>
    );
  }

  return (
    <>
      <Field.Root
        required
        disabled={state.isSubmitting || state.status === 'verifying'}
        invalid={state.status === 'error'}
        {...stylex.props(styles.field)}
      >
        <Field.Label htmlFor={fieldId}>Verification code</Field.Label>
        <CodeInput
          id={fieldId}
          status={state.status}
          value={state.code}
          onChange={onCodeChange}
          onComplete={onSubmit}
        />
        {state.errors.field ? <Field.Error>{state.errors.field}</Field.Error> : null}
      </Field.Root>
      {state.method === 'sms' ? (
        <div {...stylex.props(styles.resend)}>
          <Text color='neutral'>Didn&apos;t receive a code?</Text>
          <ResendButton
            disabled={state.isSubmitting || state.status === 'verifying'}
            label='Resend'
            resend={state.resend}
            onResend={onResend}
          />
        </div>
      ) : null}
    </>
  );
}

function canSubmit(state: UserProfileMfaAddFlowState) {
  if (state.step === 'phone') {
    return state.phoneNumber.length > 3;
  }
  if (state.step === 'verify') {
    return state.code.length === 6 && state.status !== 'verifying';
  }
  return true;
}

export interface UserProfileMfaRemoveDialogViewProps {
  open?: boolean;
  state: UserProfileMfaRemoveFlowState;
  verificationDialog?: ReactNode;
  onOpenChange?: (open: boolean) => void;
  onRemove: () => void;
}

export function UserProfileMfaRemoveDialogView({
  state,
  verificationDialog,
  onRemove,
  ...dialogProps
}: UserProfileMfaRemoveDialogViewProps) {
  const methodName = state.method === 'sms' ? 'phone number' : 'authenticator app';

  return (
    <AlertDialog.Root {...dialogProps}>
      <AlertDialog.Portal>
        <AlertDialog.Backdrop />
        <AlertDialog.Viewport>
          <AlertDialog.Popup>
            <AlertDialog.Title render={<Heading size='sm' />}>Remove {methodName}</AlertDialog.Title>
            <AlertDialog.Description render={<Text />}>
              {state.method === 'sms'
                ? `${state.label} will no longer receive verification codes when you sign in.`
                : 'Verification codes from this authenticator will no longer be required when you sign in.'}
            </AlertDialog.Description>
            {state.errors.form ? (
              <Text
                color='negative'
                role='alert'
              >
                {state.errors.form}
              </Text>
            ) : null}
            <AlertDialog.Actions>
              <AlertDialog.Close render={<Button variant='outline' />}>Cancel</AlertDialog.Close>
              <SubmitButton
                color='negative'
                isPending={state.isSubmitting}
                pendingLabel={`Removing ${methodName}`}
                type='button'
                onClick={onRemove}
              >
                Remove
              </SubmitButton>
            </AlertDialog.Actions>
          </AlertDialog.Popup>
        </AlertDialog.Viewport>
      </AlertDialog.Portal>
      {verificationDialog}
    </AlertDialog.Root>
  );
}
