/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsAdd } from "../funcs/domainsAdd.js";
import { domainsDelete } from "../funcs/domainsDelete.js";
import { domainsList } from "../funcs/domainsList.js";
import { domainsUpdate } from "../funcs/domainsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Domains extends ClientSDK {
  /**
   * List all instance domains
   *
   * @remarks
   * Use this endpoint to get a list of all domains for an instance.
   * The response will contain the primary domain for the instance and any satellite domains. Each domain in the response contains information about the URLs where Clerk operates and the required CNAME targets.
   */
  async list(
    options?: RequestOptions,
  ): Promise<components.Domains> {
    return unwrapAsync(domainsList(
      this,
      options,
    ));
  }

  /**
   * Add a domain
   *
   * @remarks
   * Add a new domain for your instance.
   * Useful in the case of multi-domain instances, allows adding satellite domains to an instance.
   * The new domain must have a `name`. The domain name can contain the port for development instances, like `localhost:3000`.
   * At the moment, instances can have only one primary domain, so the `is_satellite` parameter must be set to `true`.
   * If you're planning to configure the new satellite domain to run behind a proxy, pass the `proxy_url` parameter accordingly.
   */
  async add(
    request?: operations.AddDomainRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<components.Domain> {
    return unwrapAsync(domainsAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a satellite domain
   *
   * @remarks
   * Deletes a satellite domain for the instance.
   * It is currently not possible to delete the instance's primary domain.
   */
  async delete(
    domainId: string,
    options?: RequestOptions,
  ): Promise<components.DeletedObject> {
    return unwrapAsync(domainsDelete(
      this,
      domainId,
      options,
    ));
  }

  /**
   * Update a domain
   *
   * @remarks
   * The `proxy_url` can be updated only for production instances.
   * Update one of the instance's domains. Both primary and satellite domains can be updated.
   * If you choose to use Clerk via proxy, use this endpoint to specify the `proxy_url`.
   * Whenever you decide you'd rather switch to DNS setup for Clerk, simply set `proxy_url`
   * to `null` for the domain. When you update a production instance's primary domain name,
   * you have to make sure that you've completed all the necessary setup steps for DNS and
   * emails to work. Expect downtime otherwise. Updating a primary domain's name will also
   * update the instance's home origin, affecting the default application paths.
   */
  async update(
    request: operations.UpdateDomainRequest,
    options?: RequestOptions,
  ): Promise<components.Domain> {
    return unwrapAsync(domainsUpdate(
      this,
      request,
      options,
    ));
  }
}
