/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testingTokensCreate } from "../funcs/testingTokensCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TestingTokens extends ClientSDK {
  /**
   * Retrieve a new testing token
   *
   * @remarks
   * Retrieve a new testing token.
   */
  async create(
    options?: RequestOptions,
  ): Promise<components.TestingToken> {
    return unwrapAsync(testingTokensCreate(
      this,
      options,
    ));
  }
}
