/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserPasskeyDeleteRequest = {
  /**
   * The ID of the user that owns the passkey identity
   */
  userId: string;
  /**
   * The ID of the passkey identity to be deleted
   */
  passkeyIdentificationId: string;
};

/** @internal */
export const UserPasskeyDeleteRequest$inboundSchema: z.ZodType<
  UserPasskeyDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  passkey_identification_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "passkey_identification_id": "passkeyIdentificationId",
  });
});

/** @internal */
export type UserPasskeyDeleteRequest$Outbound = {
  user_id: string;
  passkey_identification_id: string;
};

/** @internal */
export const UserPasskeyDeleteRequest$outboundSchema: z.ZodType<
  UserPasskeyDeleteRequest$Outbound,
  z.ZodTypeDef,
  UserPasskeyDeleteRequest
> = z.object({
  userId: z.string(),
  passkeyIdentificationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
    passkeyIdentificationId: "passkey_identification_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserPasskeyDeleteRequest$ {
  /** @deprecated use `UserPasskeyDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = UserPasskeyDeleteRequest$inboundSchema;
  /** @deprecated use `UserPasskeyDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = UserPasskeyDeleteRequest$outboundSchema;
  /** @deprecated use `UserPasskeyDeleteRequest$Outbound` instead. */
  export type Outbound = UserPasskeyDeleteRequest$Outbound;
}

export function userPasskeyDeleteRequestToJSON(
  userPasskeyDeleteRequest: UserPasskeyDeleteRequest,
): string {
  return JSON.stringify(
    UserPasskeyDeleteRequest$outboundSchema.parse(userPasskeyDeleteRequest),
  );
}

export function userPasskeyDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<UserPasskeyDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasskeyDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasskeyDeleteRequest' from JSON`,
  );
}
