
name: Setup Action
description: Checkout, setup node and dependencies
inputs:
  node-version:
    description: 'The node version to use'
    required: false
    default: '18'
  playwright-enabled:
    description: 'Enable Playwright?'
    required: false
    default: 'false'
  turbo-enabled:
    description: 'Enable Turbo?'
    required: false
    default: 'true'
  turbo-cache-dir:
    description: 'The cache dir to use for Turbo'
    required: false
    default: './.turbo-cache'
  turbo-signature:
    description: 'The signature to use for Turbo'
    required: false
  turbo-remote-only:
    description: 'Only use remote cache?'
    required: false
    default: 'true'
  turbo-team:
    description: 'The team to use for Turbo remote auth'
    required: true
  turbo-token:
    description: 'The token to use for Turbo remote auth'
    required: true

outputs:
  turbo-args:
    description: 'The args to use for Turbo'
    value: ${{ steps.env-vars.outputs.turbo-args }}

runs:
  using: "composite"
  steps:
    - name: Configure Turborepo
      id: turbo
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const os = require('os')
          const cpus =
            typeof os.availableParallelism === "function"
              ? os.availableParallelism()
              : os.cpus().length;

          const turbo = {
            enabled: core.getInput('turbo-enabled') === 'true',
            cacheDir: core.getInput('turbo-cache-dir'),
            signature: core.getInput('turbo-signature'),
            remoteOnly: core.getInput('turbo-remote-only'),
            team: core.getInput('turbo-team', { required: true }),
            token: core.getInput('turbo-token', { required: true }),
          }

          const turboArgs = [
            '--output-logs=new-only',
            `--cache-dir=${turbo.cacheDir}`,
            `--concurrency=${cpus}`
          ];

          if (turbo.enabled) {
            turboArgs.push(
              `--team=${turbo.team}`,
              `--token=${turbo.token}`,
              `--remote-only=${turbo.remoteOnly}`,
            )
          }

          core.setOutput('turbo-args', turboArgs.join(' '));
          core.exportVariable('FORCE_COLOR', '1')

          if (turbo.signature && turbo.signature !== '') {
            core.exportVariable('TURBO_REMOTE_CACHE_SIGNATURE_KEY')
          }

    - name: Setup NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install NPM Dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci --audit=false --fund=false
      shell: bash

    - name: Get Playwright Version
      if: inputs.playwright-enabled == 'true'
      shell: bash
      id: playwright-version
      run: echo "VERSION=$(node -e "console.log($(npm ls @playwright/test --json).dependencies['@playwright/test'].version)")" >> "$GITHUB_OUTPUT"

    - name: Cache Playwright Binaries
      if: inputs.playwright-enabled == 'true'
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-playwright-${{ steps.playwright-version.outputs.VERSION }}

    - name: Install Playwright Browsers
      if: inputs.playwright-enabled == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps
