name: Setup Action
description: Checkout, setup node and dependencies
inputs:
  node-version:
    description: 'The node version to use'
    required: false
    # This is pinned to `18.20.2` because `18.20.3` bumps npm from `10.5.0` to `10.7.0`, which causes our verdaccio setup to fail (see SDK-1793).
    # TODO: Update workflows/ci.yml when this isn't pinned anymore.
    default: '18.20.2'
  playwright-enabled:
    description: 'Enable Playwright?'
    required: false
    default: 'false'
  turbo-summarize:
    description: 'The token to use for Turbo task summaries'
    required: false
    default: 'false'
  turbo-enabled:
    description: 'Enable Turbo?'
    required: false
    default: 'true'
  turbo-cache-dir:
    description: 'The cache dir to use for Turbo'
    required: false
    default: './.turbo-cache'
  turbo-signature:
    description: 'The signature to use for Turbo'
    required: false
  turbo-remote-only:
    description: 'Only use remote cache?'
    required: false
    default: 'true'
  turbo-team:
    description: 'The team to use for Turbo remote auth'
    required: true
  turbo-token:
    description: 'The token to use for Turbo remote auth'
    required: true
  registry-url:
    description: 'The registry the packages will be published to'
    required: false
    default: ''
  verbose:
    description: 'Enable verbose output'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Configure Turborepo
      id: turbo
      uses: actions/github-script@v7
      env:
        # envs are required to pass inputs to the script
        ENABLED: ${{ inputs.turbo-enabled }}
        CACHE_DIR: ${{ inputs.turbo-cache-dir }}
        REMOTE_ONLY: ${{ inputs.turbo-remote-only }}
        SIGNATURE: ${{ inputs.turbo-signature }}
        SUMMARIZE: ${{ inputs.turbo-summarize }}
        TEAM: ${{ inputs.turbo-team }}
        TOKEN: ${{ inputs.turbo-token }}
        VERBOSE: ${{ inputs.verbose }}
      with:
        script: |
          const os = require('os')
          const cpus =
            typeof os.availableParallelism === "function"
              ? os.availableParallelism()
              : os.cpus().length;

          const { ENABLED, CACHE_DIR, SIGNATURE, REMOTE_ONLY, SUMMARIZE, TEAM, TOKEN, VERBOSE } = process.env

          const ARGS = [
            `--cache-dir=${CACHE_DIR}`,
            `--concurrency=${cpus}`,
            `--summarize=${SUMMARIZE}`,
          ]

          if (VERBOSE === 'true') {
            ARGS.push('--verbosity=2')
            ARGS.push('--log-order=stream')
            ARGS.push('--output-logs=full')
          } else {
            ARGS.push('--output-logs=new-only')
          }

          core.exportVariable('TURBO_ARGS',
            ARGS.join(' ')
          )

          if (ENABLED === 'true') {
            core.exportVariable('TURBO_TEAM', TEAM)
            core.exportVariable('TURBO_TOKEN', TOKEN)
            core.exportVariable('TURBO_REMOTE_ONLY', REMOTE_ONLY)
          }

          if (SIGNATURE && SIGNATURE !== '') {
            core.exportVariable('TURBO_REMOTE_CACHE_SIGNATURE_KEY', SIGNATURE)
          }

          core.exportVariable('FORCE_COLOR', '1')

    - name: Turborepo CLI Args
      shell: bash
      run: echo $TURBO_ARGS

    - name: Setup NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Restore node_modules
      id: cache-node-modules
      uses: actions/cache/restore@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}-${{ inputs.node-version }}

    - name: Install NPM Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true' # Don't run if it's an **exact** match
      run: mkdir node_modules && npm ci --audit=false --fund=false --prefer-offline && npm prune
      shell: bash

    - name: Save node_modules
      uses: actions/cache/save@v3
      with:
        path: node_modules
        key: ${{ steps.cache-node-modules.outputs.cache-primary-key }}

    - name: Get Playwright Version
      if: inputs.playwright-enabled == 'true'
      shell: bash
      id: playwright-version
      run: echo "VERSION=$(node -e "console.log($(npm ls @playwright/test --json).dependencies['@playwright/test'].version)")" >> "$GITHUB_OUTPUT"

    - name: Cache Playwright Binaries
      if: inputs.playwright-enabled == 'true'
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-playwright-${{ steps.playwright-version.outputs.VERSION }}-v2

    - name: Install Playwright Browsers
      if: inputs.playwright-enabled == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx playwright install chromium
