on:
  workflow_call:

jobs:
  check:
    runs-on: ${{ vars.RUNNER_LARGE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          use-turbo-cache: 'false'
      - run: npm run format:check
