on:
  workflow_call:

jobs:
  build:
    # if: ${{ github.repository == 'clerk/javascript' }}
    runs-on: ${{ vars.RUNNER_NORMAL }}
    timeout-minutes: ${{  fromJSON(vars.TIMEOUT_MINUTES_NORMAL) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: npm run build
      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-artifacts
          path: ./node_modules/.cache/turbo
          retention-days: 1
      - name: Configure npm to use Verdaccio
        run: |
          npm set registry http://localhost:4873/
          nohup ./node_modules/.bin/verdaccio --config ./verdaccio.publish.yaml &
          sleep 5
          ./node_modules/.bin/npm-cli-adduser -u user -p pass -e test@test.com -r http://localhost:4873/
          ./node_modules/.bin/npm-cli-login -u user -p pass -e test@test.com -r http://localhost:4873/
      - name: Publish to Verdaccio
        # The command below includes a sanity check
        # and fails early if the default npm registry is used
        run: |
          npm run release:verdaccio
      - name: List published packages
        run: |
          ls -all .verdaccio/storage/@clerk
      - uses: actions/upload-artifact@v3
        with:
          name: verdaccio
          path: .verdaccio
