name: 'Lock stale PRs and issues'

on:
  workflow_dispatch:
  schedule:
    # This runs 4 times a day:
    # https://crontab.guru/#0_0,12_*_*_*
    - cron: '0 0,6,12,18 * * *'

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 14
          pr-inactive-days: 14
          log-output: true