name: Quality checks

on:
  merge_group:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Check format
    runs-on: ${{ vars.RUNNER_NORMAL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - run: npm run format:check

  changeset:
      name: Require changeset
      runs-on: ${{ vars.RUNNER_NORMAL }}
      concurrency:
        group: require-changeset-${{ github.ref }}
        cancel-in-progress: true
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            ref: ${{github.event.pull_request.head.sha}}
            fetch-depth: 0
        - name: Setup
          uses: ./.github/actions/setup
        - run: npx changeset status --since=origin/main
