name: Quality checks

on:
#  push:
#    branches: [ main ]
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [ 18, 19 ]
    env:
      # Bundlewatch
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
      CI_REPO_OWNER: clerkinc
      CI_REPO_NAME: javascript
      CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      CI_BRANCH: ${{ github.ref	}}
      CI_BRANCH_BASE: refs/heads/develop
    name: Build and test
    runs-on: ubuntu-latest
    concurrency:
      group: tests-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test:ci
      - run: npm run bundlewatch

  prettier:
    name: Check format
    runs-on: ubuntu-latest
    concurrency:
      group: formatter-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - run: npm run format:check

  changeset:
      name: Require changeset
      runs-on: ubuntu-latest
      concurrency:
        group: require-changeset-${{ github.ref }}
        cancel-in-progress: true
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            ref: ${{github.event.pull_request.head.sha}}
            fetch-depth: 0
        - name: Setup
          uses: ./.github/actions/setup
        - run: npx changeset status --since=origin/main
