on:
  workflow_call:

jobs:
  registry:
    runs-on: ${{ vars.RUNNER_NORMAL }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download turbo cache
        uses: actions/download-artifact@v3
        with:
          name: package-artifacts
          path: ./node_modules/.cache/turbo
      - name: Configure npm to use Verdaccio
        run: |
          npm set registry http://localhost:4873/
      # The command below includes a sanity check
      # and fails early if the default npm registry is used
      - name: Publish to Verdaccio
        run: |
          nohup verdaccio --config ./verdaccio.publish.yaml &
          npm run release:verdaccio
      - name: List published packages
        run: |
          ls -all .verdaccio_storage/@clerk
      - uses: actions/upload-artifact@v3
        with:
          name: verdaccio-storage
          path: .verdaccio_storage
