name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Validate Renovate Config
        run: npx --yes --package renovate@43.150.0 renovate-config-validator
